Generating questions state
ua-dev-front/crossword-master pull request #101
Opened 2022-10-18 16:57 UTC by Fybex

Fixes #96

2022-10-19 20:21 UTC, Fybex commented
Можливо треба перемістити з компонента `App` `getTabByModeAndIsSelected`, `getLoaderLabel` та імпортувати.
Також не впевнений чи варто залишати options-buttons-wrapper в `App`, але не знаю як його абстрагована версія повинна виглядати

2022-10-20 10:42 UTC, danmysak requested changes

2022-10-20 10:42 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +      <div className='option-buttons-wrapper'>
Клас названо не по BEM’у.

2022-10-20 10:44 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +      <div className='option-buttons-wrapper'>
А щодо коментаря до PR, то я теж не бачу очевидних шляхів абстракції. Хай лишається поки як є (крім назви класу). Потім, можливо, проясниться.

2022-10-20 13:16 UTC, danmysak requested changes

2022-10-20 13:16 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +    );
Не бачу потреби в цих проміжних змінних.

2022-10-20 17:19 UTC, danmysak approved these changes

2022-10-22 05:54 UTC, TeksPeks approved these changes

2022-10-22 06:11 UTC, merged