Fix no adjacent cells error
ua-dev-front/crossword-master pull request #104
Opened 2022-10-20 15:47 UTC by TeksPeks

Fixes #98 
Якщо у клітинки нема сусідів, то вона не буде вважатися окремим словом в алгоритмі генерації, через що слова будуть пусті, що не було передбачено в алгоритмі розв'язування і викликало помилку. Зробив так що це не призводить до помилки і повертається `None`, тому, що мені здається логічним що одна клітинка - не слово, в цьому випадку ще треба напевно зробити щоб кнопка 'generate questions' не показувалась коли заповнена одна клітинка чи по діагоналі.
Але можливо треба зробити, щоб одна клітинка рахувалась за слово.

2022-10-20 16:34 UTC, danmysak requested changes
Одна клітинка має рахуватися за слово. По-перше, це логічно (чому дві клітинки — це слово, а одна — ні?..). По-друге, якщо повертати `null`, це обманює користувача: натискаючи (недезактивовану) кнопку «розв’язати», він очікує, що кросворд має шанс бути розв’язаним, а ми його принципово не розв’язуємо.

2022-10-22 11:00 UTC, TeksPeks commented
Зробив, щоб одна клітинка вважалась за слово, але це потрібно було зробити і на фронтенді і на бекенді. І там і там зараз напрям цього слова рахується як `across`, але я не вказував це явно, можливо якщо ці алгоритми будуть змінюватись, буде конфлікт між фронтендом і бекендом.
Тому напевно треба змінити взаємодію з бекендом, щоб питання генерувались тільки на фронтенді, тоді не буде можливості такої помилки. Або треба вказати явно в якому напрямі повинне бути таке слово і на фронтенді і на бекенді?

2022-10-22 12:13 UTC, danmysak requested changes
За логікою слово з однієї клітинки має рахуватися як по горизонталі, так і по вертикалі (причому якщо алгоритми включають елемент випадковості при виборі визначення, то питання по горизонталі та вертикалі до цього слова навіть можуть бути різними). Наскільки я пам’ятаю, щонайменше на фронтенді алгоритм саме так і має працювати. Якщо ні, то варто розібратися чому і виправити.

2022-10-22 16:36 UTC, TeksPeks commented
Тепер слова з однієї клітинки створюються в обох напрямках

2022-10-22 17:12 UTC, danmysak requested changes

2022-10-22 17:12 UTC, danmysak commented on backend/backtracking.py
> +        answers = []
Варто повернути, як було.

2022-10-22 17:12 UTC, danmysak commented on backend/generate.py
> +
Скоротити.

2022-10-22 17:12 UTC, danmysak commented on frontend/src/store/helpers.ts
> +    grid[row][column + 1] === null;
Виправити і скоротити.

2022-10-24 10:13 UTC, danmysak requested changes

2022-10-24 10:13 UTC, danmysak commented on backend/generate.py
> +                       for shift in shifts)
1) Здається, ти відповідаєш на питання «чи є хоча б одна порожня комірка», а не чи «всі комірки навколо порожні».
2) `shifts` нема потреби виносити у проміжну змінну.
3) `shift` варто відразу деструктуризувати на горизонтальну та вертикальну складові.
4) Навколо плюсів мають бути пробіли.
5) У тебе ж є функція `is_filled_cell`. Чому не скористатися відразу нею?

2022-10-24 10:13 UTC, danmysak commented on backend/helpers.py
> +    return position.row in range(len(table)) and position.column in range(len(table[0]))
Неефективні перевірки: потребують `O(лінійний розмір таблиці)` часу, хоча можна було б за `O(1)`.

2022-10-24 10:13 UTC, danmysak commented on backend/solve.py
>             and table[position.row][position.column]
1) Краще назвати функцію `is_cell_filled`.
2) Помітив, що вона не завжди повертає `bool`...

2022-10-24 10:13 UTC, danmysak commented on frontend/src/store/helpers.ts
> +      cellColumn < grid[0].length;
Є сенс винести цю функцію на рівень вище: вона не перестворюватиметься щоразу плюс може виявитися корисною ще для когось.

2022-10-24 10:13 UTC, danmysak commented on frontend/src/store/helpers.ts
> +    ];
Нема сенсу у проміжній змінній.

2022-10-24 10:13 UTC, danmysak commented on frontend/src/store/helpers.ts
> +    );
1) Логіка так само помилкова.
2) Варто відразу деструктуризувати.

2022-10-24 10:57 UTC, danmysak requested changes

2022-10-24 10:57 UTC, danmysak commented on backend/generate.py
> +            return all(not is_filled_cell(Position(position.row+row_shift, position.column+column_shift), table)
Потрібні пробіли навколо плюсів.

2022-10-24 10:57 UTC, danmysak commented on backend/helpers.py
> +    return 0 <= position.row < len(table) and 0 <= position.column < len(table)
Друге порівняння неправильне.

2022-10-24 10:57 UTC, danmysak commented on backend/helpers.py
> +    return cell_exists(position, table) and table[position.row][position.column] == 1
`is_cell_filled`

2022-10-24 11:03 UTC, danmysak approved these changes

2022-10-26 06:27 UTC, Fybex approved these changes

2022-10-26 07:45 UTC, merged