Entering questions + Questions entered
ua-dev-front/crossword-master pull request #108
Opened 2022-10-22 16:57 UTC by Fybex

Fixes #102

2022-10-22 17:51 UTC, danmysak requested changes

2022-10-22 17:51 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +    useAppSelector((state) => state);
Чи не можна спростити?

2022-10-22 17:51 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +  const isQuestionsEntered = useMemo(() => {
`is` → `are`

2022-10-22 17:51 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +      ({ question }) => !!question,
`.trim()`

2022-10-22 17:51 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +      default:
1) `TODO`
2) Замість `default` виписати всі нерозглянуті випадки.

2022-10-22 17:51 UTC, danmysak commented on frontend/src/components/TransitionContainer/index.tsx
> +              center && 'transition-container__item_center',
`centered`

2022-10-22 17:51 UTC, danmysak commented on frontend/src/components/TransitionContainer/styles.scss
> +        transition: all var(--transition-duration) var(--transition-function);
Обмежити.

2022-10-22 17:51 UTC, danmysak commented on frontend/src/components/QuestionPanel/index.tsx
> +  onChange?: (value: string, id: number) => void;
Усе ж таки повернемо.

2022-10-22 17:51 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +                          direction.charAt(0).toUpperCase() + direction.slice(1)
Не користуватися технічною назвою варіантів `enum`’а.

2022-10-22 17:51 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +                  ].map(({ direction, color }) => (
Якщо на напрямку немає питань, то його не відображаємо, а інший напрямок відображаємо посередині.

2022-10-23 18:24 UTC, Fybex commented on frontend/src/components/App/index.tsx
> +    useAppSelector((state) => state);
Не думаю

2022-10-23 18:45 UTC, Fybex commented
Також в процесі виправлення змін знайшов таку проблему.

https://user-images.githubusercontent.com/46112160/197409937-3f049da0-2897-4502-9b86-5eebf22ba174.mp4

Не знаю як його виправити.

2022-10-24 11:41 UTC, danmysak requested changes

2022-10-24 11:41 UTC, danmysak commented on frontend/src/components/App/styles.scss
> +            &:has(&__item:only-of-type) {
На жаль, `has` підтримується [не всіма браузерами](https://caniuse.com/css-has), зокрема його не сприйме файрфокс.

Може, спрацює просто `margin: auto` на дочірньому елементі?

2022-10-24 11:41 UTC, danmysak commented on frontend/src/components/Tabs/index.tsx
> +              hide: !tab || !!tab.hide,
Виходить, при зникненні `tab` анімації не буде?

2022-10-24 11:41 UTC, danmysak commented on frontend/src/components/Tabs/index.tsx
> +              content: <div />,
Додай коментар, що це filler абощо.

2022-10-24 11:41 UTC, danmysak commented on frontend/src/components/Tabs/styles.scss
> +    min-height: 27px;
Чому довелося це додати?

2022-10-24 11:41 UTC, danmysak commented on frontend/src/components/TransitionContainer/index.tsx
> +}: Props) {
А які саме задачі зараз вирішує цей компонент? Яка поведінка від нього очікується ззовні? Непогано було б уточнити в коментарі, бо з коду зрозуміти нетривіально.

2022-10-24 11:41 UTC, danmysak commented on frontend/src/components/TransitionContainer/index.tsx
> +      (item, index) => item.hide && item.hide !== items[index].hide,
Не бачу чогось, що забороняло б, наприклад, `rawItems` мати відмінну від `items` кількість елементів…

2022-10-24 13:27 UTC, Fybex commented on frontend/src/components/Tabs/index.tsx
> +              hide: !tab || !!tab.hide,
Чому? Вона ж є при натисканні `Enter questions & solve`, `Drawing`, `Erase` таби зникають

2022-10-24 13:40 UTC, Fybex commented on frontend/src/components/TransitionContainer/index.tsx
> +}: Props) {
Описав логіку в `useEffect`

2022-10-24 13:41 UTC, Fybex commented on frontend/src/components/TransitionContainer/index.tsx
> +      (item, index) => item.hide && item.hide !== items[index].hide,
Додав перевірку, але взагалі компонент не планується використовуватися з динамічним `items.length`

2022-10-24 13:48 UTC, Fybex commented
> Також в процесі виправлення змін знайшов таку проблему.
> 
>  many_questions_on_switch_bug.mp4 
> Не знаю як його виправити.

Виправив

2022-10-24 14:17 UTC, danmysak commented on frontend/src/components/Tabs/styles.scss
> +    min-height: 27px;
З’являється неявна залежність: якщо, наприклад, надумаємо збільшити шрифт у табах, при їх зникненні висота буде зменшуватися.

2022-10-24 14:24 UTC, danmysak requested changes

2022-10-24 14:24 UTC, danmysak commented on frontend/src/components/App/styles.scss
>              justify-content: space-between;
Зараз відстань між панелями ~удвічі менша, ніж у дизайні.

2022-10-24 17:20 UTC, danmysak requested changes

2022-10-24 17:20 UTC, danmysak commented on frontend/src/components/TransitionContainer/index.tsx
> +    hide: boolean;
`hide` можна прибрати.

2022-10-24 17:20 UTC, danmysak commented on frontend/src/components/TransitionContainer/index.tsx
> +}: Props) {
Усе ж таки потрібен коментар до компонента та/або до пропсів. Коментарі до `useEffect` необов’язкові.

2022-10-24 17:20 UTC, danmysak commented on frontend/src/components/TransitionContainer/index.tsx
> +  }[];
Домовилися ідентифікувати компоненти не по місцю в масиві, а по (кастомному пропу) `key`.

2022-10-24 17:20 UTC, danmysak commented on frontend/src/components/TransitionContainer/index.tsx
> +  };
Використати [`onTransitionEnd`](https://developer.mozilla.org/en-US/docs/Web/API/Element/transitionend_event).

2022-10-26 07:28 UTC, danmysak requested changes

2022-10-26 07:28 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +            key: 'option-label',
Чи справді тут і нижче потрібен префікс `option-`?

2022-10-26 07:28 UTC, danmysak commented on frontend/src/components/Tabs/index.tsx
> +                  isSelected={(tab && tab === selectedTab) || index === 1}
Це виглядає доволі дивно. Я б залишив просто `index === 1` і додав коментар до рядка 36, де би вказав на цю неявну залежність (як її уникнути зовсім, не знаю).

2022-10-26 07:28 UTC, danmysak commented on frontend/src/components/Tabs/index.tsx
> +                  icon={tab?.icon || <Square isFilled={false} />}
Можливо, `false` тоді варто зробити типовим значенням для `isFilled` (це має сенс і щоб тут його не вказувати і не спричиняти питання «чому саме False?», і для самого `Square`, оскільки `isFilled === true` не дуже в’яжеться з непорожнім `content`).

2022-10-26 07:28 UTC, danmysak commented on frontend/src/components/TransitionContainer/index.tsx
> +      }),
Мені цей момент досі не дуже зрозумілий. Чому, коли компонент зникає (набуває `hide: true`), ми мусимо залишати старий вміст, а не задовольнятися поточним? Наведи приклад, коли поточний вміст відрізнятиметься від старого, але відображати під час анімації ми мусимо саме старий.

2022-10-26 07:28 UTC, danmysak commented on frontend/src/components/TransitionContainer/index.tsx
> +                      ) as Props['items'][number])
Але ж це, здається, не зовсім так, якщо компонент повністю зникає з `rawItems`?

2022-10-26 07:28 UTC, danmysak commented on frontend/src/components/TransitionContainer/index.tsx
> +            if (event.propertyName === 'opacity') {
Навіщо потрібна ця перевірка?

2022-10-28 10:08 UTC, Fybex commented on frontend/src/components/TransitionContainer/index.tsx
> +                      ) as Props['items'][number])
Але компонент не може зникнути з `rawItems`, `Props['items][number]` не може містити `undefined` 👍

2022-10-28 10:09 UTC, Fybex commented on frontend/src/components/TransitionContainer/index.tsx
> +                      ) as Props['items'][number])
До речі, тоді виходить, що й нові елементи додаватися в `rawItems` не можуть, тому `key` не потрібен

2022-10-28 10:39 UTC, Fybex commented on frontend/src/components/TransitionContainer/index.tsx
> +      }),
На конференції обговорили приклади в потрібності саме такого підходу, додав коментар до компонента, який пояснює основну роль та нюанси компонента.

2022-10-28 10:41 UTC, Fybex commented on frontend/src/components/TransitionContainer/index.tsx
> +            if (event.propertyName === 'opacity') {
Прибрав цю перевірку та `items[number].className`

2022-10-28 10:51 UTC, danmysak commented on frontend/src/components/TransitionContainer/index.tsx
> +                      ) as Props['items'][number])
Не дуже розумію, про що йдеться: ти ж сам під свою відповідальність задаєш тип оператором `as`.

2022-10-28 10:59 UTC, danmysak requested changes

2022-10-28 10:59 UTC, danmysak commented on frontend/src/icons/Square/index.tsx
> +};
Здається, простіше і наочніше дописати ` = false` у 10-му рядку.

2022-10-28 11:01 UTC, Fybex commented on frontend/src/icons/Square/index.tsx
> +};
І правда, але так не працює 👍 
<img width="862" alt="image" src="https://user-images.githubusercontent.com/46112160/198572078-0e2941c8-94ac-4fff-bc0d-e9b6f1d3cf62.png">
<img width="880" alt="image" src="https://user-images.githubusercontent.com/46112160/198572131-d9cd64a6-48d1-4a42-bea6-41459723dabb.png">

2022-10-28 11:02 UTC, Fybex commented on frontend/src/components/TransitionContainer/index.tsx
> +                      ) as Props['items'][number])
Тому що `ts` думає, що з `rawItems.find` може повернути `undefined`, але це неможливо по вище вказаним причинам

2022-10-28 11:03 UTC, danmysak commented on frontend/src/icons/Square/index.tsx
> +};
Шкода :-)

2022-10-28 11:04 UTC, danmysak commented on frontend/src/components/TransitionContainer/index.tsx
> +                      ) as Props['items'][number])
Тоді я не розумію, на які саме причини ти посилаєшся.

2022-10-28 11:36 UTC, Fybex commented on frontend/src/components/TransitionContainer/index.tsx
> +                      ) as Props['items'][number])
Виправив

2022-10-28 12:22 UTC, danmysak requested changes

2022-10-28 12:22 UTC, danmysak commented on frontend/src/components/TransitionContainer/index.tsx
> +      rawItems.map((item) => {
Це, схоже, неправильно: при зникненні з `rawItems` елемента у нього не буде можливості зробити це з анімацією (ми ж розраховуємо на те, що елементи в масиві можуть з’являтися й зникати?).

Загалом мати два різних колбеки в `useEffect` та `onTransitionEnd`, кожен з яких не стовідсотково інтуїтивно оновлює стан, — це дуже хиткий підхід. Цілком імовірні баги при якихось нестандартних сценаріях, наприклад якщо користувач швидко перемикається туди-сюди між режимами.

Я би зробив так: написав одну функцію-«консолідатор» між старим станом і новим, агностичну до контексту виклику. Саме її використав би в обох випадках — і взагалі не хвилювався б, якби вона випадково запустилася зайвий раз. Імовірно, знадобиться також якась допоміжна структура даних з інформацією про стан анімацій; `onTransitionEnd` оновлюватиме в ній дані.

2022-10-31 21:52 UTC, Fybex commented on frontend/src/components/TransitionContainer/index.tsx
> +      rawItems.map((item) => {
Сподіваюсь, що правильно зрозумів та реалізував ідею з вашого коментаря 👍. Тепер працює правильно й при динамічному зникненні чи появі в масиві `rawItems`

2022-11-01 06:14 UTC, danmysak requested changes
Так, чудово, реалізація цілком відповідає моєму задуму.

2022-11-01 06:14 UTC, danmysak commented on frontend/src/components/TransitionContainer/index.tsx
>              hide: true,
А якщо до списку додається новий елемент (скажімо, із `hide: false`), як ти очікуєш, що він поводитиметься? І чи збігається це з тим, що відбувається зараз?

2022-11-01 07:53 UTC, Fybex commented on frontend/src/components/App/index.tsx
> +                      hide: !areQuestionsEntered || !!fetchAbortController,
Цей компонент не вкладений в інший, який приховується, умова потрібна

2022-11-01 12:12 UTC, Fybex commented on frontend/src/components/TransitionContainer/index.tsx
>              hide: true,
Всі нові елементи спочатку додаються с `hide: true`, потім же оновлюють `hide` на той, який в `rawItems` на наступному рендері.

Може буде корисно, тестував зі зміною `app__full-size-wrapper` `TransitionContainer` `items` на такі:
```
...(isDrawOrEraseMode && !fetchAbortController && isGridEmpty
            ? [
                {
                  key: 'label',
                  content: (
                    <Label
                      content='Let’s draw some squares first!'
                      size={LabelSize.Large}
                    />
                  ),
                  hide: false,
                  center: true,
                },
              ]
            : []),
          ...(isDrawOrEraseMode && !fetchAbortController && !isGridEmpty
            ? [
                {
                  key: 'buttons',
                  content: (
                    <div className='app__option-buttons'>
                      <Button
                        label='Generate questions'
                        onClick={() => dispatch(generateQuestions())}
                      />
                      <Button
                        label='Enter questions & solve'
                        onClick={() => dispatch(switchToEnteringQuestions())}
                      />
                    </div>
                  ),
                  hide: false,
                },
              ]
            : []),
```

https://user-images.githubusercontent.com/46112160/199229643-1346fc10-a51a-49df-a68e-1d6e432b5b6b.mp4

2022-11-01 12:59 UTC, danmysak commented on frontend/src/components/TransitionContainer/index.tsx
>              hide: true,
А хто цей наступний рендер має затригерити?

2022-11-03 09:43 UTC, Fybex commented on frontend/src/components/TransitionContainer/index.tsx
>              hide: true,
Змінив код, тепер елемент завжди появляється з його поточним станом `hide`, раніше анімація в таких випадках на рахунок побічного ефекту, тепер всі нові елементи мають анімацію завдяки доданому до `TransitionContainerItem` коду

2022-11-03 11:40 UTC, danmysak requested changes

2022-11-03 11:40 UTC, danmysak commented on frontend/src/components/TransitionContainer/index.tsx
> +        }
Здається, логічніше буде з `else`.

2022-11-03 11:40 UTC, danmysak commented on frontend/src/components/TransitionContainer/index.tsx
> +            }))
Тут можливий memory leak: старі ключі ніколи не зникають з пам’яті.

2022-11-03 11:40 UTC, danmysak commented on frontend/src/components/TransitionContainer/index.tsx
> +      const changedItems = rawItems.map((rawItem) => {
Не дуже вдала назва. Краще `presentItems` абощо.

2022-11-03 11:40 UTC, danmysak commented on frontend/src/components/TransitionContainer/TransitionContainerItem.tsx
> +  );
1) Чому просто не навісив на елемент без допомоги хука?
2) Мабуть, варто перевіряти, чи це подія на самому елементі (а не прийшла від дочірнього).

2022-11-03 11:40 UTC, danmysak commented on frontend/src/components/TransitionContainer/index.tsx
> +          (itemsTransitionState[rawItem.key] || (!oldItem.hide && rawItem.hide))
Уявімо сценарій: попередній вміст компонента зникав унаслідок виставлення йому hide = true. Під час цього переходу вміст компонента змінився, а hide стало false. Тоді, виходить, ти починаєш плавно назад показувати старий вміст, а після появи моментально змінюєш його на новий?

2022-11-03 17:52 UTC, Fybex commented on frontend/src/components/TransitionContainer/TransitionContainerItem.tsx
> +  );
1. `transitionStart` не підтримується реактом

2022-11-03 17:58 UTC, Fybex commented on frontend/src/components/TransitionContainer/TransitionContainerItem.tsx
> +  );
2. 👍

2022-11-03 18:08 UTC, danmysak requested changes

2022-11-03 18:08 UTC, danmysak commented on frontend/src/components/TransitionContainer/TransitionContainerItem.tsx
> +    if (ref.current && ref.current === event.target) {
`event.target === ref.current`

2022-11-03 18:26 UTC, danmysak requested changes

2022-11-03 18:26 UTC, danmysak commented on frontend/src/components/TransitionContainer/index.tsx
> +          (itemsTransitionState[rawItem.key] || (!oldItem.hide && rawItem.hide))
Додай коментар з приводу умов: вони, на жаль, не очевидні.

2022-11-03 18:28 UTC, danmysak requested changes

2022-11-03 18:28 UTC, danmysak commented on frontend/src/components/TransitionContainer/TransitionContainerItem.tsx
> +  hide: boolean;
`display`

2022-11-05 17:36 UTC, Fybex commented on frontend/src/components/TransitionContainer/index.tsx
> +          (itemsTransitionState[rawItem.key] || (!oldItem.hide && rawItem.hide))
Додав коментар тут та нижче до умови `deletedItems` також, щоб було максимально зрозуміло все в цьому `useEffect`

2022-11-05 17:49 UTC, danmysak requested changes

2022-11-05 17:49 UTC, danmysak commented on frontend/src/components/TransitionContainer/index.tsx
> +                    : prevState[item.key] || false,
1) Семантичніше — `??`.
2) А якщо елемента з `key` ще немає в `items`?

2022-11-05 17:57 UTC, Fybex commented on frontend/src/components/TransitionContainer/index.tsx
> +                    : prevState[item.key] || false,
1. 👍 
2. неможливо, `onTransitionStateChange` всередині `items.map`

2022-11-05 18:03 UTC, danmysak approved these changes

2022-11-06 20:27 UTC, TeksPeks approved these changes

2022-11-06 22:09 UTC, merged