Puzzle answer view
ua-dev-front/crossword-master pull request #109
Opened 2022-10-24 16:03 UTC by TeksPeks

Fixes #103
Ще не остаточна версія, панелі питань зроблю після #108, плюс треба буде пофіксити конфлікти з тим же ПРом

2022-10-24 16:18 UTC, danmysak requested changes

2022-10-24 16:18 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +          content={currentMode === Mode.Answer ? 'A' : undefined}
А точно це `A` відобразиться правильним шрифтом?

2022-10-28 15:11 UTC, TeksPeks commented on frontend/src/components/App/index.tsx
> +          content={currentMode === Mode.Answer ? 'A' : undefined}
так

2022-10-28 15:13 UTC, TeksPeks commented
Замерджив #108 сюди

2022-10-28 16:03 UTC, danmysak requested changes

2022-10-28 16:03 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +            hide: mode !== Mode.EnterQuestions && !isAnswerOrPuzzleMode,
Здається, ми домовилися про таке:
1) змінити структуру стану;
2) для розв’язаного кросворда не показувати перемикачі Puzzle/Answer (є сенс лише у режимі відповідей);
3) для розв’язаного кросворда (як і під час самого розв’язування) показувати кнопку Replace questions.

2022-10-28 16:11 UTC, TeksPeks commented on frontend/src/components/App/index.tsx
> +            hide: mode !== Mode.EnterQuestions && !isAnswerOrPuzzleMode,
це я збирався зробити в інщому пулл реквесті

2022-10-28 16:35 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +            hide: mode !== Mode.EnterQuestions && !isAnswerOrPuzzleMode,
А, ні, справді, краще в іншому. Мене заплутала назва «Puzzle answer view», яка фактично є перекладом задачі «Відображення розв’язаного кросворда», хоча насправді розв’язує іншу задачу на реалізацію Question view.

Але все ж є ще одне загальне зауваження. Порівняй, як працює перемикання режимів Draw/Erase, із тим, як працює Puzzle/Answer. Зараз бракує стабільності розташування перемикача справа та анімацій переходу для обох табів. Анімацій піктограм немає також при поверненні до режиму редагування. Також у зв’язку з цим переходом треба, щоб розташування перемикача справа було однаковим і для Home view, і для Question view.

2022-11-01 17:51 UTC, danmysak requested changes

2022-11-01 17:51 UTC, danmysak commented on frontend/src/icons/Square/index.tsx
> +import TransitionContainer from 'components/TransitionContainer';
Виправ порядок імпортів.

2022-11-01 17:51 UTC, danmysak commented on frontend/src/components/Tab/index.tsx
> +            key={`alternative-label-${index}`}
Достатньо `key={index}`.

2022-11-01 17:51 UTC, danmysak commented on frontend/src/components/App/index.tsx
>        />
Зараз при спробі генерації такого кросворда в консоль зрештою падає помилка:

<img width="413" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/6333637/199301717-c0a5c7bf-be98-422b-83bd-3714aea1ac14.png">

<img width="887" alt="image" src="https://user-images.githubusercontent.com/6333637/199301808-cea043cd-cb0b-4e55-8c8e-4fdb6546f4d1.png">

2022-11-01 17:51 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +          })}
Спробуй уніфікувати з рядками 173—182.

2022-11-01 17:53 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +            hide: mode !== Mode.EnterQuestions && !isAnswerOrPuzzleMode,
Усе виправив, спасибі. В мене буде ще серія дрібніших зауважень стосовно розташування табів, але це вже, мабуть, у наступному PR.

2022-11-03 00:00 UTC, danmysak approved these changes

2022-11-07 12:15 UTC, Fybex approved these changes

2022-11-07 17:58 UTC, merged