Solved view
ua-dev-front/crossword-master pull request #111
Opened 2022-11-01 09:25 UTC by TeksPeks

Fixes #105

2022-11-01 10:55 UTC, danmysak requested changes

2022-11-01 10:55 UTC, danmysak commented on frontend/src/store/index.ts
> +  requestFailed: boolean;
Онови опис стану у https://github.com/ua-dev-front/crossword-master/issues/46.

2022-11-01 10:55 UTC, danmysak commented on frontend/src/store/index.ts
> +  requestMode: Mode.Draw | Mode.EnterQuestions | null;
1) Тепер, здається, вже точно є сенс створити окремий енам `RequestMode` і назвати його опції відповідніше до реальності.

2) Це поле лишатиметься незмінним, коли після перегляду розв’язаного або згенерованого кросворда користувач повернеться назад до редагування кросворда або питань. Тому або виправ цю поведінку, щоб `requestMode` скидався в `null` (трохи краще), або перейменуй поле у `lastRequestMode` (трохи гірше).

2022-11-01 10:55 UTC, danmysak commented on frontend/src/components/App/index.tsx
>      }
Тоді краще винести `if (requestFailed)` вище і скористатися тернарним оператором, як у рядках 130—132.

2022-11-01 10:55 UTC, danmysak commented on frontend/src/components/App/index.tsx
>              selectedTab: getTabByModeAndIsSelected(mode, true),
Цей таб насправді теж не потрібен (задум такий, що він є частиною перемикача, а перемикати в цьому випадку нічого).

2022-11-01 10:55 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +                        !fetchAbortController && mode === Mode.EnterQuestions,
Мені здається, варто відштовхуватися від випадку, коли кнопку є сенс показувати, а не від тих випадків, коли її не слід показувати — бо в майбутньому кількість таких випадків може рости, і не факт, що під час появи якогось нового випадку не забудуть оновити цей рядок.

2022-11-03 10:50 UTC, danmysak requested changes

2022-11-03 10:50 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +  RequestMode,
Перенеси вище до `Mode`.

2022-11-03 10:52 UTC, danmysak commented on frontend/src/store/index.ts
> +  requestFailed: boolean;
Також внеси туди зміну з `RequestMode`.

2022-11-05 08:03 UTC, danmysak commented on frontend/src/store/index.ts
> +  requestFailed: boolean;
Але розпиши RequestMode за аналогією до Mode, щоб було наочно.

2022-11-05 09:13 UTC, danmysak approved these changes

2022-11-07 19:58 UTC, Fybex approved these changes

2022-11-08 20:53 UTC, merged