Align tabs with the grid
ua-dev-front/crossword-master pull request #119
Opened 2022-11-08 21:17 UTC by TeksPeks

Fixes #113 
Прибрав у табів лівий і правий padding. Не знаю що ще можна зробити, щоб їх вирівняти?

2022-11-09 07:42 UTC, danmysak requested changes

2022-11-09 07:42 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
> +  padding: 2px 0;
1) Так не можна, бо тоді кнопка погано виглядає при табуляції.
2) Справді, цього візуально недостатньо. Давай спробуємо перемістити піктограму правого таба праворуч від його тексту і глянемо, як це виглядає.

Але ці два пункти реалізуй окремими комітами, будь ласка.

2022-11-09 17:38 UTC, danmysak requested changes

2022-11-09 17:38 UTC, danmysak commented on frontend/src/components/Tab/index.tsx
> +export enum TabIconAlign {
`Align` → `Alignment`

2022-11-09 17:38 UTC, danmysak commented on frontend/src/components/Tab/index.tsx
> +  alignIcon: TabIconAlign;
`alignIcon` → `iconAlignment`

2022-11-09 17:38 UTC, danmysak commented on frontend/src/components/Tab/index.tsx
> +    alignIcon === TabIconAlign.Right && 'tab_reverse-direction',
Якщо пропс «симетричний» щодо розташування, то хай таким буде і клас — точніше два класи.

2022-11-09 17:38 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
> +      justify-self: end;
А точно потрібні обидва правила?

2022-11-09 17:38 UTC, danmysak commented on frontend/src/components/Tabs/index.tsx
> +        secondaryTab, // isSelected and alignIcon props of the Tab component below depend on the order of tabs in the array
А може, просто вбудуємо ці дані в елементи масиву?
```
{
  tab: selectedTab,
  isSelected: true,
  iconAlignment: Left,
}
```
чи якось так.

2022-11-09 17:38 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
> +  padding: 2px 3px;
Ну але ж проблему із зсувом ми в підсумку так і не вирішили...

2022-11-11 15:48 UTC, TeksPeks commented on frontend/src/components/Tab/styles.scss
> +      justify-self: end;
Перше ставить іконку справа від лейбла, а друге притискає лейбел вправо до іконки

2022-11-11 15:49 UTC, TeksPeks commented on frontend/src/components/Tabs/index.tsx
> +        secondaryTab, // isSelected and alignIcon props of the Tab component below depend on the order of tabs in the array
`iconAlignment` додав у `TabProps` а `isSelected` у сам масив

2022-11-11 15:50 UTC, TeksPeks commented on frontend/src/components/Tab/styles.scss
> +  padding: 2px 3px;
Додав `margin-left(right): -3px` для крайніх табів

2022-11-11 16:12 UTC, danmysak requested changes

2022-11-11 16:12 UTC, danmysak commented on frontend/src/components/Tabs/index.tsx
> +                  iconAlignment={tab?.iconAlignment ?? TabIconAlignment.Left}
А чому б `iconAlignment` не винести так само, як `isSelected`?

2022-11-13 12:43 UTC, Fybex requested changes

2022-11-13 12:43 UTC, Fybex commented on frontend/src/components/Tabs/index.tsx
> +                  iconAlignment={iconAlignment ?? TabIconAlignment.Left}
А так не можно? У нас же в `Tab` `TabIconAlignment.Left` - default value
```suggestion
                  iconAlignment={iconAlignment}
```

2022-11-13 12:44 UTC, Fybex commented on frontend/src/components/Tab/index.tsx
> +  alignIcon: TabIconAlignment.Left,
🤔 
```suggestion
  iconAlignment: TabIconAlignment.Left,
```

2022-11-13 12:48 UTC, Fybex approved these changes

2022-11-13 13:42 UTC, danmysak requested changes

2022-11-13 13:42 UTC, danmysak commented on frontend/src/components/Tab/index.tsx
> +      iconAlignment === TabIconAlignment.Right ? 'right' : 'left'
Просто `iconAlignment`.

2022-11-13 13:42 UTC, danmysak commented on frontend/src/components/Tabs/index.tsx
> +        { tab: secondaryTab, iconAlignment: TabIconAlignment.Right },
Але ж прибери з TabProps.

2022-11-13 13:42 UTC, danmysak commented on frontend/src/components/Tabs/styles.scss
> +        margin: 0 var(--tab-horizontal-margin);
На мій погляд, цей аспект поведінки таба слід зробити «приватним» для компонента Tab — щоб Tabs чи інші батьківські компоненти цим не морочилися. З погляду батьківського компонента Tab не має виходити за межі напису. Але візуально при табуляції буде.

2022-11-13 17:28 UTC, danmysak requested changes

2022-11-13 17:28 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
> +  --tab-horizontal-margin: -3px;
Зміст цієї змінної — консолідувати `margin` і `padding`, щоб вони завжди врівноважували один одного.

2022-11-16 05:40 UTC, danmysak approved these changes

2022-11-17 14:09 UTC, merged