Confirmation `Dialog`
ua-dev-front/crossword-master pull request #120
Opened 2022-11-09 17:03 UTC by Fybex

Fixes #114

2022-11-09 17:58 UTC, danmysak requested changes

2022-11-09 17:58 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +    showConfirmationState,
Можна це поле назвати так саме тут, а в стані залишити `showConfirmation`.

2022-11-09 17:58 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +                label={'Questions & answers will be lost.\nContinue?'}
Фрагменту `& answers` має сенс з’являтися лише тоді, коли відповіді вже визначено.

2022-11-10 22:39 UTC, Fybex commented on frontend/src/components/App/index.tsx
> +  const isGridContainsAnswers = useMemo(() => {
замінив `isGridContainsAnswers` на `requestMode && !requestFailed`

2022-11-11 01:47 UTC, danmysak requested changes

2022-11-11 01:47 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +                  requestMode && !requestFailed ? ' & answers' : ''
Не дуже розумію: хіба ця умова не справджуватиметься під час розв’язування кросворда сервером?

2022-11-11 15:10 UTC, Fybex commented on frontend/src/components/App/index.tsx
> +                  requestMode && !requestFailed ? ' & answers' : ''
виправив

2022-11-11 15:16 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +                  requestMode && !requestFailed ? ' & answers' : ''
А навіщо лишається `requestMode`?

2022-11-11 15:20 UTC, Fybex commented on frontend/src/components/App/index.tsx
> +                  requestMode && !requestFailed ? ' & answers' : ''
ну якщо `requestMode === null`, то ми не виконували ще запитів, тобто у нас немає відповідей.

Приклад: в момент заповнення питань при натисканні `Edit` `requestMode === null`, тому ми не показуємо ` & answers`

2022-11-11 15:26 UTC, danmysak approved these changes

2022-11-16 08:03 UTC, merged