Ban repeating words
ua-dev-front/crossword-master pull request #126
Opened 2022-11-13 12:23 UTC by Fybex

Fixes #124

2022-11-13 13:17 UTC, danmysak requested changes

2022-11-13 13:17 UTC, danmysak commented on backend/backtracking.py
> +        else loaded_options
1) Поки що це неправильно: у змінній answers зберігаються не поточні підібрані відповіді, а щось випадкове (справжні відповіді зберігаються в таблиці). Перепиши функцію краще — щоб такої невідповідності не було.
2) Перевірку можна робити відразу в циклі нижче.
3) Для чого умова word_length > 1? Оформ так, щоб цього питання не виникало.

2022-11-19 10:48 UTC, Fybex commented on backend/backtracking.py
> +        else loaded_options
1. Виправив
2. 👍 
3. Прибрав умову (#128)

2022-11-19 11:37 UTC, danmysak requested changes

2022-11-19 11:37 UTC, danmysak commented on backend/backtracking.py
> +        return None
Навіть якщо відповіді є, це не значить, що якась із них підійде. Тому `None` потрібно повернути вже після виходу з циклу.

2022-11-19 11:37 UTC, danmysak commented on backend/backtracking.py
> +              current_index: int = 0, answers: list[str] | None = None) -> list[str] | None:
Параметр `current_index` тепер зайвий: він дублює розмір `answers`.

2022-11-19 11:37 UTC, danmysak commented on backend/backtracking.py
>              return answers
Уже лишимо, як є, але хочу звернути увагу, що такий підхід дещо вразливий до помилок у майбутньому: якщо з’явиться альтернативний виклик `backtrack` у якому-небудь іншому місці функції, інваріант, що `answers` після знаходження відповіді не мутується, може зламатися.

2022-11-19 11:37 UTC, danmysak commented on backend/backtracking.py
> +            answers.pop()
Між іншим, а чи не потрібно зробити аналогічної зворотної дії і з таблицею?

2022-11-19 17:35 UTC, Fybex commented on backend/backtracking.py
> +        return None
але ж функція і так поверне `None`

2022-11-19 17:47 UTC, danmysak commented on backend/backtracking.py
> +        return None
Так, для семантики. Ну і в будь-якому випадку тут повертати `None` не має сенсу.

2022-11-19 17:48 UTC, Fybex commented on backend/backtracking.py
> +            answers.pop()
> Між іншим, а чи не потрібно зробити аналогічної зворотної дії і з таблицею?

Це не обов'язково та додає додаткової роботи, але щоб не повторити ситуацію, яка була з `answers` додав зворотну дію для таблиці

2022-11-19 18:22 UTC, danmysak approved these changes

2022-11-20 12:15 UTC, TeksPeks approved these changes

2022-11-20 12:48 UTC, merged