Normalize generated questions
ua-dev-front/crossword-master pull request #127
Opened 2022-11-13 12:29 UTC by TeksPeks

Fixes #123

2022-11-13 13:25 UTC, danmysak requested changes

2022-11-13 13:25 UTC, danmysak commented on backend/generate.py
> +    return question.capitalize() + ('.' if question[-1] != '.' else '')
1) Семантичніше і менш вразливо до помилок (якщо раптом трапиться порожній рядок) буде `.endswith`.
2) Щоб не дублювати крапку, винеси її у константу. Називаючи константу, май на думці, наприклад, сценарій локалізації сайту іншою мовою, де речення закінчуються іншим розділовим знаком.

2022-11-16 05:59 UTC, danmysak requested changes

2022-11-16 05:59 UTC, danmysak commented on backend/api.py
> +        return question[0].isalnum()
1) Для поставленої задачі точніше буде `.isalpha()`.
2) Краще `[:1]`, щоб не вилітати на порожньому рядку.

2022-11-16 05:59 UTC, danmysak commented on backend/api.py
> +                      api_request(generate_path))
Уникни дублювання `item['defs'][0]` тут і нижче. Зокрема, чому б не брати ненульове питання, якщо нульове не підходить, але підходить якесь інше?

2022-11-16 06:00 UTC, danmysak commented on backend/generate.py
> +    return question.capitalize() + ('.' if question[-1] != '.' else '')
Врахуй останнє зауваження:

> Називаючи константу, май на думці, наприклад, сценарій локалізації сайту іншою мовою, де речення закінчуються іншим розділовим знаком.

2022-11-17 14:19 UTC, danmysak requested changes

2022-11-17 14:19 UTC, danmysak commented on backend/api.py
> +        return list(filter(is_valid_question, questions))
Це неправильно: якщо `questions` — `None`, то випаде помилка.

2022-11-17 14:19 UTC, danmysak commented on backend/api.py
> +    return {item['word']: normalize_question(filter_questions(item['defs'])[0]) for item in response}
Дублювання (у вигляді виклику `filter_questions` та припущення, що результат цього виклику непорожній) лишилося.

2022-11-17 16:20 UTC, TeksPeks commented on backend/api.py
> +        return list(filter(is_valid_question, questions))
`questions` не повинно бути `None`, не знаю чому в типах він був

2022-11-20 14:04 UTC, TeksPeks commented on backend/api.py
> +    return {item['word']: normalize_question(filter_questions(item['defs'])[0]) for item in response}
виправив

2022-11-20 16:13 UTC, danmysak approved these changes

2022-11-20 19:53 UTC, Fybex approved these changes

2022-11-21 15:41 UTC, merged