Frontend components templates
ua-dev-front/crossword-master pull request #13
Opened 2022-06-29 20:06 UTC by Fybex

Fixes #12

2022-06-30 10:48 UTC, danmysak requested changes

2022-06-30 10:48 UTC, danmysak commented on frontend/src/components/Button/index.tsx
> +  isLoading: boolean;
Для чого саме потрібне це поле?

2022-06-30 10:48 UTC, danmysak commented on frontend/src/components/Cell/index.tsx
> +  onClick: () => void;
Типування ненормалізоване (ми говорили про це на занятті). Плюс комірка не завжди повинна бути редаговною.

2022-06-30 10:48 UTC, danmysak commented on frontend/src/components/Field/index.tsx
> +  onChange: (matrix: Array<Array<number | string>>) => void;
Дрібниці:
1) Мабуть, правильніше назвати не «Field», а «Grid».
2) Використовуймо не `Array<X>`, а `X[]`.
3) Мабуть, оголошення типу `Array<Array<number | string>>` слід винести як спільне?
4) `'draw' | 'erase' | 'answer'` — це poor man’s substitute до енаму.

Але глобально я не дуже розумію твій задум. Наприклад, поле не завжди редаговне. А коли редаговне, то чи справді воно має саме проставляти цифри й літери у відредагованих полях? Здається, це мала б бути не його задача.

Загалом, здається, ти поки що не надто глибоко продумав цей компонент.

2022-07-02 12:11 UTC, TeksPeks approved these changes

2022-07-04 10:25 UTC, danmysak requested changes

2022-07-04 10:25 UTC, danmysak commented on frontend/src/components/Cell/index.tsx
> +  cell:
У цьому контексті поле краще назвати `data`.

2022-07-04 10:25 UTC, danmysak commented on frontend/src/components/Cell/index.tsx
> +  onClick: () => void;
Тоді краще `onEdited: (filled: boolean) => void`: комірка все одно має контролювати свій наведений вигляд, тому має пам’ятати, в якому вона зараз стані. Хай лише вона і пам’ятає.

2022-07-04 10:25 UTC, danmysak commented on frontend/src/types/mode.ts
> +  Answer,
Краще дописати `Draw = 'draw'` і т. д., щоб легше було зневаджувати

2022-07-04 10:25 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +  onChange: (matrix: Matrix) => void;
Ще раз: хіба поле має коли-небудь передавати матрицю з літерами і цифрами у колбек?..

Але загалом давай обдумаємо взаємодію з цим компонентом краще. Для кожного режиму роботи з ним існує конкретний (більш специфічний, ніж зараз) тип даних, які поле приймає, і потреба / відсутність потреби в колбеку.

Спробуй подати це все в пропсах нормалізовано.

2022-07-04 17:09 UTC, danmysak requested changes

2022-07-04 17:09 UTC, danmysak commented on frontend/src/types/mode.ts
> +  Answer = 'answer',
Додати режим `Puzzle`.

2022-07-04 17:09 UTC, danmysak commented on frontend/src/types/matrix.ts
> +};
Врахувати, що порожня комірки != незафарбована комірка.

2022-07-04 17:09 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +        onChange: (matrixItem: MatrixItem, row: number, column: number) => void;
`matrixItem` зайвий.

2022-07-04 17:09 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +  modeData:
Поле `matrix` потрібно специфікувати під кожен окремий режим.

2022-07-04 18:21 UTC, Fybex commented on frontend/src/components/Grid/index.tsx
> +  modeData:
Постарався максимально детально розписати, сподіваюсь зараз краще

2022-07-05 11:37 UTC, danmysak requested changes

2022-07-05 11:37 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +      mode: Mode.Draw | Mode.Erase;
1) Поле `mode` має стояти першим для всіх варіантів (як `editable` у Cell), бо є базою для розрізнення цих варіантів.
2) `boolean` — з маленької літери.

2022-07-05 11:37 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +        | null[][];
У тебе виходить, що або `{ number: ... }`, або масив `null[][]`...

2022-07-05 11:37 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +        | null[][];
Те саме тут.

2022-07-05 19:12 UTC, Fybex commented on frontend/src/components/Cell/index.tsx
> +          | { number: number | null }
Ми можемо мати { letter: string; number: number | null } - коли клітинка заповнена та може мати цифру, а може й не мати, або ми маємо { number: number | null }, це коли ми маємо заповнену клітинку, але без букви, яка може мати цифру, а може й не мати

2022-07-06 17:11 UTC, merged