Sorting api responses by part of speech
ua-dev-front/crossword-master pull request #131
Opened 2022-11-19 11:24 UTC by Fybex

Fixes #125

2022-11-19 11:46 UTC, danmysak requested changes

2022-11-19 11:46 UTC, danmysak commented on backend/api.py
> +        if item.get('tags')
1) `'tags' in item`
2) Форматування дещо заплутує: логічно було б `if` та `else` бачити на рівні з `lambda`, а не `key`. Якщо лінтер не пропускає, спробуй дужки.

2022-11-19 11:46 UTC, danmysak commented on backend/api.py
> +    part_of_speech_order = ['n', 'adj', 'v', 'adv', 'u']
Можна винести в константи нагору файлу.

2022-11-19 11:46 UTC, danmysak commented on backend/api.py
> +def filter_by_part_of_speech(response: list[dict]) -> list[dict]:
`filter` → `sort`

2022-11-19 18:23 UTC, danmysak approved these changes

2022-11-20 12:10 UTC, TeksPeks requested changes

2022-11-20 12:10 UTC, TeksPeks commented on backend/api.py
> +        key=lambda item: PART_OF_SPEECH_ORDER.index(item['tags'][0]) if 'tags' in item else len(part_of_speech_order),
`part_of_speech_order` великими літерами

2022-11-20 19:58 UTC, Fybex commented on backend/api.py
> +        key=lambda item: PART_OF_SPEECH_ORDER.index(item['tags'][0]) if 'tags' in item else len(part_of_speech_order),
🤦

2022-11-21 15:41 UTC, TeksPeks approved these changes

2022-11-24 07:50 UTC, merged