Match the colour of the tab icons to the figma version
ua-dev-front/crossword-master pull request #136
Opened 2022-11-20 20:18 UTC by Fybex

Fixes #133 

Привів всі кольори іконок з `Tab` до варіантів з фігми.

2022-11-21 07:20 UTC, danmysak approved these changes

2022-11-21 07:54 UTC, danmysak requested changes

2022-11-21 07:54 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
Здається, тепер неправильний колір має стрілка від Edit’а (правильний, мабуть, повинен бути такий самий, як у самого напису Edit).

2022-11-24 07:41 UTC, Fybex commented on frontend/src/components/Tab/styles.scss
Змінив колір `LeftArrow` на той, який у фігмі(аналогічний до не заповненого `Square`)

2022-11-24 09:36 UTC, danmysak approved these changes

2022-11-28 21:53 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
Гм... У мене ці кольори різні — навіть візуально:

![image](https://user-images.githubusercontent.com/6333637/204388795-514b6aab-4f84-4358-8d3c-6e47b5223d64.png)

Також — чому тоді фінальний колір (який уже включає прозорість) не винесено у змінну?

2022-11-28 21:54 UTC, danmysak requested changes
Лишився коментар.

2022-12-01 17:56 UTC, Fybex commented on frontend/src/components/Tab/styles.scss
> Гм... У мене ці кольори різні — навіть візуально:
> 
> ![image](https://user-images.githubusercontent.com/6333637/204388795-514b6aab-4f84-4358-8d3c-6e47b5223d64.png)

"ці кольори" це які?

2022-12-01 17:59 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
Ті два, які видно на зображенні (крім фонового білого).

2022-12-01 17:59 UTC, Fybex commented on frontend/src/components/Tab/styles.scss
![image](https://user-images.githubusercontent.com/46112160/205126435-97d9a799-65f9-449c-9673-284647daf74a.png)

в дизайні аналогічно

2022-12-01 19:21 UTC, Fybex commented on frontend/src/components/Tab/styles.scss
Іконку `Square`, яка використовується для табу `Draw`, `Answer`

2022-12-01 19:25 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
Тепер ясно. То чи не має сенсу винести `cl(near-black, 0.67)` у змінну?

2022-12-01 19:26 UTC, Fybex commented on frontend/src/components/Tab/styles.scss
має, можна рекомендацію щодо назви змінної? `--color-${name?}` `transparent-near-black`?

2022-12-01 19:30 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
Можна `near-black-translucent`.

2022-12-01 20:00 UTC, Fybex commented on frontend/src/components/Tab/styles.scss
Проблема в тому, що тоді цей колір буде вибиватися з маси інших кольорів, оскільки в нього буде прозорість, і тоді його треба буде використовувати не як всі інші за допомогою `cl(...)`, а як змінну `var(--color-near-black-translucent)`.

2022-12-01 20:27 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
Гаразд. На цьому етапі не критично.

2022-12-01 20:27 UTC, danmysak approved these changes

2022-12-03 17:33 UTC, TeksPeks approved these changes

2022-12-03 18:00 UTC, merged