Backtracking algorithm
ua-dev-front/crossword-master pull request #14
Opened 2022-07-02 15:01 UTC by TeksPeks

Абстрагував алгоритм бектрекінгу з алгоритму розв'язування питань

2022-07-04 10:59 UTC, danmysak requested changes

2022-07-04 10:59 UTC, danmysak commented on backend/app_types.py
> +Position = list[int]  # length = 2
А взагалі — нарешті усвідомив — давайте розіб’ємо це просто на два цілочисельних поля `row` та `column` (нумерація, наприклад, з нуля). То буде значно природніше.

@Fybex — FYI ^

2022-07-04 10:59 UTC, danmysak commented on backend/app_types.py
> +    down: dict[int, list[str]]
Повторення підтипу.

2022-07-04 10:59 UTC, danmysak commented on backend/backtracking.py
> +
Має бути не два порожніх рядки, а один.

2022-07-04 10:59 UTC, danmysak commented on backend/backtracking.py
> +                    answers: SolveAnswers = None) -> SolveAnswers:
1) Чи завжди функція справді може повернути `SolveAnswers`?
2) Те, що функція приймає на вхід `word_id` та `answers` — деталі реалізації; з погляду користувача цієї функції дані параметри незрозумілі. Відповідно, треба розділити функцію на те, що бачить її користувач, і вже окрему рекурсивну імплементацію.

2022-07-04 10:59 UTC, danmysak commented on backend/backtracking.py
> +    direction = get_direction(words, word_id)
Здається, ти знову не врахував, що слово з одним і тим самим номером може траплятися в кросворді двічі — один раз по горизонталі та один раз по вертикалі.

2022-07-04 10:59 UTC, danmysak commented on backend/backtracking.py
> +    answers[direction].append({'id': word_id, 'answer': answer})
Треба обійтися без мутації даних.

2022-07-04 10:59 UTC, danmysak commented on backend/backtracking.py
> +    return None
Імовірно, для фінальному варіанта коду це не буде релевантним, але загальне зауваження: цю та попередню функцію треба було б сумістити, щоб обійтися без дублікації коду.

2022-07-04 10:59 UTC, danmysak commented on backend/backtracking.py
> +            position = increase_position(position, direction)
А ти тестував цей код?.. Я не бачу, який ефект має таке присвоєння, для того, хто викликав функцію.

2022-07-04 10:59 UTC, danmysak commented on backend/backtracking.py
> +        if is_correct_cell(position, table):
Навіщо потрібна ця перевірка?

2022-07-04 10:59 UTC, danmysak commented on backend/backtracking.py
> +                return answers
У цілому непогано. Але хотілося б, звичайно, врахувати, що при генерації кросворда значно надійніше буде довантажувати підходящі варіанти на ходу. Бо навіть якщо назбирати по 1000 варіантів на кожне слово, але в кросворді буде, скажімо, перетин одного слова по вертикалі з трьома по горизонталі, то матимеш три фіксовані літери, і з великою ймовірністю жодне з 1000 слів не підійде.

Але, щоб такий бектрекінг узагалі допрацював за прийнятний час, доведеться обмежити кількість варіантів значно меншою кількістю...

2022-07-06 06:35 UTC, TeksPeks commented on backend/backtracking.py
> +        if is_correct_cell(position, table):
не потрібна

2022-07-06 06:37 UTC, TeksPeks commented on backend/backtracking.py
> +            position = increase_position(position, direction)
Тестував, працює. Присвоюється наступна позиція яка повертається з функції

2022-07-06 12:35 UTC, danmysak requested changes

2022-07-08 17:57 UTC, danmysak requested changes
Обговорили на занятті.

2022-07-10 17:29 UTC, danmysak requested changes

2022-07-10 17:29 UTC, danmysak commented on backend/app_types.py
>  class Word(TypedDict):
`TypedDict` у цьому файлі лишатися не мають (усі слід перенести у файл з ендпоінтами). Тут — лише датакласи.

2022-07-10 17:29 UTC, danmysak commented on backend/app_types.py
> +from typing import TypedDict, Callable
Абетка.

2022-07-10 17:29 UTC, danmysak commented on backend/backtracking.py
> +from app_types import LoadOptions, Position, PossibleAnswers, Pattern, Table, WordLocation, Direction
Абетка.

2022-07-10 17:29 UTC, danmysak commented on backend/backtracking.py
> +              current_id: int, answers: list[str], loaded_more_answers: list[bool]) -> list[str] | None:
`id` → `index`

2022-07-10 17:29 UTC, danmysak commented on backend/backtracking.py
> +def solve(locations: list[WordLocation], table_size: int, load_options: LoadOptions) -> list[str] | None:
`table_size` зайвий, а `LoadOptions` має виглядати зовсім інакше.

2022-07-11 19:59 UTC, TeksPeks commented on backend/backtracking.py
> +def solve(locations: list[WordLocation], table_size: int, load_options: LoadOptions) -> list[str] | None:
У `LoadOptions`  залишив `Id`, бо в алгоритмі розв'язування треба завантажувати слова які підходять до паттерну і відповідають на задане запитання, і `Id` потрібен для того, щоб отримати запитання.

2022-07-12 17:15 UTC, danmysak requested changes

2022-07-12 17:15 UTC, danmysak commented on backend/app.py
> +    solve_words = SolveWords(parsed_words['across'], parsed_words['down'])
Мало б сенс `SolveWords` одразу зробити максимально придатним до опрацювання на сервері (спільний список усіх слів, а не окремо по горизонталі й вертикалі).

2022-07-12 17:15 UTC, danmysak commented on backend/app_types.py
>  Id = int
Видалити `Id`, бо насправді це індекс, для якого навіть не потрібно еліасу.

2022-07-12 17:15 UTC, danmysak commented on backend/app_types.py
> +Pattern = list[str | None]  # Each element represents either a letter on its respective position or a wildcard(None)
Пробіл перед дужкою.

2022-07-12 17:15 UTC, danmysak commented on backend/app_types.py
> +LoadOptions = Callable[[Pattern, Id], WordOptions]
`Id` → `int` + дописати коментар.

2022-07-12 17:15 UTC, danmysak commented on backend/app_types.py
> +BackTrackTable = list[list[str | None]]
Перенести у файл з бектрекінгом (оскільки це деталь реалізації саме його).

2022-07-12 17:15 UTC, danmysak commented on backend/app_types.py
> +    DOWN = "down"
Одинарні лапки.

2022-07-12 17:15 UTC, danmysak commented on backend/app_types.py
> +ParsedWords = list[ParsedWord]
Усі типи, які не використовуються, видалити.

2022-07-12 17:15 UTC, danmysak commented on backend/backtracking.py
> +            pattern.append(None)
Скористатися тернарним оператором.

2022-07-12 17:15 UTC, danmysak commented on backend/backtracking.py
> +              current_ind: int, answers: list[str], loaded_more_answers: list[bool]) -> list[str] | None:
`current_index`

2022-07-14 20:05 UTC, danmysak approved these changes

2022-07-15 21:26 UTC, Fybex requested changes

2022-07-15 21:26 UTC, Fybex commented on backend/app_types.py
> +    column: int
Просто думка.

Враховуючи, що ми в декількох місцях ми деструктуризуємо dataclass Position та це займає два рядки. 
Приклад:
```
row =  position.row
column = position.column
```

Для мінімізації коду ми можемо додати до датаклассу Position:
```
def __iter__(self):
        return iter(astuple(self)) 
```

або 

```
def __iter__(self):
        return iter((self.row, self.column))
```

тоді ми зможемо писати так:
```
row, column = position
```

2022-07-15 21:26 UTC, Fybex commented on backend/backtracking.py
> +            column += location.length
Рядки 51 - 54 аналогічні до 12 - 15

2022-07-17 07:42 UTC, TeksPeks commented on backend/backtracking.py
> +    position = Position(prev_pos.row, prev_pos.column)
Не бачу нічого поганого, дивлячись що цей `dataclass` зразу після зміни повертається і більше ніде не використовується. Але 👍

2022-07-17 07:55 UTC, TeksPeks commented on backend/backtracking.py
> +    if current_index >= len(locations):
Пробував. Так як зараз виходить менше коду.

І навіщо повертати `boolean` якщо `list[int]` також свого роду `true` 😄

2022-07-17 10:43 UTC, danmysak commented on backend/backtracking.py
> +def increase_position(previous_position: Position, direction: Direction, times: int = 1) -> Position:
`times` → `delta`.

2022-07-17 10:43 UTC, danmysak commented on backend/backtracking.py
> +        return position
Чому не `return increase_position(location.first_letter, location.type, location.length)`?

2022-07-17 10:43 UTC, danmysak commented on backend/backtracking.py
> +                next_answer = backtrack(locations, table, load_options, current_index=current_index + 1,
Перенеси `current_index=current_index + 1,` в новий рядок, щоб усі іменовані параметри були оформлені однаково.

2022-07-17 10:43 UTC, danmysak commented on backend/backtracking.py
>              if word_fits_pattern(pattern, possible_answer):
До речі... А навіщо потрібна ця перевірка? `load_options` і так поверне лише ті слова, які підходять під патерн.

2022-07-17 10:43 UTC, danmysak commented on backend/backtracking.py
> +    if current_index >= len(locations):
Перевірка там, де вона зараз, краща з того погляду, що робить функцію більш універсальною: вона повертає правильний результат і у випадку виклику з `current_index == len(locations)`, зокрема якщо її так одразу викликали ззовні.

Щодо `bool` не зрозумів: функція має повертати `list[str] | None`, а `answers` має якраз тип `list[str]`.

2022-07-17 10:47 UTC, danmysak requested changes

2022-07-17 10:47 UTC, danmysak commented on backend/backtracking.py
Подивився свіжим поглядом, і тепер не зрозумів, навіщо нам уся ця логіка з багаторазовим викликом `load_options` і спеціальним масивом `loaded_more_answers`. Я уявляв собі, що виклик `load_options(pattern, current_index)` повертатиме одні й ті самі результати кожного разу.

2022-07-18 16:05 UTC, TeksPeks commented on backend/backtracking.py
Більше не потрібна

2022-07-18 17:17 UTC, danmysak requested changes

2022-07-18 17:17 UTC, danmysak commented on backend/backtracking.py
> +        return increase_position(position, location.type, location.length)
Скоротити.

2022-07-20 17:00 UTC, danmysak requested changes

2022-07-20 17:05 UTC, danmysak approved these changes

2022-07-21 17:39 UTC, Fybex approved these changes

2022-07-21 19:07 UTC, merged