Fix failed view shown after retrying request to the api
ua-dev-front/crossword-master pull request #145
Opened 2022-11-21 16:43 UTC by TeksPeks

Fixes #140

2022-11-21 18:00 UTC, danmysak requested changes

2022-11-21 18:00 UTC, danmysak commented on frontend/src/store/index.ts
>        state.fetchAbortController = null;
Але тепер функціональність Edit не працює :-(

2022-11-29 17:13 UTC, danmysak approved these changes

2022-12-01 17:47 UTC, Fybex approved these changes

2022-12-03 14:32 UTC, merged