Issue 146 - Fix `/solve` endpoint when undefined tags come from API
ua-dev-front/crossword-master pull request #147
Opened 2022-11-26 20:39 UTC by Fybex

Resolves #146

2022-11-27 06:42 UTC, danmysak requested changes

2022-11-27 06:42 UTC, danmysak commented on backend/api.py
> +        key=lambda item: next((index for index, tag in enumerate(PART_OF_SPEECH_ORDER) if tag in item.get('tags', [])),
Тепер, наскільки я розумію, порядок частин мови, який повертає Datamuse, ігнорується. Він дійсно довільний чи все ж таки основна частина мови для даного слова іде там на першому місці?

2022-11-27 17:48 UTC, Fybex commented on backend/api.py
> +        key=lambda item: next((index for index, tag in enumerate(PART_OF_SPEECH_ORDER) if tag in item.get('tags', [])),
Порядок з Datamuse не довільний, виправив.

2022-11-27 18:07 UTC, danmysak approved these changes

2022-11-29 14:43 UTC, TeksPeks approved these changes

2022-11-29 14:44 UTC, merged