Hide questions label and button when the dialog is open
ua-dev-front/crossword-master pull request #149
Opened 2022-11-26 20:47 UTC by Fybex

Resolves #142

2022-11-27 06:46 UTC, danmysak requested changes

2022-11-27 06:46 UTC, danmysak commented on frontend/src/components/App/index.tsx
>                      {
У мене проблема лишається...

2022-11-27 17:24 UTC, Fybex commented on frontend/src/components/App/index.tsx
>                      {
https://user-images.githubusercontent.com/46112160/204150348-ab923ec7-571e-41f5-847f-1f88f44150a2.mp4

2022-11-27 19:37 UTC, danmysak commented on frontend/src/components/App/index.tsx
>                      {
Спробуй відтворити той сценарій, що на відео до задачі.

2022-12-01 19:28 UTC, danmysak approved these changes

2022-12-03 17:37 UTC, TeksPeks approved these changes

2022-12-03 18:00 UTC, merged