Normalize user questions
ua-dev-front/crossword-master pull request #163
Opened 2022-12-10 11:44 UTC by TeksPeks

Fixes #158 
Проблема справді була в тому, що апі не розпізнавало спеціальних знаків, тому тепер в питаннях, які передаються в апі залишаються тільки букви, цифри, пробіли та перенесення рядка.

2022-12-10 11:56 UTC, danmysak requested changes

2022-12-10 11:56 UTC, danmysak commented on backend/solve.py
> +# Normalizes questions for use in the api.
1) В інших місцях крапку в кінці коментаря не ставили.
2) У коментарі варто також пояснити, для чого така нормалізація потрібна.

2022-12-10 11:56 UTC, danmysak commented on backend/solve.py
> +def normalize_user_question(question: Question):
Бракує типу результату.

2022-12-10 11:56 UTC, danmysak commented on backend/solve.py
> +    return re.sub(r'[^a-zA-Z\d\n ]', '', question)
1) А той факт, що ми прибираємо коми і крапки, не сильно впливає на кінцевий результат? Якщо все ж впливає, може, є якийсь інший спосіб передати їх у API?
2) Можливо, використати `\w` (він, правда, включає ще прочерк)?
3) Дефіс і апостроф(и) точно не потрібно лишити?
4) У подібних випадках з whitespace зазвичай роблять так: замінюють `\s+` на одиночний пробіл (а також прибирають пробіли з обох боків рядка). Це дозволяє не відволікатися на конкретні види whitespace та гарантовано отримати пристойний результат.

2022-12-10 11:56 UTC, danmysak commented on backend/solve.py
> +        return get_possible_word_answers(normalize_user_question(words[word_index].question), pattern)
Думаю, нормалізація концептуально є частиною виклику API (тобто функції `get_possible_word_answers` або, можливо навіть, `api_request`), а не турботою користувача цього API.

2022-12-12 13:18 UTC, danmysak requested changes

2022-12-14 11:36 UTC, danmysak requested changes

2022-12-14 11:36 UTC, danmysak commented on backend/api.py
> +    return re.sub(r"[^\w\s\-']", '', re.sub(r'\s+', ' ', question.strip()))
1) Апостроф ще буває типографський: `’`. Можливо, їх разом із машинописним (`'`) варто зводити до єдиної форми.
2) Перевір, чи дефіс та апостроф(и) добре сприймає API Datamuse’а.

2022-12-16 16:17 UTC, TeksPeks commented on backend/api.py
> +    return re.sub(r"[^\w\s\-']", '', re.sub(r'\s+', ' ', question.strip()))
1. Привожу всі види апострофа до `'`
2. Дефіс і апостроф сприймає, але апостроф сприймає тільки в виді `'`.

2022-12-16 16:27 UTC, TeksPeks commented
Також зробив, щоб цифри залишались, тому що
[1st place](https://api.datamuse.com/words?ml=1st%20place&md=dp) i [st place](https://api.datamuse.com/words?ml=st%20place&md=dp) дають різні результати

2022-12-16 17:26 UTC, Fybex approved these changes

2022-12-16 18:12 UTC, danmysak requested changes

2022-12-16 18:12 UTC, danmysak commented on backend/api.py
> +    return re.sub(r"[^\w\s\d\-']", '', re.sub(r'\s+', ' ', re.sub(r"[ʼʻ’]", "'", question.strip())))
Хіба \w не включає \d?

2022-12-18 11:48 UTC, TeksPeks commented on backend/api.py
> +    return re.sub(r"[^\w\s\d\-']", '', re.sub(r'\s+', ' ', re.sub(r"[ʼʻ’]", "'", question.strip())))
Правда, включає

2022-12-18 15:20 UTC, danmysak approved these changes

2022-12-19 16:54 UTC, merged