Check if word returned from api fits the pattern
ua-dev-front/crossword-master pull request #165
Opened 2022-12-12 13:19 UTC by TeksPeks

Fixes #154

2022-12-12 13:39 UTC, danmysak requested changes

2022-12-12 13:39 UTC, danmysak commented on backend/api.py
> +            and word_fits_pattern(item['word'], pattern)}
Додай коментар, який пояснює, навіщо ця перевірка.

2022-12-12 13:39 UTC, danmysak commented on backend/helpers.py
> +        if character != '?' and character != string[index]:
1) Це не зовсім відповідає оголошенню типу `Pattern = list[str | None]`...
2) Використай `zip`.
3) Усю функцію можна написати «в один рядок».

2022-12-14 11:39 UTC, danmysak requested changes

2022-12-14 11:39 UTC, danmysak commented on backend/api.py
> +            and word_fits_pattern(item['word'], pattern)}  # Api can return word not fitting pattern (with extra space)
Трохи краще:
`API can return words not actually fitting the pattern (e.g., with extra spaces)`

2022-12-14 11:39 UTC, danmysak commented on backend/helpers.py
> +    return all(character[0] == character[1] for character in zip(string, pattern))
Ну, це зовсім неправильно... Потестуй, будь ласка.
Також замість `character` відразу деструктуризуй у дві змінні.

2022-12-16 16:27 UTC, TeksPeks commented
Також зробив, щоб цифри залишались, тому що
[1st place](https://api.datamuse.com/words?ml=1st%20place&md=dp) i [st place](https://api.datamuse.com/words?ml=st%20place&md=dp) дають різні результати

2022-12-16 17:31 UTC, Fybex approved these changes

2022-12-16 17:51 UTC, TeksPeks commented
Перемістив виклик `word_fits_pattern` у нову функцію `get_api_response`, тому що треба перевіряти чи слова підходять і при генерації і при розв'язанні кросворда. А функцію створив, щоб у `api_request` виконувався тільки виклик апі, а обробка результату була в окремій функції.

2022-12-16 19:36 UTC, danmysak commented on backend/api.py
> +           'get_possible_word_answers_and_questions']
Для чого ця зміна?

2022-12-16 19:43 UTC, danmysak approved these changes

2022-12-18 11:08 UTC, merged