Words from API must contain only Latin characters
ua-dev-front/crossword-master pull request #166
Opened 2022-12-12 17:44 UTC by Fybex

Resolves #156

2022-12-12 18:08 UTC, danmysak commented on backend/api.py
> +        if (question := next(filter(is_valid_question, item.get('defs', [])), None))
Внести `sort_by_part_of_speech` та `leave_only_alpha_words` у `api_request`.

2022-12-14 17:39 UTC, danmysak requested changes

2022-12-14 17:39 UTC, danmysak commented on backend/api.py
> +                                        (normalize_question(question) for question in item.get('defs', []))), None))}
Переставив назад `normalize_question`. Це була причина https://github.com/ua-dev-front/crossword-master/issues/153.

2022-12-14 18:14 UTC, danmysak approved these changes

2022-12-16 17:31 UTC, TeksPeks approved these changes

2022-12-16 17:32 UTC, merged