Replace `API_PATH` from 'datamuse' to `onelook`
ua-dev-front/crossword-master pull request #167
Opened 2022-12-14 15:15 UTC by Fybex

Resolves #155

2022-12-14 17:41 UTC, danmysak requested changes

2022-12-14 17:41 UTC, danmysak commented on backend/api.py
> +        return question.capitalize() + ('' if question.strip().endswith(END_OF_SENTENCE) else END_OF_SENTENCE)
Якщо визначення справді може містити пробіли по боках, то, можливо, це не зовсім те місце, де їх треба прибирати?

2022-12-14 17:59 UTC, Fybex commented on backend/api.py
> +        return question.capitalize() + ('' if question.strip().endswith(END_OF_SENTENCE) else END_OF_SENTENCE)
Після зміни `API_PATH` я помітив, що питання мали дві точки, тому я прибираю перевіряю чи останній символ питання без пробілів точка

2022-12-14 18:11 UTC, danmysak approved these changes

2022-12-16 17:32 UTC, TeksPeks approved these changes

2022-12-16 17:32 UTC, merged