Cell
ua-dev-front/crossword-master pull request #19
Opened 2022-07-10 12:24 UTC by Fybex

Fixes #17

2022-07-15 20:02 UTC, Fybex commented on frontend/src/App.tsx
> +          onEdited: (filled) => console.log(filled),
Також змінив border на box-shadow для filled стану клітинки, щоб зробити анімацію плавніше.

2022-07-15 20:03 UTC, Fybex commented on frontend/src/components/Cell/index.tsx
> +    corner && `cell--${corner}`
BEM methodology. В ній для перед модифікаторами ставлять `--`

2022-07-15 20:05 UTC, Fybex commented on frontend/src/components/Cell/index.tsx
> +      {!editable && content?.number && (
> Може, винести умову `!editable` на рівень вище як спільну?

Спробував спосіб з уроку. Тоді треба додавати `key` prop до елементів масиву, не впевнений чи треба змінювати цей код, враховуючи вище описану проблему  🤔

2022-07-17 11:32 UTC, danmysak commented on frontend/src/components/Cell/index.tsx
> +      handleClick();
Не дуже добре: `handleClick`, виходячи з назви, має запускатися тоді, коли реально відбувся клік. Якщо хочеш позбутися дублікації коду, створи третю функцію, яку викликатиме і `handleKeyDown`, і `handleClick`.

2022-07-17 11:32 UTC, danmysak commented on frontend/src/components/Cell/index.tsx
> +      onKeyDown={handleKeyDown}
Знову ж таки: `() => handleClick()` та `() => handleKeyDown()`.

2022-07-17 11:32 UTC, danmysak commented on frontend/src/components/Cell/styles.scss
> +    $cell-transition: 0.2s ease-in-out;
1) Там, де це можливо, варто користуватися CSS- (а не SASS-) змінними: їх у разі необхідності можна бути міняти динамічно.
2) Навіщо у змінну винесено `transition`?

2022-07-17 11:32 UTC, danmysak commented on frontend/src/styles/index.scss
> +  --font-straight: 'Roboto', sans-serif;
А де імпорт?

2022-07-17 11:32 UTC, danmysak commented on frontend/src/components/Cell/styles.scss
> +        box-shadow: 0px 0px 0px 2px cl(near-black);
Чому замінив `border` на `box-shadow`?

2022-07-17 11:32 UTC, danmysak commented on frontend/src/App.tsx
> +          onEdited: (filled) => console.log(filled),
> зміна стану filled не дуже помітна
Те, що фон не змінюється, так і задумано. Наскільки воно уцілому інтуїтивно, побачимо вже тоді, коли буде готове поле повністю.

> Також змінив border на box-shadow для filled стану клітинки, щоб зробити анімацію плавніше.
Я б цю проблему вирішив зміною фонового кольору border: від transparent to near-black. Власне, мені здається, з погляду семантичності/логічності це буде трохи правильніше, ніж тінь, яка з’являється «з-під» комірки (хоча це й красиво). Спробуй.

2022-07-17 11:37 UTC, danmysak commented on frontend/src/components/Cell/index.tsx
> +    corner && `cell--${corner}`
Гм... Тут сказано про `_`: https://en.bem.info/methodology/quick-start/#modifier

2022-07-17 11:37 UTC, danmysak commented on frontend/src/components/Cell/index.tsx
> +      {!editable && content?.number && (
Спробуй із фрагментами: `<>...</>`.

2022-07-17 11:37 UTC, danmysak commented on frontend/src/components/Cell/styles.scss
> +    &__number {
Кольору досі нема.

2022-07-17 11:54 UTC, danmysak commented on frontend/src/components/Cell/styles.scss
> +        top: 0;
До речі, в яких браузерах ти тестуєш? Дивлюся, що у файрфоксі виглядає не дуже красиво.

2022-07-17 20:58 UTC, Fybex commented on frontend/src/components/Cell/styles.scss
> +    $cell-transition: 0.2s ease-in-out;
`transition` винесено в змінну, щоб не дублювати нижче два рази

2022-07-17 21:01 UTC, Fybex commented on frontend/src/components/Cell/styles.scss
> +        box-shadow: 0px 0px 0px 2px cl(near-black);
Замінив на `border`

2022-07-17 21:01 UTC, Fybex commented on frontend/src/components/Cell/styles.scss
> +        top: 0;
опустив на 2px

2022-07-18 14:31 UTC, danmysak commented on frontend/src/components/Cell/index.tsx
> +    corner && `cell--${corner}`
Поки не враховано.

2022-07-18 14:34 UTC, danmysak commented on frontend/src/components/Cell/styles.scss
> +    $cell-transition: 0.2s ease-in-out;
Скористайся окремо властивостями `transition-property`, `transition-duration`, `transition-timing-function`.

2022-07-18 17:26 UTC, danmysak requested changes
Не працюють кнопки.

2022-07-18 17:31 UTC, danmysak approved these changes

2022-07-21 13:28 UTC, TeksPeks approved these changes

2022-07-21 17:36 UTC, merged