Grid
ua-dev-front/crossword-master pull request #20
Opened 2022-07-21 19:25 UTC by Fybex

Fixes #18

2022-07-22 16:58 UTC, danmysak requested changes

2022-07-22 17:59 UTC, Fybex commented on frontend/src/components/Grid/index.tsx
> +      : []),
Постарався виправити, тепер краще, але не впевнений чи повністю зрозумів вашу ідею

2022-07-22 18:01 UTC, Fybex commented on frontend/src/App.tsx
> +      <Grid mode={Mode.Answer} matrix={answerMatrix} />
Додав в `Cell` клас `cell_editable`, тепер тільки при наявності цього класу елемент може бути фокусованим та має hover стилі, також виніс основний клас `cell` в змінну для уникнення дублювання

2022-07-24 16:28 UTC, TeksPeks approved these changes

2022-07-24 17:08 UTC, danmysak requested changes

2022-07-24 17:08 UTC, danmysak commented on frontend/src/components/Cell/index.tsx
> +      tabIndex={editable ? 0 : -1}
`-1` → `undefined` або `null`.

2022-07-24 17:08 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +    });
```
const dimensions: {
  [Corner]: [number, number]
} = {
  Corner.TopLeft: [0, 0],
  ...
  Corner.BottomRight: [width, height],
};
```

2022-07-24 18:24 UTC, danmysak requested changes

2022-07-24 18:24 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +    return corners;
Можна, до речі, без проміжної змінної ;-)

2022-07-24 18:26 UTC, danmysak approved these changes

2022-07-24 18:27 UTC, merged