Solve endpoint
ua-dev-front/crossword-master pull request #21
Opened 2022-07-21 20:21 UTC by TeksPeks

Ендпоінт розв'язування питань, базований на бектрекінгу

2022-07-22 16:57 UTC, danmysak requested changes

2022-07-22 16:57 UTC, danmysak commented on backend/increase_position.py
> +from app_types import Direction, Position
`increase_position.py` → `helpers.py` абощо.

2022-07-22 16:57 UTC, danmysak commented on backend/solve_questions.py
> +    return position.row < len(table) and position.column < len(table) and table[position.row][position.column]
1) `correct` → `filled`.
2) Варто перевіряти також на від’ємні індекси.

2022-07-22 16:57 UTC, danmysak commented on backend/solve_questions.py
> +    return ''.join(letter if isinstance(letter, str) else '?' for letter in pattern)
Винеси літерал `?` у відповідним чином названу константу.

2022-07-22 16:57 UTC, danmysak commented on backend/solve_questions.py
> +    return ''.join(letter if isinstance(letter, str) else '?' for letter in pattern)
Винеси літерал `?` у відповідним чином названу константу.

2022-07-22 16:57 UTC, danmysak commented on backend/solve_questions.py
> +def get_possible_word_answers(question: Question, length: int, pattern=None) -> list[str]:
1) `pattern` не типізовано.
2) Чи `pattern`, рівний `None`, колись трапляється?

2022-07-22 16:57 UTC, danmysak commented on backend/solve_questions.py
> +        pattern = "?" * length
Одинарні лапки. Але скоріше за все цей код зрештою взагалі зникне.

2022-07-22 16:57 UTC, danmysak commented on backend/solve_questions.py
> +def get_api_pattern(pattern: Pattern) -> str:
Думаю, ця функція має бути вкладеною в `get_possible_word_answers` (або винесена з нею в окремий файл).

2022-07-22 16:57 UTC, danmysak commented on backend/solve_questions.py
> +    for ind, answer in enumerate(raw_answers):
`ind` → `index`.

2022-07-22 16:57 UTC, danmysak commented on backend/solve_questions.py
> +    parsed_answers = {'across': [], 'down': []}
dict можна зробити по самому енаму, а не по його значеннях.

2022-07-22 16:57 UTC, danmysak commented on backend/solve_questions.py
> +    parsed_answers = {'across': [], 'down': []}
dict можна зробити по самому енаму, а не по його значеннях.

2022-07-22 16:57 UTC, danmysak commented on backend/solve_questions.py
> +    def load_more_answers(pattern, word_id):
1) Чому `more`?
2) Нема типізації.

2022-07-22 16:57 UTC, danmysak commented on backend/solve_questions.py
> +        word = words[word_id]
Чи справді ця змінна має сенс?

2022-07-22 16:57 UTC, danmysak commented on backend/solve_questions.py
> +
Чи не забагато порожніх рядків?

2022-07-24 16:52 UTC, danmysak requested changes

2022-07-24 16:52 UTC, danmysak commented on backend/solve_questions.py
> +from api import get_possible_word_answers
Абетка.

2022-07-24 16:52 UTC, danmysak commented on backend/solve_questions.py
> +    return position.row in range(len(table)) and position.column in range(len(table)) and table[position.row][position.column]
Зайве припущення, що таблиця — квадратна.

2022-07-24 16:52 UTC, danmysak commented on backend/solve_questions.py
> +    def load_word_answers(pattern: Pattern, word_id: int) -> list[str]:
Чому `word_id`, а не індекс?

2022-07-24 17:10 UTC, danmysak approved these changes

2022-07-24 18:26 UTC, Fybex approved these changes

2022-07-25 05:30 UTC, merged