Pictogram text component
ua-dev-front/crossword-master pull request #27
Opened 2022-07-26 10:41 UTC by TeksPeks

Назвав компонент `TabulatorItem`, але може краще назвати його інакше.
Також додав компонент іконку назад.

2022-07-26 16:38 UTC, Fybex requested changes

2022-07-26 16:38 UTC, Fybex commented on frontend/src/components/BackIcon/styles.scss
> +}
Немає пустого рядка в кінці

2022-07-26 16:38 UTC, Fybex commented on frontend/src/components/TabulatorItem/index.tsx
> +  icon: React.ReactNode;
Імпортуй ReactNode і використовуй без React.

2022-07-26 16:38 UTC, Fybex commented on frontend/src/App.tsx
> +          <Cell
чи справді нам потрібно все так ускладнювати та використовувати `Cell`, а не просто літеру? 🤔

2022-07-26 16:38 UTC, Fybex commented on frontend/src/components/TabulatorItem/styles.scss
> +}
Немає пустого рядка в кінці файлу

2022-07-26 16:38 UTC, Fybex commented on frontend/src/components/TabulatorItem/styles.scss
> +  &:active:not(&_selected) {
чи не можна не повторювати `:not(&_selected)`, можна ж винести `:not(&_selected)` на рівень вище

2022-07-26 16:38 UTC, Fybex commented on frontend/src/components/TabulatorItem/styles.scss
> +  gap: 7px;
в дизайні `gap` 7px, коли item selected, коли normal - 4px

2022-07-26 16:40 UTC, Fybex requested changes
Також, як буде відбуватися взаємодія? Я не бачу ніяких event-ів

2022-07-26 17:15 UTC, TeksPeks commented on frontend/src/App.tsx
> +          <Cell
В дизайні клітинка

2022-07-26 17:16 UTC, TeksPeks commented
> Також, як буде відбуватися взаємодія? Я не бачу ніяких event-ів

Додав `onClick`

2022-07-26 17:28 UTC, danmysak commented on frontend/src/App.tsx
> +import TabulatorItem from './components/TabulatorItem';
`Tab`?

2022-07-26 17:28 UTC, danmysak commented on frontend/src/App.tsx
> +          <Cell
Зробимо з допомогою SVG.

2022-07-31 19:36 UTC, danmysak requested changes

2022-07-31 19:36 UTC, danmysak commented on frontend/src/icons/SquareLetter.tsx
> +export default function SquareLetter() {
Цей і решта компонентів-піктограм, крім стрілки, значно простіше реалізується без SVG.

2022-07-31 19:36 UTC, danmysak commented on frontend/src/types/tabData.ts
> +  };
Обійдімося без цього типу (обговорили окремо).

2022-07-31 19:36 UTC, danmysak commented on frontend/src/icons/LeftArrow.tsx
> +        fillOpacity='0.67'
Кольори та прозорість виставляємо в CSS — зокрема, щоб не було дублювань.

2022-07-31 19:36 UTC, danmysak commented on frontend/src/components/Tab/index.tsx
> +import './styles.scss';
CSS-імпорти у нас ідуть останніми.

2022-07-31 19:36 UTC, danmysak commented on frontend/src/components/Tab/index.tsx
> +  const { isSelected } = data;
Деструктуризуємо в сигнатурі функції.

2022-07-31 19:36 UTC, danmysak commented on frontend/src/components/Tab/index.tsx
> +      onClick={isSelected ? undefined : data.onClick}
`() => data.onClick()` (бо інакше ризикуємо передати у функцію неочікувані параметри).

2022-07-31 19:36 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
> +  }
Навіщо це?

2022-07-31 19:36 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
> +    border-color: cl(dark);
Використай `border-bottom`.

2022-07-31 19:36 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
> +    }
Чому саме `svg`, якщо ти дозволяєш передавати довільні елементи як піктограму?

2022-07-31 19:36 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
> +    & > span {
По тегах селектори не будуємо.

2022-07-31 19:36 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
> +      & > span {
По тегах селектори не будуємо.

2022-07-31 19:36 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
> +      }
По тегах селектори не будуємо.

2022-07-31 19:36 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
> +        border-color: cl(near-black);
Додай анімацію для плавності, як в Андрія.

2022-07-31 19:36 UTC, danmysak commented on frontend/src/icons/LeftArrow.tsx
> +      width='17'
Чому 17, якщо в дизайні 16?

2022-07-31 19:36 UTC, danmysak commented on frontend/src/icons/SquareLetter.tsx
> +          A
Твоя літерка виглядає темнішою за ту, що в дизайні.

2022-07-31 19:36 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
> +      font-weight: 600;
По-перше, схоже, в Google Fonts немає жирності 600 (тому зараз виглядає, як 700), а візуально найближча, яка є, — 500. По-друге, навіть 500 зараз чомусь виглядає, як 300. Спробуй розібратися.

2022-08-01 16:59 UTC, TeksPeks commented on frontend/src/components/TabulatorItem/styles.scss
> +    border-color: cl(selected);
Я не бачу в чому вони різні.

2022-08-01 16:59 UTC, TeksPeks commented on frontend/src/components/Tab/styles.scss
> +  }
Різні іноки можуть бути різної висоти, це треба щоб відцентрувати їх вертикально

2022-08-01 17:36 UTC, danmysak requested changes

2022-08-01 17:36 UTC, danmysak commented on frontend/src/components/Tab/index.tsx
> +      tabIndex={0}
Зайвий рядок.

2022-08-01 17:36 UTC, danmysak commented on frontend/src/components/Tab/index.tsx
> +      onClick={() => (onClick ? onClick() : null)}
`onClick?.()`

2022-08-01 17:36 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
> +    transition: all 0.2s ease-in-out;
1) Позбудьмося дублювання значень.
2) Обійтися без `all`.

2022-08-01 17:36 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
> +  * {
Обійтися без зірочки.

2022-08-01 17:36 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
> +      * {
Без зірочки!

2022-08-01 17:36 UTC, danmysak commented on frontend/src/icons/Square/styles.scss
> +    height: 16px;
Винести у змінну.

2022-08-01 17:36 UTC, danmysak commented on frontend/src/icons/SquareFilled/styles.scss
> +    width: 16px;
Змінна.

2022-08-01 17:36 UTC, danmysak commented on frontend/src/icons/SquareFilled/styles.scss
> +    border-radius: 2px;
Спробувати уникнути дублювання зі `Square`.

2022-08-01 17:36 UTC, danmysak commented on frontend/src/icons/SquareLetter/styles.scss
> +    height: 16px;
Змінна + дублювання з іншими `Square...`.

2022-08-01 17:36 UTC, danmysak commented on frontend/src/icons/SquareLetter/styles.scss
> +    line-height: 16px;
Дублювання з іншими `Square...`.

2022-08-03 06:24 UTC, TeksPeks commented on frontend/src/components/Tab/styles.scss
> +      font-weight: 600;
Я імпортував `Roboto` тільки жирності 400 і 500(це всі які використовуються зараз), і тоді 500 стала виглядати як треба.

2022-08-03 16:16 UTC, danmysak requested changes

2022-08-03 16:16 UTC, danmysak commented on frontend/src/components/Cell/styles.scss
> +}
Порожній рядок.

2022-08-03 16:16 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
> +      --icon-colour: #{cl(dark)};
Використовуємо американську ортографію: `color`.

2022-08-03 16:16 UTC, danmysak commented on frontend/src/icons/LeftArrow/index.tsx
> +      className='icon-left-arrow icon'
Тут і в решті аналогічних місць — поміняй класи місцями й приведи до BEM.

2022-08-03 16:16 UTC, danmysak commented on frontend/src/icons/SquareFilled/index.tsx
> +  return <span className='icon-square icon-square_filled icon' />;
У такому випадку Square та SquareFilled є сенс сумістити в один компонент.

2022-08-03 16:16 UTC, danmysak commented on frontend/src/icons/SquareLetter/index.tsx
> +  return <span className='icon-square_letter icon-square icon'>A</span>;
Можливо, в той самий спільний компонент винести і цей варіант піктограми?

2022-08-03 16:16 UTC, danmysak commented on frontend/src/icons/SquareFilled/styles.scss
> +  }
Щонайменше у Хромі літера виглядає притисненою до нижнього боку квадратика, а не відцентрованою.

2022-08-03 17:02 UTC, TeksPeks commented on frontend/src/icons/SquareFilled/styles.scss
> +  }
в мене виглядає відцентровано

2022-08-03 17:12 UTC, danmysak requested changes

2022-08-03 17:12 UTC, danmysak commented on frontend/src/icons/Square/index.tsx
> +export default function Square(props: Props) {
1) Рамка заповненої комірки в дизайні — чорна.
2) Деструктуризація в сигнатурі.

2022-08-03 17:12 UTC, danmysak commented on frontend/src/icons/Square/index.tsx
> +  return <span className={classes}>{content && content}</span>;
Спростити вираз.

2022-08-04 20:11 UTC, TeksPeks commented on frontend/src/icons/SquareFilled/styles.scss
> +  }
відцентрував

2022-08-05 10:55 UTC, danmysak approved these changes

2022-08-05 16:33 UTC, Fybex approved these changes

2022-08-05 16:36 UTC, merged