Generate answers and questions
ua-dev-front/crossword-master pull request #28
Opened 2022-07-26 16:05 UTC by Fybex

Fixes #7

2022-07-26 16:58 UTC, danmysak requested changes

2022-07-26 16:58 UTC, danmysak commented on backend/api.py
> +
1) Використати dataclass, а не dict.
2) Що за порожнє визначення?
3) Зайвий порожній рядок у кінці файлу.

2022-07-26 16:58 UTC, danmysak commented on backend/app.py
> +from generate import generate_questions_and_words
1) Абетка.
2) Тоді для однорідності треба перейменувати `solve_questions` → `solve`.

2022-07-26 16:58 UTC, danmysak commented on backend/api.py
> +def get_possible_word_answers_and_questions(pattern: Pattern) -> list[dict[str, str]]:
Чому в такому дивному порядку: `answers_and_questions`?

2022-07-26 16:58 UTC, danmysak commented on backend/backtracking.py
>  def solve(locations: list[WordLocation], load_options: LoadOptions) -> list[str] | None:
Забув оновити тип. Але в цілому я б, мабуть, запропонував зробити дещо інакше (обговоримо на занятті).

2022-07-26 16:58 UTC, danmysak commented on backend/generate.py
> +from api import get_possible_word_answers_and_questions
Абетка.

2022-07-26 16:58 UTC, danmysak commented on backend/generate.py
> +def define_words(table: Table) -> list[WordLocation]:
Чи це по суті не та сама функція, яка вже реалізована у файлі `solve_questions.py`?..

2022-07-27 19:19 UTC, Fybex commented on backend/backtracking.py
>  def solve(locations: list[WordLocation], load_options: LoadOptions) -> list[str] | None:
Прибрав всі зміни з бектрекінгу

2022-07-27 19:23 UTC, Fybex commented on backend/generate.py
> +def define_words(table: Table) -> list[WordLocation]:
не впенений чи це потрібно та можна об‘єднати

в `solve_questions.py` ми проходимося по вже створеному списку слів, у випадку генерації ми проходимо по таблиці

Це дві різні сутуації на мій погляд 🤔

2022-07-28 16:45 UTC, danmysak requested changes

2022-07-28 16:45 UTC, danmysak commented on backend/app.py
> +    return GenerateResponse(generate_words_and_questions(table))
Можна позбутися проміжної змінної.

2022-07-28 16:45 UTC, danmysak commented on backend/solve.py
> +    return get_parsed_answers(answers, words)
Слід повернути порожній рядок у кінці файлу.

2022-07-28 16:45 UTC, danmysak commented on backend/api.py
> +def get_possible_word_answers_and_questions(pattern: Pattern) -> list[tuple[str, str]]:
А чому все ж таки не dataclass?

2022-07-28 16:45 UTC, danmysak commented on backend/generate.py
> +    return None
1) Краще назвати функцію `extract_location`, а замість `words` аргумент назвати `locations` — призначення функції стане, мабуть, зрозумілішим.
2) Скористайся конструкцією `next(...)`.

2022-07-28 16:45 UTC, danmysak commented on backend/generate.py
> +    return False
Спробуй позбутися дублювання логіки між горизонталями й вертикалями. Можливо, тобі допоможе функція `increase_position` з `helpers.py` (до речі, перейменуй її у `shift_position`).

2022-07-28 16:45 UTC, danmysak commented on backend/generate.py
> +def define_words(table: Table) -> list[WordLocation]:
Чому `define`, а не, скажімо, `locate`?

2022-07-28 16:45 UTC, danmysak commented on backend/generate.py
> +                        word.length += 1
Цей підхід, звичайно, має присмак небажаної мутабельності. Без неї ніяк не можна обійтися?

2022-07-28 16:45 UTC, danmysak commented on backend/generate.py
> +        return question.split('\t')[1]
А оце чому так?..

2022-07-28 16:45 UTC, danmysak commented on backend/generate.py
> +        return max(response, key=lambda item: item.id).id + 1
Краще `map` + `max` із `default`.

2022-07-28 16:45 UTC, danmysak commented on backend/generate.py
> +                        cache: list[tuple[str, str]]) -> GenerateWords | None:
А де в результаті зберігаються питання? Не розумію...

2022-07-28 16:45 UTC, danmysak commented on backend/generate.py
> +        ))
Важко для розуміння.

2022-07-28 17:18 UTC, danmysak commented on backend/generate.py
> +        return question.split('\t')[1]
Домовилися додати аргумент, що обмежує кількість розбиттів та перенести це в API.

2022-07-28 17:23 UTC, danmysak commented on backend/generate.py
> +        return max(response, key=lambda item: item.id).id + 1
Але вирішили, що нумерувати потрібно більш детерміновано.

2022-08-01 06:04 UTC, Fybex commented on backend/api.py
> +def get_possible_word_answers_and_questions(pattern: Pattern) -> list[tuple[str, str]]:
Створив dataclass `GenerateApiResponse`

2022-08-01 06:05 UTC, Fybex commented on backend/generate.py
> +    return False
Створив `get_axes` в `helpers.py`

2022-08-01 06:05 UTC, Fybex commented on backend/generate.py
> +def define_words(table: Table) -> list[WordLocation]:
Перейменував на `determine_locations`

2022-08-01 06:06 UTC, Fybex commented on backend/generate.py
> +                        word.length += 1
Переніс всі функції-помічники в `determine_locations`

2022-08-01 06:07 UTC, Fybex commented on backend/generate.py
> +        ))
Зробив краще

2022-08-01 08:38 UTC, danmysak requested changes

2022-08-01 08:38 UTC, danmysak commented on backend/api.py
> +from app_types import Pattern, Question, GenerateApiResponse
Абетка.

2022-08-01 08:38 UTC, danmysak commented on backend/api.py
> +        return question.split('\t', 1)[1]
Додай коментар, який роз’яснює, що там таке є перед символом табуляції.

2022-08-01 08:38 UTC, danmysak commented on backend/app_types.py
> +    question: str
Якщо вже так, прибери аліаси `Answer` і `Question` вище.

2022-08-01 08:38 UTC, danmysak commented on backend/generate.py
> +    GenerateApiResponse
Абетка.

2022-08-01 08:38 UTC, danmysak commented on backend/helpers.py
> +    COLUMN = 'column'
Навіщо потрібен ще один енам? Чи не можна обійтися енамом `Direction`?

2022-08-01 08:38 UTC, danmysak commented on backend/helpers.py
> +__all__ = ['get_axes', 'shift_position']
Якщо експортуємо функцію, то має сенс експортувати й типи в її сигнатурі.

2022-08-01 08:38 UTC, danmysak commented on backend/helpers.py
> +    fixed_axis: str
1) Слід використати енами, а не рядки.
2) Суфікс `_axis` у цьому контексті зайвий.

2022-08-01 08:38 UTC, danmysak commented on backend/helpers.py
> +        return iter((self.changeable_axis, self.fixed_axis))
Отак це точно зайве: робить код вразливим до помилок.

2022-08-01 08:38 UTC, danmysak commented on backend/helpers.py
> +    new_position.__setattr__(get_axes(direction).changeable_axis, new_axes_position)
Тут старий код, на мій погляд, значно читабельніший.

2022-08-01 08:38 UTC, danmysak commented on backend/generate.py
> +                         scope_locations: list[WordLocation]) -> WordLocation | None:
Зміни `scope_` на щось, що характеризує змінну, а не описує її використання програмістом.

2022-08-01 08:38 UTC, danmysak commented on backend/generate.py
> +                        cache: list[GenerateApiResponse]) -> GenerateWords | None:
А чому кеш у тебе список, а не словник?

2022-08-01 08:38 UTC, danmysak commented on backend/app_types.py
> +    answer: Answer
Онови https://fybex.notion.site/API-crossword-master-14c1740fda6f4ef09f27a8ee657c6f32.

2022-08-01 17:06 UTC, danmysak requested changes

2022-08-01 17:06 UTC, danmysak commented on backend/api.py
> +        return question.split('\t', 1)[1]  # remove first line of unnecessary data
«Проіменувати» частини.

2022-08-02 18:30 UTC, Fybex commented on backend/helpers.py
> +    new_position.__setattr__(get_axes(direction).changeable_axis, new_axes_position)
змінив `__getattribute__` -> `getattr`, `__setattr__` -> `setattr`

2022-08-02 18:31 UTC, Fybex commented on backend/api.py
> +        return question.split('\t', 1)[1]  # remove first line of unnecessary data
перша частина str, яка до tab, й правда part of speech

2022-08-03 16:49 UTC, danmysak approved these changes

2022-08-04 06:49 UTC, TeksPeks approved these changes

2022-08-04 07:13 UTC, merged