Layout
ua-dev-front/crossword-master pull request #30
Opened 2022-08-03 16:55 UTC by Fybex

Fixes #22

2022-08-07 17:27 UTC, danmysak requested changes

2022-08-09 16:36 UTC, Fybex commented on frontend/src/components/Layout/styles.scss
> +                background-image: url('../../assets/repeated_background.webp');
не розумію 2

2022-08-09 18:06 UTC, danmysak requested changes

2022-08-09 18:06 UTC, danmysak commented on frontend/src/components/Layout/styles.scss
> +        min-height: 100vh;
Використовуй `100%`, а не `100vh`: щонайменше `100vh` нестабільно працює на мобільних телефонах, де динамічно прибираються верхня та нижня панелі інтерфейсу браузера, збільшуючи простір сторінки.

2022-08-09 18:06 UTC, danmysak commented on frontend/src/components/Layout/styles.scss
> +        font-weight: 700;
`bold`

2022-08-09 18:06 UTC, danmysak commented on frontend/src/components/Layout/styles.scss
> +        left: 30px;
Зроби це падингом — наприклад, щоб справа текст теж не притулявся до краю ближче ніж на 30 пікселів.

2022-08-09 18:06 UTC, danmysak commented on frontend/src/components/Layout/styles.scss
> +        min-height: 860px;
Це не має бути захардкоджено, а має визначатися висотою фонового зображення.
Як усе відображається, поки фон не підвантажився — окреме питання...

2022-08-11 13:11 UTC, danmysak requested changes

2022-08-11 13:11 UTC, danmysak commented on frontend/src/components/Layout/styles.scss
> +        width: 100vw;
Коли це можливо, без `vw` теж краще обійтися.

2022-08-11 17:06 UTC, danmysak commented on frontend/src/components/Layout/styles.scss
> +                background-image: url('../../assets/repeated_background.webp');
2 — не спрацювало :-(

2022-08-11 17:19 UTC, danmysak commented on frontend/src/components/Layout/styles.scss
> +        min-height: 860px;
Домовилися дописати коментар, звідки це число береться.

2022-08-13 10:30 UTC, Fybex commented on frontend/src/components/Layout/styles.scss
> +        min-height: 860px;
Дописав коментар 👍

2022-08-13 10:30 UTC, Fybex commented on frontend/src/components/Layout/styles.scss
> +
Додав min-width, viewport - 656px, це width `layout__content`

2022-08-13 13:16 UTC, danmysak commented on frontend/src/components/Layout/styles.scss
> +        width: 100vw;
У мене висота виходить не на весь екран на демо-сторінці:
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/6333637/184495804-f5a940d9-1f4a-4683-835b-27b236a281db.png">

2022-08-13 13:17 UTC, danmysak commented on frontend/src/components/Layout/styles.scss
> +
Виглядає асиметрично:
<img width="364" alt="image" src="https://user-images.githubusercontent.com/6333637/184495853-3f99aa45-a8a2-4aa8-97df-4f6dca894d21.png">

2022-08-13 13:17 UTC, danmysak requested changes
Прокоментував у старих обговореннях.

2022-08-13 14:05 UTC, Fybex commented on frontend/src/components/Layout/styles.scss
> +        width: 100vw;
я не знаю як це виправити без `min-height: 100vh`

2022-08-13 14:10 UTC, danmysak commented on frontend/src/components/Layout/styles.scss
> +        width: 100vw;
Ну, зараз воно не на всю висоту при виставленому `100%` через те, що батьківські елементи по ланцюжку вже самі не на всю висоту.

2022-08-13 16:43 UTC, Fybex commented on frontend/src/components/Layout/styles.scss
> +        width: 100vw;
Дописав такий код:
```
html,
body,
#root {
  height: 100%;
}
```

Тепер сторінці погано:
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/46112160/184503187-a84b011b-c9d4-4983-95a6-86beb33f9cf8.png">

2022-08-15 14:38 UTC, danmysak commented on frontend/src/components/Layout/index.tsx
> +        <div className='layout__content'>{children}</div>
Щоб не забулося: семантична розмітка.

2022-08-15 16:56 UTC, danmysak commented on frontend/src/components/Layout/styles.scss
> +
Уже краще, але стирчить олівчик плюс з’являється горизонтальна смуга прокручування.

<img width="34" alt="image" src="https://user-images.githubusercontent.com/6333637/184680072-8595fe8c-719f-4944-904a-bedde030eec0.png">

2022-08-15 16:57 UTC, danmysak commented on frontend/src/components/Layout/index.tsx
> +        <div className='layout__content'>{children}</div>
Думаю, `main` повинен бути глибше.

2022-08-15 16:57 UTC, danmysak requested changes
Дописав у старих обговореннях.

2022-08-15 18:13 UTC, danmysak commented on frontend/src/components/Layout/styles.scss
> +
Як обговорили на занятті, на мобільних пристроях лишається сіра смуга праворуч.

2022-08-16 19:11 UTC, Fybex commented on frontend/src/components/Layout/styles.scss
> +
Зменшив min-width до 560

2022-08-17 06:43 UTC, danmysak approved these changes

2022-08-18 18:57 UTC, TeksPeks approved these changes

2022-08-18 19:22 UTC, merged