Label
ua-dev-front/crossword-master pull request #33
Opened 2022-08-07 12:08 UTC by Fybex

Fixes #31

2022-08-07 13:11 UTC, danmysak requested changes

2022-08-07 13:11 UTC, danmysak commented on frontend/src/types/labelSize.ts
> +export default LabelSize;
Поперенось типи з папки `frontend/src/types` у файли компонентів, яких вони безпосередньо стосуються.

2022-08-07 13:11 UTC, danmysak commented on frontend/src/components/Label/index.tsx
> +  const classes = `label label_${size}`;
На мій смак, проміжна змінна невиправдана.

2022-08-07 13:11 UTC, danmysak commented on frontend/src/components/Label/styles.scss
> +    --font-size-line-height-coefficient: 2;
Використай `em` для `line-height` — змінні та функція тобі не знадобляться.

2022-08-07 13:11 UTC, danmysak commented on frontend/src/components/Label/styles.scss
> +    width: 100%;
Ця властивість зайва, якщо ти покладаєшся, що в тебе елемент має `display: block`. Натомість я б на це не покладався, а виставив `display: block` явно, виставив би також `margin`, а `width` прибрав би.

2022-08-08 19:50 UTC, TeksPeks approved these changes

2022-08-09 11:47 UTC, danmysak requested changes

2022-08-09 11:47 UTC, danmysak commented on frontend/src/components/Label/styles.scss
> +    --large-font-size: 21px;
Чи справді потрібні змінні? Якщо так, то бажано перейменувати:
1) Властивість — перша (як із `color-`), а вже далі `small`/`large`.
2) Щоб уникнути конфлікту імен, треба було б додати префікс `label-`.

2022-08-09 11:47 UTC, danmysak commented on frontend/src/components/Label/labelSize.ts
> +export default LabelSize;
Перенеси в `index.tsx` — і аналогічно зроби з іншими типами.

2022-08-09 16:41 UTC, Fybex commented on frontend/src/components/Label/styles.scss
> +    --large-font-size: 21px;
Змінні не потрібні, прибрав

2022-08-09 16:50 UTC, danmysak approved these changes

2022-08-09 16:51 UTC, merged