TextField component
ua-dev-front/crossword-master pull request #34
Opened 2022-08-07 14:03 UTC by TeksPeks

Resolves #25

2022-08-07 14:21 UTC, danmysak requested changes

2022-08-07 14:21 UTC, danmysak commented on frontend/src/components/TextField/index.tsx
> +    e.target.style.height = '0px';
1) Достатньо просто `0`, без `px`.
2) Такі от «махінації» бажано пояснювати в коментарях.
3) Цей підхід не спрацює з непорожнім початковим значенням.

2022-08-07 14:21 UTC, danmysak commented on frontend/src/components/TextField/index.tsx
> +      placeholder='TBD'
Винеси літерал у константу.

2022-08-07 14:21 UTC, danmysak commented on frontend/src/components/TextField/styles.scss
> +    width: 200px;
У дизайні наче 198. Але взагалі я б пропонував зробити `100%`, а 198 отримати вже зовнішнім контекстом.

2022-08-07 14:21 UTC, danmysak commented on frontend/src/components/TextField/styles.scss
> +    min-height: 33px;
Ця величина мала б залежати від розміру шрифту.

2022-08-07 14:21 UTC, danmysak commented on frontend/src/components/TextField/styles.scss
> +    border: none;
Щоб контент не стрибав при зміні isEditable, зроби рамку в обох режимах однопіксельною, просто тут — прозорою.

2022-08-07 14:21 UTC, danmysak commented on frontend/src/components/TextField/styles.scss
> +    overflow: hidden;
Навіщо це?

2022-08-07 14:21 UTC, danmysak commented on frontend/src/components/TextField/styles.scss
> +        height: 33px;
Див. зауваження до `min-height`.

2022-08-08 19:39 UTC, TeksPeks commented on frontend/src/components/TextField/styles.scss
> +    min-height: 33px;
Висота тепер контролюється тільки в js

2022-08-08 19:39 UTC, TeksPeks commented on frontend/src/components/TextField/styles.scss
> +        height: 33px;
Висота тепер контролюється тільки в js

2022-08-08 19:44 UTC, TeksPeks commented on frontend/src/components/TextField/styles.scss
> +    overflow: hidden;
Спочатку я додав це, тому що я не правильно виставляв висоту в джсі, але це потрібно щоб в хромі правильно працював авторесайз (в firefox і без цього працює).

2022-08-09 10:43 UTC, danmysak commented on frontend/src/App.tsx
> +  );
Значення `null` у тебе не є теоретично досяжним.

2022-08-09 10:43 UTC, danmysak commented on frontend/src/components/TextField/styles.scss
> +    border-radius: 2px;
Чому забрав `overflow-wrap: break-word`?

2022-08-09 10:43 UTC, danmysak commented on frontend/src/components/TextField/index.tsx
> +  const placeholder = 'TBD';
Ага, тільки великими літерами і на початку файлу.

2022-08-09 10:43 UTC, danmysak commented on frontend/src/components/TextField/styles.scss
> +    width: 100%;
Чому забрав `box-sizing: border-box`?

2022-08-09 10:43 UTC, danmysak commented on frontend/src/components/TextField/styles.scss
> +    overflow: hidden;
Допиши це в коментарі, і включи посилання на джерело в інтернеті, яке засвідчує цю проблему.

2022-08-09 11:29 UTC, danmysak requested changes

2022-08-09 11:29 UTC, danmysak commented on frontend/src/components/TextField/index.tsx
> +    if (isEditable && textareaRef.current) setHeight(textareaRef.current);
Фігурні лапки, окремий рядок.

2022-08-09 16:43 UTC, TeksPeks commented on frontend/src/components/TextField/styles.scss
> +    border-radius: 2px;
повернув

2022-08-09 16:43 UTC, TeksPeks commented on frontend/src/components/TextField/styles.scss
> +    width: 100%;
він не потрібен

2022-08-09 16:45 UTC, TeksPeks commented on frontend/src/components/TextField/index.tsx
> +      parseInt(elementStyles.paddingBottom);
`element.scrollHeight = contentHeight + padding`
Якщо `box-sizing` стоїть `content-box`, то `height = contentHeight`, тобто треба прибрати `padding`, якщо стоїть `border-box`, то `height =  contentHeight + padding + border`, тобто треба додати ще `border`. Я не думаю що тут можно обійтися без парсингу стилів. 
Плюс мені потрібен padding який є, не грає ролі звідки він

2022-08-09 16:58 UTC, TeksPeks commented on frontend/src/components/TextField/styles.scss
> +    overflow: hidden;
Єдина схожа проблема яку я знайшов [тут](https://stackoverflow.com/questions/31968803/issues-with-textareas-scrollheight-increasing-inconsistently), але там є одна відповідь де просто код який працює, без пояснень що саме вирішує проблему.

2022-08-09 17:21 UTC, danmysak commented on frontend/src/components/TextField/styles.scss
> +    overflow: hidden;
Усе ще потрібен коментар.

2022-08-09 17:21 UTC, danmysak commented on frontend/src/App.tsx
> +  );
Прибрати `| null`.

2022-08-09 17:29 UTC, danmysak commented on frontend/src/components/TextField/styles.scss
> +    width: 100%;
Потрібен :-)

2022-08-09 17:30 UTC, danmysak commented on frontend/src/components/TextField/index.tsx
> +    // Set height to zero to get real height of content, instead of strictly set height
Онови ще другий рядок — що було б, якби не присвоєння нуля.

2022-08-09 17:30 UTC, danmysak commented on frontend/src/components/TextField/index.tsx
> +      parseInt(elementStyles.paddingBottom);
Усе ж таки слід обійтися.

2022-08-09 17:30 UTC, danmysak requested changes
Прокоментував у старих обговореннях.

2022-08-10 18:26 UTC, TeksPeks commented on frontend/src/components/TextField/styles.scss
> +    overflow: hidden;
Додав коментарю Я зрозумів чому неправильно працював авторесайз без `overflow: hidden`, але не зрозуміло чому у firefox і без нього працює

2022-08-10 18:26 UTC, TeksPeks commented on frontend/src/components/TextField/index.tsx
> +    // Set height to zero to get real height of content, instead of strictly set height
Оновив, але не впевнений чи правильно

2022-08-11 12:45 UTC, danmysak commented on frontend/src/App.tsx
> +  const [textFieldValue, setTextFieldValue] = useState<string>(
`<string>` тепер зайве (виводиться автоматично).

2022-08-11 12:45 UTC, danmysak commented on frontend/src/components/TextField/index.tsx
> +    // Set height to zero to get real height of content, instead of strictly set height
Хай буде. Єдине — `less lines` → `fewer lines`.

2022-08-11 12:47 UTC, danmysak requested changes
Лишається два коментарі.

2022-08-11 17:03 UTC, danmysak approved these changes

2022-08-13 10:41 UTC, Fybex requested changes

2022-08-13 10:41 UTC, Fybex commented on frontend/src/App.tsx
> +          onChange={(val) => setTextFieldValue(val)}
`value`, без скорочень

2022-08-13 10:41 UTC, Fybex commented on frontend/src/App.tsx
> +        <TextField content={textFieldValue ?? ''} />
`textFieldValue` завжди `string`, тому `?? ''` не потрібно

2022-08-13 10:41 UTC, Fybex commented on frontend/src/App.tsx
> +          content={textFieldValue ?? ''}
`textFieldValue` завжди `string`, тому `?? ''` не потрібно

2022-08-13 10:41 UTC, Fybex commented on frontend/src/components/TextField/styles.scss
> +
чому тут пуста лінія? 🤔

2022-08-13 10:41 UTC, Fybex commented on frontend/src/components/TextField/index.tsx
> +      onChange={(e) => onChange?.(e.target.value)}
`e` -> `event`

2022-08-13 10:41 UTC, Fybex commented on frontend/src/App.tsx
> +import TextField from './components/TextField';
Не впевнений, але чи не повинні у нас бути спочатку компоненти за абеткою, потім типи та іконки, чи це не ділиться на типи та повинно бути за єдиною абеткою 🤔

2022-08-13 11:59 UTC, danmysak commented on frontend/src/App.tsx
> +import TextField from './components/TextField';
Мені перший (тематичний) варіант теж більше до вподоби.

2022-08-13 13:01 UTC, TeksPeks commented on frontend/src/components/TextField/styles.scss
> +
Розділяє стилі фонту та інші.

2022-08-13 13:05 UTC, Fybex approved these changes

2022-08-13 13:06 UTC, merged