Question panels
ua-dev-front/crossword-master pull request #35
Opened 2022-08-11 06:26 UTC by TeksPeks

Fixes #26

2022-08-11 17:48 UTC, danmysak requested changes

2022-08-11 17:48 UTC, danmysak commented on frontend/src/styles/index.scss
>  :root {
Виправити візуальні дрібниці: відступ чисел, лівий кінець лінії, вертикальний відступ лінії.

2022-08-13 12:16 UTC, TeksPeks commented on frontend/src/styles/index.scss
>  :root {
Для чисел я задав ширину в пікселях, і зробив, щоб вони оверфловили вліво. Я не розумію як для одно- і двоцифрових чисел зробити різний відступ, може тільки в джс задати їм різні класи.

2022-08-13 13:26 UTC, danmysak commented on frontend/src/styles/index.scss
>  :root {
Саме так: різні класи. Також текст під лінією все ще на пару пікселів нижче, ніж має бути.

2022-08-13 14:05 UTC, danmysak requested changes

2022-08-13 14:05 UTC, danmysak commented on frontend/src/components/QuestionPanel/index.tsx
> +  isEditable: boolean;
Додай ще, мабуть, анімацію при переході між редаговним і нередаговним варіантами (це ж стосується і самого текстового поля).

2022-08-13 14:05 UTC, danmysak commented on frontend/src/components/TextField/styles.scss
> +    }
Див. зауваження вище.

2022-08-13 17:01 UTC, TeksPeks commented on frontend/src/App.tsx
> +    setQuestions(newQuestions);
мені здається що state не можно міняти мапом

2022-08-13 17:02 UTC, TeksPeks commented on frontend/src/App.tsx
> +export type Question = {
більше ніде не використовується

2022-08-13 17:02 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/index.tsx
> +    <div className={classes}>
`section`?

2022-08-13 17:03 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/styles.scss
> +        direction: rtl;
не потрібно

2022-08-13 17:03 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/styles.scss
> +        width: 11px;
прибрав

2022-08-13 17:03 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/styles.scss
> +        flex-basis: auto;
прибрав

2022-08-13 17:03 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/styles.scss
> +        flex-basis: 90%;
щоб у всіх полів була однакова ширина

2022-08-13 17:04 UTC, TeksPeks commented on frontend/src/components/TextField/styles.scss
> +    position: relative;
бордер який на нередагованних панелях відносно до цього positioned

2022-08-13 17:05 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/styles.scss
> +        line-height: 21px;
додав змінну у текстовому полі яка може служити як фолбек, і переписую її тут

2022-08-13 17:55 UTC, danmysak requested changes

2022-08-13 17:55 UTC, danmysak commented on frontend/src/components/QuestionPanel/index.tsx
> +    isEditable && 'question-panel_editable',
Використай змінну.

2022-08-13 17:55 UTC, danmysak commented on frontend/src/components/QuestionPanel/index.tsx
> +    <div className={classes}>
А всередині — `article`.

2022-08-14 17:48 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/index.tsx
> +    isEditable && 'question-panel_editable',
використав. використав її і в класах, які прямо в jsx

2022-08-14 17:50 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/styles.scss
> +                    &::after {
Зробив з `<hr />`, відцентрував відносно країв панелі, і задав ширину у пікселях, бо зараз все в панелі задано в пікселях.

2022-08-14 17:50 UTC, TeksPeks commented on frontend/src/components/TextField/styles.scss
> +    position: relative;
перемістив у `question-panel__item`

2022-08-14 17:51 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/styles.scss
> +        flex-basis: 90%;
задав у пікселях

2022-08-14 17:51 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/styles.scss
> +        line-height: 21px;
додав глобальну змінну

2022-08-14 17:52 UTC, TeksPeks commented on frontend/src/App.tsx
> +export type Question = {
перемістив у `QuestionPanel`

2022-08-15 15:02 UTC, danmysak requested changes

2022-08-15 15:02 UTC, danmysak commented on frontend/src/styles/index.scss
> +  --transition-duration: 2s;
Забув повернути початкове значення?

2022-08-15 15:02 UTC, danmysak commented on frontend/src/styles/index.scss
> +  --question-panel-line-height: 21px;
Це має бути `--text-field-...`, а не `--question-panel-...`: текстові поля можна теоретично використовувати і поза панеллю, але не навпаки.

2022-08-15 15:17 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/styles.scss
> +        padding-top: 7px;
щоб індекс був вертикально на рівні першого рядку текстового поля 6px padding + 1px border

2022-08-15 15:21 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/styles.scss
> +        align-items: flex-start;
Я взагалі поміняв, тому що у firefox індекси знизу отраплялись, з `first baseline`, проблема залишилась

2022-08-15 15:59 UTC, danmysak commented on frontend/src/components/QuestionPanel/styles.scss
> +        padding-top: 7px;
Не вбачаєш дублювання?

2022-08-15 16:00 UTC, danmysak commented on frontend/src/components/QuestionPanel/styles.scss
> +        align-items: flex-start;
А, так, для `textarea` це дійсно не має працювати.

2022-08-17 06:48 UTC, TeksPeks commented on frontend/src/components/TextField/styles.scss
> +    padding: 6px;
мені здається, що не потрібно. більше ніде не використовується

2022-08-17 06:53 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/styles.scss
> +        transition: border-color var(--transition-duration) var(--transition-function);
додав, але анімація на `TextField` не працює, напевно тому, що тег міняється і новий дом елемент зразу зі зміненим класом отрапляється. Я намагався пофіксити, але не виходить, може у вас є ідея як це зробити?

2022-08-17 07:10 UTC, danmysak commented on frontend/src/components/QuestionPanel/index.tsx
> +          {index !== 0 && <hr className={`${className}__item-divider`} />}
Оформ це за зразком https://github.com/ua-dev-front/crossword-master/blob/main/frontend/src/components/Label/index.tsx#L18

2022-08-17 07:10 UTC, danmysak commented on frontend/src/components/QuestionPanel/index.tsx
> +              }-digit`}
До речі, просто `single-digit` і `multiple-digit` — це не за BEM’ом. Мають бути названі як модифікатори.

2022-08-17 07:10 UTC, danmysak commented on frontend/src/components/QuestionPanel/index.tsx
> +            />
Цікавий підхід, але так у тебе числа, наприклад, не виділені напівжирним. Плюс можуть бути несподівані перекриття падингів. Усе ж таки я б повернувся до старого варіанта.

2022-08-17 07:10 UTC, danmysak commented on frontend/src/components/TextField/index.tsx
> +  className?: string;
Після решти змін, імовірно, буде зайвим.

2022-08-17 07:10 UTC, danmysak commented on frontend/src/components/QuestionPanel/styles.scss
> +        width: 168px;
77% — така сама «магічна величина», як і 168px.

2022-08-17 07:12 UTC, danmysak commented on frontend/src/components/QuestionPanel/styles.scss
> +        transition: border-color var(--transition-duration) var(--transition-function);
Рамка, певно, має бути не в самого textarea, а у додаткового зовнішнього контейнера, який міститиме то div, то textarea.

2022-08-17 07:12 UTC, danmysak commented on frontend/src/components/TextField/styles.scss
> +    padding: 6px;
Має використовуватися для обрахунку ширини пунктирної лінії.

2022-08-17 07:14 UTC, danmysak requested changes
Див. коментарі.

2022-08-18 18:48 UTC, TeksPeks commented on frontend/src/components/TextField/index.tsx
> +  className?: string;
все ще використовується

2022-08-18 20:30 UTC, Fybex requested changes

2022-08-18 20:30 UTC, Fybex commented on frontend/src/components/QuestionPanel/index.tsx
> +  onChange?: (value: string, index: number) => void;
Це, напевно, суб‘єктивна річ, але у меня б був порядок Props згідно їхньою важливістю
```suggestion
  questions: Question[];
  isEditable: boolean;
  color: QuestionPanelColor;
  onChange?: (value: string, index: number) => void;
```

2022-08-18 20:30 UTC, Fybex commented on frontend/src/components/QuestionPanel/styles.scss
> +    --item-question-width: 198px;
У нас, в інших файлах стилів, між властивостями й  змінними порожня лінія 
```suggestion
    --item-question-width: 198px;

```

2022-08-18 20:30 UTC, Fybex commented on frontend/src/components/QuestionPanel/styles.scss
> +
Не розумію для чого відділяти `box-shadow` від інших стилів

2022-08-19 07:26 UTC, danmysak commented on frontend/src/components/QuestionPanel/index.tsx
> +  onChange?: (value: string, index: number) => void;
Згоден із Андрієм.

2022-08-19 09:45 UTC, danmysak requested changes

2022-08-19 09:45 UTC, danmysak commented on frontend/src/components/QuestionPanel/styles.scss
> +    justify-content: space-around;
Навіщо потрібне це правило?

2022-08-19 09:45 UTC, danmysak commented on frontend/src/components/QuestionPanel/styles.scss
> +        position: relative;
А це для чого?

2022-08-19 09:45 UTC, danmysak commented on frontend/src/components/QuestionPanel/styles.scss
> +        margin: 0 calc(100% - (var(--item-question-width) - var(--text-field-padding)));
1) Чому виставляєш `margin`, а не `width`?
2) Ти впевнений, що ця формула правильна?..

2022-08-19 09:45 UTC, danmysak commented on frontend/src/components/TextField/index.tsx
>    onChange?: (value: string) => void;
Так само є сенс впорядкувати за важливістю (тут і в сигнатурі).

2022-08-19 09:45 UTC, danmysak commented on frontend/src/components/TextField/index.tsx
> +    'text-field',
Винеси тоді й тут, мабуть, `text-field` у змінну.

2022-08-19 09:45 UTC, danmysak commented on frontend/src/components/TextField/styles.scss
> +    margin: 0;
Варто прибрати (порушує BEM + навіщо?).

2022-08-19 09:45 UTC, danmysak commented on frontend/src/components/TextField/styles.scss
> +        height: 100%;
Навіщо?

2022-08-19 09:45 UTC, danmysak commented on frontend/src/components/TextField/styles.scss
>          border-color: cl(light-dark);
Мабуть, при фокусуванні/розфокусуванні колір рамки має мінятися миттєво (без анімації) — за аналогією до зміни рамки навколо кнопки і `Tab`у. Чи можна це малою кров’ю реалізувати без шкоди для анімації при зміні редаговності?

2022-08-19 09:45 UTC, danmysak commented on frontend/src/components/QuestionPanel/index.tsx
> +          <hr className={`${className}__item-divider`} key={`divider-${id}`} />
Навіщо префікс `divider-` у властивості `key`?

2022-08-19 16:31 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/index.tsx
> +          <hr className={`${className}__item-divider`} key={`divider-${id}`} />
У `question-panel__item` стоїть `key` просто `id`, це щоб не повторялися `keys`

2022-08-19 16:31 UTC, TeksPeks commented on frontend/src/components/TextField/styles.scss
> +        height: 100%;
забув прибрати

2022-08-19 16:32 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/styles.scss
> +        position: relative;
більше не потрібно

2022-08-19 16:32 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/styles.scss
> +    justify-content: space-around;
не потрібно

2022-08-19 16:32 UTC, TeksPeks commented on frontend/src/components/TextField/styles.scss
>      }
додав `min-height` до `TextField`

2022-08-19 16:36 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/styles.scss
> +        margin: 0 calc(100% - (var(--item-question-width) - var(--text-field-padding)));
1. для `width` виходить складна формула
2. додав ще `border-width` у формулу

2022-08-19 16:37 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/styles.scss
> +    --item-question-width: 198px;
Я не розумію як вони пов'язані

2022-08-19 16:50 UTC, Fybex approved these changes

2022-08-19 16:59 UTC, TeksPeks commented on frontend/src/components/TextField/styles.scss
>          border-color: cl(light-dark);
можно в js додавати класс з `transition`, коли змінюється `isEditable`, і прибирати коли анімація закінчується. інших ідей в мене поки нема

2022-08-19 17:14 UTC, danmysak commented on frontend/src/components/TextField/styles.scss
> +    );
Використати підхід із нерозривним пробілом.

2022-08-19 17:14 UTC, danmysak commented on frontend/src/components/QuestionPanel/index.tsx
> +          <label
Усе ж таки давай спробуємо з `label`, коли поле редаговне.

2022-08-19 17:23 UTC, danmysak requested changes
Див. коментарі.

2022-08-22 19:36 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/styles.scss
> +        margin: 0 calc(100% - (var(--item-question-width) - var(--text-field-padding)));
все ще виставляю `margin`, бо формула простіша. Але тепер вона правильна

2022-08-23 07:23 UTC, danmysak requested changes

2022-08-23 07:23 UTC, danmysak commented on frontend/src/components/QuestionPanel/index.tsx
> +        const inputId = `${id}-question`;
Це не гарантовано унікальний id (у межах проєкту)! Використай, наприклад, https://reactjs.org/docs/hooks-reference.html#useid.

2022-08-23 07:23 UTC, danmysak commented on frontend/src/components/QuestionPanel/styles.scss
> +        flex-shrink: 0;
Це точно потрібно?

2022-08-23 07:23 UTC, danmysak commented on frontend/src/components/QuestionPanel/styles.scss
> +            left: -4px;
Краще все ж `position` динамічно не міняти. Можна обійтися `margin`ом, мабуть?

2022-08-23 07:23 UTC, danmysak commented on frontend/src/components/QuestionPanel/styles.scss
> +        flex-basis: 198px;
Домовилися ж обійтися без дублювання!

2022-08-23 07:23 UTC, danmysak commented on frontend/src/components/QuestionPanel/styles.scss
> +        min-width: 0; // without this line editable TextField takes all the width in panel
Думаю, при правильній розмітці це все ж буде зайвим.

2022-08-23 15:50 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/styles.scss
> +        flex-shrink: 0;
не потрібно, прибрав

2022-08-23 15:53 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/styles.scss
> +            left: -4px;
в дизайні `id` з двума цифрами залазить в `padding` наліво. І якщо використати `margin`, то ширина текстового поля для одно- і двоцифрових чисел буде різна

2022-08-23 16:01 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/styles.scss
> +        min-width: 0; // without this line editable TextField takes all the width in panel
додав `width: 100%` до `text-field__content`, і це виправилось

2022-08-23 17:14 UTC, danmysak commented on frontend/src/components/QuestionPanel/styles.scss
> +        flex-basis: calc(100% - var(--item-id-width));
1) Ці дві властивості фактично дублюють одна одну. В ідеалі хотілося б, щоб ти обійшовся `flex-grow`, яке автоматично виставляє таку ширину, як ти хочеш.
2) Префіксуй назву змінною назвою компонента (щоб уникнути потенційного конфлікту імен).

2022-08-23 17:14 UTC, danmysak commented on frontend/src/components/QuestionPanel/styles.scss
> +            left: -4px;
Вистав просто різний `padding` при однаковому `width` (і `box-sizing: border-box`).

2022-08-23 17:15 UTC, danmysak requested changes
Новий коментар + див. незакриті старі.

2022-08-24 20:20 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/styles.scss
> +            left: -4px;
також зробив для панелей `padding-left` 5 пікселів замість 12, щоб у двоцифрових чисел був відступ зліва як у дизайні

2022-08-24 20:30 UTC, TeksPeks commented on frontend/src/components/TextField/styles.scss
>          border-color: cl(light-dark);
зробив як писав вище.

2022-08-25 05:27 UTC, danmysak commented on frontend/src/components/TextField/styles.scss
>          border-color: cl(light-dark);
При переході від редаговного до нередаговного рамка зникає миттєво (мала з анімацією).
Крім того, зберігається анімація при фокусуванні, якщо встигнути сфокусуватися на полі одразу після завантаження сторінки (легше тестувати зі збільшеним `--transition-duration`).

2022-08-25 05:35 UTC, danmysak requested changes
Лишаються проблеми з анімацією (див. коментар).

2022-08-25 08:08 UTC, danmysak commented on frontend/src/components/QuestionPanel/styles.scss
> +@import '../../styles/functions.scss';
`'styles/functions.scss'`

2022-08-25 17:13 UTC, danmysak commented on frontend/src/components/TextField/index.tsx
> +  const forceUpdate = useCallback(() => updateState({}), []);
Винести в окремий хук.

2022-08-25 17:13 UTC, danmysak commented on frontend/src/components/TextField/index.tsx
> +  }, [isEditable]);
Теж винести в окремий хук.

2022-08-25 17:13 UTC, danmysak commented on frontend/src/components/TextField/styles.scss
>          border-color: cl(light-dark);
Існують сценарії, коли підхід не працює.

2022-08-25 17:14 UTC, danmysak requested changes
Див. коментарі.

2022-08-27 14:44 UTC, TeksPeks commented on frontend/src/components/TextField/index.tsx
> +  const forceUpdate = useCallback(() => updateState({}), []);
більше не використовується

2022-08-27 14:52 UTC, danmysak requested changes

2022-08-27 14:52 UTC, danmysak commented on frontend/src/hooks/usePrevValue.js
> +export default usePrevValue;
`.js` → `.ts` + типізуй.

2022-08-27 14:52 UTC, danmysak commented on frontend/src/components/TextField/index.tsx
> +          onFocus={() => setIsTransitioning(false)}
Це точно потрібно?

2022-08-27 14:52 UTC, danmysak commented on frontend/src/components/TextField/index.tsx
> +    (prevIsEditable !== isEditable || isTransitioning) &&
А тут не вистачить просто `isTransitioning` без необхідності в хуку `usePrevValue`?

2022-08-27 14:52 UTC, danmysak commented on frontend/src/hooks/usePrevValue.js
> +const usePrevValue = (value) => {
`usePreviousValue`

2022-08-27 16:17 UTC, danmysak commented on frontend/src/styles/index.scss
>    --transition-function: ease-in-out;
Додай також порожній рядок, що розділяє групи змінних.

2022-08-27 16:30 UTC, TeksPeks commented on frontend/src/components/TextField/index.tsx
> +          onFocus={() => setIsTransitioning(false)}
без цього анімація продовжиться коли буде перехід до редагованого стану і юзер сфокусується на текстовому полі

2022-08-27 16:32 UTC, TeksPeks commented on frontend/src/components/TextField/index.tsx
> +    (prevIsEditable !== isEditable || isTransitioning) &&
треба цей класс додавати на тому ж рендері коли і `&_editable`, щоб був transition

2022-08-27 16:57 UTC, danmysak requested changes

2022-08-27 16:57 UTC, danmysak commented on frontend/src/hooks/usePreviousValue.ts
> +const usePreviousValue = (value: unknown) => {
Використай генерики (generics) і задай тип результату.

2022-08-28 18:23 UTC, danmysak requested changes

2022-08-28 18:23 UTC, danmysak commented on frontend/src/hooks/usePreviousValue.ts
> +const usePreviousValue = <Value>(value: Value): Value => {
1) Тоді вже мало б бути не `Value`, а `Type`, але типи стандартно позначаються одиночними літерами: `T`, `S`, `V` тощо. Основний варіант — `T`.

2) Оформ усе простіше — як `export default function usePreviousValue<T>...`.

2022-08-29 04:41 UTC, danmysak approved these changes

2022-08-29 16:36 UTC, Fybex requested changes

2022-08-29 16:36 UTC, Fybex commented on frontend/src/components/QuestionPanel/index.tsx
> +          `${className}__item-id_${
Повторення рядка 41, можна винести у віддільну змінну

2022-08-29 16:36 UTC, Fybex commented on frontend/src/components/QuestionPanel/index.tsx
> +        const inputId = useId();
На мою думку, спочатку повинні йти хуки, потім змінні, в цьому випадку змінні класів

2022-08-29 16:36 UTC, Fybex commented on frontend/src/components/QuestionPanel/index.tsx
> +              className={`${className}__item-question`}
Часткове повторення рядку 55

2022-08-29 16:36 UTC, Fybex commented on frontend/src/components/QuestionPanel/styles.scss
> +    &_editable {
Чому цей модифікатор розташовано відділено від інших двох?

2022-08-29 16:36 UTC, Fybex commented on frontend/src/components/TextField/index.tsx
>    onChange?: (value: string) => void;
функції йдуть після змінних

2022-08-29 16:36 UTC, Fybex commented on frontend/src/components/TextField/index.tsx
> +  const baseClassName = 'text-field';
нижче хуків, на мою думку

2022-08-29 16:36 UTC, Fybex commented on frontend/src/components/TextField/index.tsx
> +  }, [isEditable]);
Можна інлайново
```suggestion
  useEffect(() => setIsTransitioning(true), [isEditable]);
```

2022-08-29 16:36 UTC, Fybex commented on frontend/src/components/TextField/index.tsx
> +          id={inputId}
`key` та `id` доволі схожі за логікою речі, в деяких місцях спочкатку `className`, потім `key`, тут навпаки

В інших компонентах у нас `key` попереду. Треба прийти до одного стилю 👍

2022-08-29 16:36 UTC, Fybex commented on frontend/src/components/TextField/index.tsx
> +          onChange={(event) => onChange?.(event.target.value)}
Суб'єктивно
```suggestion
          onChange={({ target: { value } }) => onChange?.(value)}
```

2022-08-29 16:36 UTC, Fybex commented on frontend/src/components/TextField/styles.scss
> +    }
Вище за модифікатори, у нас, наче, всюди нижче

2022-08-29 16:36 UTC, Fybex commented on frontend/src/components/TextField/styles.scss
> +    }
відділено від іншого модифікатора

2022-08-29 16:58 UTC, danmysak commented on frontend/src/components/TextField/index.tsx
> +  }, [isEditable]);
Оскільки результат, який повертає функція з useEffect, має значення, краще не треба.

2022-08-29 16:59 UTC, danmysak commented on frontend/src/components/TextField/styles.scss
> +    }
(Цього коментаря не зрозумів.)

2022-08-29 17:00 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/index.tsx
> +        const inputId = useId();
А мені здається що константи мають бути наверху

2022-08-29 17:01 UTC, TeksPeks commented on frontend/src/components/TextField/styles.scss
> +    }
Як мінімум у `Cell` модифікатори нижче

2022-08-29 17:17 UTC, danmysak commented on frontend/src/components/QuestionPanel/index.tsx
> +        const inputId = useId();
Хук не може бути в цьому місці в принципі.

2022-08-30 19:01 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/index.tsx
> +              className={`${className}__item-question`}
якщо виносити в змінну то забагато змінних виходить

2022-08-30 19:01 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/styles.scss
> +    &_editable {
перемістив до інших

2022-08-30 19:02 UTC, TeksPeks commented on frontend/src/components/TextField/index.tsx
>    onChange?: (value: string) => void;
вона важливіша за змінні під нею

2022-08-30 19:02 UTC, TeksPeks commented on frontend/src/components/TextField/index.tsx
> +          id={inputId}
перемістив `key` перед `className`ом

2022-08-30 19:04 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/index.tsx
> +        const inputId = useId();
перемістив хук в початок компонента

2022-08-30 19:06 UTC, Fybex approved these changes

2022-08-31 05:36 UTC, danmysak approved these changes

2022-08-31 06:22 UTC, merged