Dialog
ua-dev-front/crossword-master pull request #38
Opened 2022-08-13 11:07 UTC by Fybex

Fixes #32

2022-08-13 14:23 UTC, danmysak requested changes

2022-08-13 14:23 UTC, danmysak commented on frontend/src/components/Dialog/index.tsx
> +      <Label content={label} size={LabelSize.Large} />
1) Розмір шрифту не той — додай у `LabelSize` ще `ExtraLarge`.
2) Додай можливість у `Label` вставляти контент із перенесенням рядка (`\n`).

2022-08-13 14:23 UTC, danmysak commented on frontend/src/App.tsx
> +        label='Questions & answers will be lost. Continue?'
`\nContinue?` (див. коментар нижче).

2022-08-13 14:26 UTC, Fybex commented on frontend/src/components/Dialog/index.tsx
> +      <Label content={label} size={LabelSize.Large} />
Може краще  нинішнє значення`Large` перейменувати в `Medium`?

2022-08-13 14:55 UTC, danmysak commented on frontend/src/components/Dialog/index.tsx
> +      <Label content={label} size={LabelSize.Large} />
Можна.

2022-08-13 16:49 UTC, danmysak requested changes

2022-08-13 16:49 UTC, danmysak commented on frontend/src/components/Label/index.tsx
> +      {content.split('\\n').map((element) => (
Чому два слеші?

2022-08-13 16:49 UTC, danmysak commented on frontend/src/components/Label/index.tsx
> +          <br />
Після останнього не має бути.

2022-08-13 16:49 UTC, danmysak commented on frontend/src/components/Label/styles.scss
> +
Зайвий порожній рядок?

2022-08-13 17:00 UTC, Fybex commented on frontend/src/components/Label/index.tsx
> +      {content.split('\\n').map((element) => (
Character | Description
-- | --
\ | Marks the next character as either a special character or a literal. For example:n matches the character n. "\n" matches a newline character.The sequence \\ matches \ and \( matches (.

2022-08-13 17:33 UTC, danmysak approved these changes

2022-08-13 17:33 UTC, danmysak commented on frontend/src/components/Label/index.tsx
> +    const splitedContent = content.split('\\n');
1) `splitContent`
2) Один слеш.

2022-08-14 15:27 UTC, TeksPeks approved these changes

2022-08-16 18:54 UTC, merged