Favicon
ua-dev-front/crossword-master pull request #4
Opened 2022-06-16 17:01 UTC by Fybex

Fixes #3

2022-06-16 18:07 UTC, danmysak requested changes

2022-06-16 18:07 UTC, danmysak commented on frontend/public/index.html
> +    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
Я так розумію, фон для favicon’а взято з інтерфейсу фігми. Але насправді він мав бути прозорим. Чи є можливість зробити favicon прозорим? Якщо ні, то треба подивитися, який фоновий колір виглядатиме краще. Цей конкретний виглядає доволі брудно.

2022-06-18 09:11 UTC, Fybex commented on frontend/public/index.html
> +    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
Без фону з чорною темою має поганий вигляд, тому додав фон, для мене фон виглядає нормально, на який замінити не знаю, просто на білий? 🤔

2022-06-18 17:21 UTC, danmysak requested changes

2022-06-18 17:21 UTC, danmysak commented on frontend/public/index.html
> +    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
Дизайн оновлено.

2022-06-20 11:29 UTC, danmysak requested changes

2022-06-20 11:29 UTC, danmysak commented on frontend/public/index.html
> +    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
Але тепер навколо чорної рамки — непрозоро (наприклад, у файлі frontend/public/favicon-32x32.png).

2022-06-20 11:29 UTC, danmysak commented on frontend/public/browserconfig.xml
> +            <square150x150logo src="/mstile-150x150.png"/>
А точно, наприклад, у файлі frontend/public/mstile-310x150.png усе правильно? Там розташування піктограми на зображенні навіть несиметричне.

2022-06-22 14:08 UTC, danmysak commented on frontend/public/browserconfig.xml
> +            <square150x150logo src="/mstile-150x150.png"/>
Вирішили ігнорувати.

2022-06-22 14:08 UTC, danmysak approved these changes

2022-06-22 17:26 UTC, merged