Aliases and linter
ua-dev-front/crossword-master pull request #40
Opened 2022-08-13 16:10 UTC by Fybex

Fixes #37 

Вирішив не додавати aliases, вони, як мінімум зараз, не потрібні. Замість них додав`baseUrl`.

Також додав налаштування eslint. Буду радий почути які правила ще слід додати, які виключити. Перед review, потрібно встановити нові dependencies: `npm i`

2022-08-13 17:00 UTC, danmysak requested changes

2022-08-13 17:00 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +            ? { letter: null, number: matrix[row][column]?.number ?? null }
Чому так?

2022-08-13 17:07 UTC, Fybex commented on frontend/src/components/Grid/index.tsx
> +            ? { letter: null, number: matrix[row][column]?.number ?? null }
[eslint[@typescript-eslint/no-non-null-assertion](https://typescript-eslint.io/rules/no-non-null-assertion)](https://typescript-eslint.io/rules/no-non-null-assertion/)

2022-08-13 17:08 UTC, Fybex commented on frontend/src/components/Cell/index.tsx
> +}
забув перенести в #33

2022-08-14 05:01 UTC, danmysak approved these changes

2022-08-14 13:37 UTC, TeksPeks approved these changes

2022-08-14 13:37 UTC, merged