Firefox focus outline + unnecessary border on focus button fix
ua-dev-front/crossword-master pull request #41
Opened 2022-08-13 16:41 UTC by Fybex

Fixes #39

2022-08-13 16:53 UTC, danmysak requested changes

2022-08-13 16:53 UTC, danmysak commented on frontend/src/components/Button/styles.scss
> +        outline: 2px solid cl(selected);
Тепер у тебе кнопка при виділення зсувається (її розміри міняються).
А взагалі зауваж, що початкова проблема була не лише у файрфоксі, але і в інших браузерах. Просто показав, як виглядає конкретно в ФФ.

2022-08-16 19:24 UTC, Fybex commented on frontend/src/components/Button/styles.scss
> +        outline: 2px solid cl(selected);
Протестував в хромі, ФФ, сафарі. Зараз кнопка не зсувається, додаткових обведень немає 👍

2022-08-17 06:38 UTC, danmysak requested changes

2022-08-17 06:38 UTC, danmysak commented on frontend/src/components/Button/styles.scss
> +    margin: 0;
Такий підхід порушує BEM: https://en.bem.info/methodology/css/#external-geometry-and-positioning.

2022-08-18 19:50 UTC, Fybex commented on frontend/src/components/Button/styles.scss
> +    margin: 0;
Додав `span.button__label`, як обговорили на уроці

2022-08-19 07:19 UTC, danmysak approved these changes

2022-08-25 16:57 UTC, TeksPeks approved these changes

2022-08-25 17:27 UTC, merged