Loader
ua-dev-front/crossword-master pull request #44
Opened 2022-08-25 07:58 UTC by Fybex

Fixes #36

2022-08-25 08:22 UTC, danmysak requested changes

2022-08-25 08:22 UTC, danmysak commented on frontend/src/components/Loader/index.tsx
> +import './style.scss';
`styles.scss`

2022-08-25 08:22 UTC, danmysak commented on frontend/src/components/Loader/index.tsx
> +  isLoading: boolean;
Прокоментуй, що це необхідно для анімації.

2022-08-25 08:22 UTC, danmysak commented on frontend/src/components/Loader/style.scss
> +    height: 100%;
1) `position: fixed` точно не підходить, бо нам потрібно вирівнювати не щодо екрану, а відносно контейнера з грідом.
2) Встановлення позиції тут суперечить BEM. Я б у цьому компоненті   встановив лише мінімальний `padding: ...` (для гарного відображення окремо від контексту) та `box-sizing: border-box`, а позицію та розміри встановлював із контексту ззовні.

2022-08-25 08:22 UTC, danmysak commented on frontend/src/components/Loader/style.scss
> +}
Бракує `border-radius`, як у гріда (зупинилися на тому, що це буде глобальна змінна).

2022-08-25 08:22 UTC, danmysak commented on frontend/src/components/Loader/style.scss
> +    z-index: 10;
Для абстрактного компонента так робити недобре.
Після врахування коментаря вище, думаю, відпаде.

2022-08-25 08:22 UTC, danmysak commented on frontend/src/components/Loader/style.scss
> +        font-weight: 32px;
По-перше, `line-height`. Але по-друге, мабуть, це тут взагалі зайве?

2022-08-25 08:22 UTC, danmysak commented on frontend/src/components/Loader/style.scss
> +        color: cl(light);
Забув контур і тінь. А взагалі вони такі самі, як і в заголовку (хоч розмір різний). Є сенс винести в окремий компонент — `TitleLabel` абощо.

2022-08-27 16:02 UTC, Fybex commented on frontend/src/components/Loader/style.scss
> +        color: cl(light);
Створив компонент `TitleLabel` 👍

2022-08-27 16:06 UTC, Fybex commented on frontend/src/components/Loader/style.scss
> +        font-weight: 32px;
Вирішив залишити `line-height`, наразі він у компоненті `TitleLabel`

2022-08-27 16:07 UTC, Fybex commented on frontend/src/components/Loader/style.scss
> +    height: 100%;
1. Прибрав position
2. Додав `padding: 20px` та `box-sizing: border-box` 👍

2022-08-27 16:43 UTC, danmysak requested changes

2022-08-27 16:43 UTC, danmysak commented on frontend/src/App.tsx
> +    return !state;
Інлайново.

2022-08-27 16:43 UTC, danmysak commented on frontend/src/App.tsx
> +          toggleLoading();
Інлайново.

2022-08-27 16:43 UTC, danmysak commented on frontend/src/App.tsx
> +      <Loader label='Solving...' isLoading={isLoading} />
Помісти у штучний контейнер із фіксованими розмірами.

2022-08-27 16:43 UTC, danmysak commented on frontend/src/styles/index.scss
> +  --cell-border-radius: 10px;
Думаю, не завадило б мати порожній рядок, що розділяє групи змінних.

2022-08-27 16:43 UTC, danmysak commented on frontend/src/components/TitleLabel/styles.scss
> +        line-height: 38px;
Звідки ця величина?

2022-08-27 16:43 UTC, danmysak commented on frontend/src/components/TitleLabel/styles.scss
> +    padding: 30px;
`margin`, мабуть, тут допустимий, а ось `padding` має бути властивістю відповідного елемента, а не блока.

2022-08-27 16:43 UTC, danmysak commented on frontend/src/components/Loader/index.tsx
> +  isLoading: boolean; // need to make an animation, shows the loader when true
`is needed to display ...`

2022-08-27 16:43 UTC, danmysak commented on frontend/src/components/TitleLabel/index.tsx
> +    <h1 className={`title-label title-label_${size} ${className}`}>
Використай `classnames` (ну і винеси у змінну назву класу, якщо вже у `Loader`і винесено).

2022-08-27 16:43 UTC, danmysak commented on frontend/src/components/Loader/index.tsx
> +  const classes = classnames(className, !isLoading && `${className}_hidden`);
Нема сенсу у проміжній змінній `classes`.

2022-08-27 16:43 UTC, danmysak commented on frontend/src/components/TitleLabel/index.tsx
> +    <h1 className={`title-label title-label_${size} ${className}`}>
Мабуть, для лоадера `h1` буде недоречно. Може, передавати тег як параметр?

2022-08-27 16:52 UTC, Fybex commented on frontend/src/components/TitleLabel/styles.scss
> +        line-height: 38px;
![image](https://user-images.githubusercontent.com/46112160/187040076-3e7d3080-0d12-4251-8312-6cb13e5d675b.png)

2022-08-27 17:16 UTC, danmysak requested changes

2022-08-27 17:16 UTC, danmysak commented on frontend/src/components/TitleLabel/index.tsx
> +  tag: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
`'h1' | 'p'`

2022-08-27 17:16 UTC, danmysak commented on frontend/src/components/Loader/index.tsx
> +  isLoading: boolean; // is needed to make the animation on the loader appear and disappear
`is needed to display the animation, shows the loader when true`

2022-08-27 17:16 UTC, danmysak commented on frontend/src/components/Loader/index.tsx
> +      <TitleLabel content={label} size={TitleLabelSize.Small} tag='h2' />
`'p'`

2022-08-27 17:19 UTC, danmysak approved these changes

2022-08-31 06:14 UTC, TeksPeks commented on frontend/src/components/Loader/styles.scss
> +    padding: 20px;
А навіщо це потрібно?

2022-08-31 16:39 UTC, Fybex commented on frontend/src/components/Loader/styles.scss
> +    padding: 20px;
https://github.com/ua-dev-front/crossword-master/pull/44#discussion_r954650450

2022-08-31 16:54 UTC, TeksPeks approved these changes

2022-08-31 16:55 UTC, merged