Redux setup
ua-dev-front/crossword-master pull request #52
Opened 2022-09-02 07:31 UTC by TeksPeks

Fixes #49

2022-09-02 08:05 UTC, danmysak requested changes

2022-09-02 08:05 UTC, danmysak commented on frontend/src/store/index.ts
> +export default store;
У цьому PR ти не лише засетапив Redux, а і втілив певну структуру слайсів, яка, на мій погляд, не є цілком відповідною вимогам проєкту. Щоб зрозуміти, які мають бути слайси, слід спершу визначитися з екшенами. У цьому ж PR пропоную лишити власне сетап — без припущень щодо розбивки на слайси і без логіки редюсерів.

2022-09-02 15:25 UTC, TeksPeks commented on frontend/src/components/Grid/index.tsx
> +  EnterQuestions = 'enterQuestions',
так як тепер тільки сетап то зробив як було

2022-09-02 15:25 UTC, TeksPeks commented on frontend/src/components/QuestionPanel/index.tsx
> +  };
так як тепер тільки сетап то зробив як було

2022-09-02 16:15 UTC, danmysak requested changes

2022-09-02 16:15 UTC, danmysak commented on frontend/src/index.tsx
>  import './styles/index.scss';
Стилі — в кінці.

2022-09-02 16:15 UTC, danmysak commented on frontend/src/components/App/index.tsx
Зміни в цьому файлі зайві.

2022-09-04 11:45 UTC, TeksPeks commented on frontend/src/components/App/index.tsx
але `textFieldValue` прибрав, бо воно ніде не використовується

2022-09-04 12:02 UTC, danmysak approved these changes

2022-09-04 16:35 UTC, Fybex approved these changes

2022-09-04 16:47 UTC, merged