Move actions to code
ua-dev-front/crossword-master pull request #54
Opened 2022-09-08 14:22 UTC by TeksPeks

Fixes #53

2022-09-08 14:59 UTC, danmysak requested changes

2022-09-08 14:59 UTC, danmysak commented on frontend/src/store/index.ts
> +type CellAtionPayload = {
«`Ation`»

2022-09-08 14:59 UTC, danmysak commented on frontend/src/store/index.ts
> +  };
Винеси це як окремий тип, щоб не дублювати.

2022-09-08 14:59 UTC, danmysak commented on frontend/src/store/index.ts
> +type InitialState = {
Чому `Initial`?

2022-09-08 14:59 UTC, danmysak commented on frontend/src/store/index.ts
> +  grid: [],
Це не так.

2022-09-08 14:59 UTC, danmysak commented on frontend/src/store/index.ts
> +const generalSlice = createSlice({
А без слайсів тоді обійтися не можна?

2022-09-08 14:59 UTC, danmysak commented on frontend/src/store/index.ts
> +    fillCell: (state, action: PayloadAction<CellAtionPayload>) => {
`state` не має бути типізований?

2022-09-08 14:59 UTC, danmysak commented on frontend/src/store/index.ts
> +      // sets mode to Draw, resets questions and removes letters & numbers from grid.
Тут і нижче — зайва крапка в кінці коментаря (у коментарях вище її немає).

2022-09-12 11:53 UTC, TeksPeks commented on frontend/src/store/index.ts
> +const generalSlice = createSlice({
Можна, але треба буде редюсери і екшени робити по іншому, якщо ми будемо далі слайси використовувати, то можна буде просто звідси перенести в інший слайс редюсер який потрібен, а не переписувати його під слайси.

2022-09-12 15:42 UTC, danmysak requested changes

2022-09-12 15:42 UTC, danmysak commented on frontend/src/store/index.ts
> +type EditQuestionPayload = {
1) Онови ім’я.
2) Експортуй.

2022-09-12 15:42 UTC, danmysak commented on frontend/src/store/index.ts
> +export type Question = {
Експорт зайвий.

2022-09-12 17:51 UTC, TeksPeks commented on frontend/src/store/index.ts
> +  grid: [...Array(10)].map(() => [...Array(10)].map(() => null)),
Виніс розміри у константи в окремий файл

2022-09-12 17:52 UTC, TeksPeks commented on frontend/src/store/index.ts
> +type EditQuestionPayload = {
Оновив.
Не розумію навіщо експортувати?

2022-09-12 17:54 UTC, TeksPeks commented on frontend/src/store/index.ts
> +export enum Mode {
перемістив `Mode` у файл з константами

2022-09-12 18:02 UTC, danmysak commented on frontend/src/appConstants.ts
> +}
Це тип, а не константа. Хай живе у `store/index.ts.`.

2022-09-12 18:02 UTC, danmysak commented on frontend/src/store/index.ts
> +type EditQuestionPayload = {
Цей тип використовується в інтерфейсі взаємодії (у даному випадку — між компонентами та редаксом). Експортувати всі типи, що використовуються в інтерфейсі — правило хорошого тону; наприклад, так споживач інтерфейсу зможе зберегти дані у проміжній змінній.

До речі, я ж ото помилявся, що стан — це внутрішня деталь реалізації редюсера. Відповідно, там, де писав, що експортувати не потрібно, все ж варто експортувати.

2022-09-12 18:05 UTC, danmysak requested changes
Плюс див. окремі коментарі.

2022-09-12 18:05 UTC, danmysak commented on frontend/src/store/index.ts
> +  name: 'everything',
Чому не `general` тоді?

2022-09-12 18:41 UTC, danmysak requested changes
Останнє — експортуй `State`.

2022-09-12 18:45 UTC, danmysak approved these changes

2022-09-14 16:51 UTC, Fybex approved these changes

2022-09-14 16:53 UTC, merged