Endpoints templates
ua-dev-front/crossword-master pull request #6
Opened 2022-06-18 09:55 UTC by Fybex

Fixes #5

2022-06-18 17:52 UTC, danmysak requested changes

2022-06-18 17:52 UTC, danmysak commented on backend/app.py
> +from flask import Flask, request, jsonify
Абетка.

2022-06-18 17:52 UTC, danmysak commented on backend/app.py
>  app = Flask(__name__)
Порожній рядок над даним.

2022-06-18 17:52 UTC, danmysak commented on backend/app.py
>      return 'Test successful'
Прибрати.

2022-06-18 17:52 UTC, danmysak commented on backend/app.py
> +def generate(data: dict[str, list[list[int]]]) -> dict[str, dict[list[dict[str, str | int | list[int]]]] | None]:
Використай тут і нижче [TypedDict](https://peps.python.org/pep-0589/).

2022-06-19 16:04 UTC, Fybex commented on backend/app.py
> +def generate(data: dict[str, list[list[int]]]) -> dict[str, dict[list[dict[str, str | int | list[int]]]] | None]:
Використав 👍🏿 . Також створив окремий файл `types.py`

2022-06-19 20:07 UTC, TeksPeks requested changes
При запуску `flask run`
виникає помилка:
```
File "C:\Work\crossword-master\backend\app.py", line 17, in <module>
    def generate(data: GenerateData) -> GenerateResponse:
NameError: name 'GenerateData' is not defined
```

2022-06-20 06:33 UTC, TeksPeks approved these changes

2022-06-20 11:54 UTC, danmysak requested changes

2022-06-20 11:54 UTC, danmysak commented on backend/app.py
> +def solve(data: SolveData) -> SolveAnswers:
Чому Generate**Response**, але Solve**Answers**?

2022-06-20 11:54 UTC, danmysak commented on backend/app.py
> +from app_types import *
Універсальний імпорт (`*`) без потреби не використовуємо.

2022-06-20 11:54 UTC, danmysak commented on backend/app.py
> +from flask import Flask, jsonify, request
Потрібен порожній між різними типами імпортів (у даному випадку чужа бібліотека і власний код).

2022-06-20 11:54 UTC, danmysak commented on backend/app_types.py
> +    words: SolveWords | None
Чому `| None`?

2022-06-20 11:54 UTC, danmysak commented on backend/app_types.py
> +StartPosition = list[int]
Вкажи в коментарі, що рівно два елементи.

2022-06-20 11:54 UTC, danmysak commented on backend/app_types.py
> +class GenerateWord(Word):
Можливо, ще id потрібен?

2022-06-22 16:31 UTC, Fybex commented on backend/app_types.py
> +class GenerateWord(Word):
GenrateWord походить від класу Word, у якого є все потрібне. Перевірте ще раз

2022-06-22 17:06 UTC, danmysak approved these changes

2022-06-22 17:26 UTC, merged