Редюсери для showConfirmation, dismissConfirmation #60
ua-dev-front/crossword-master pull request #63
Opened 2022-09-15 07:04 UTC by Fybex

Fix #60

2022-09-15 08:54 UTC, danmysak approved these changes

2022-09-16 13:04 UTC, danmysak requested changes

2022-09-16 13:04 UTC, danmysak commented on frontend/src/store/index.ts
>      },
Додай експорт для обох екшенів (див. https://github.com/ua-dev-front/crossword-master/pull/67/files#diff-b8386abad60d80adc4b8d9da859d1c43b26bf3abd5463c63e0aed17c0a27a4b0R122).

2022-09-16 18:06 UTC, danmysak approved these changes

2022-09-18 14:31 UTC, TeksPeks approved these changes

2022-09-18 14:39 UTC, merged