Редюсери для switchToDrawing, switchToDrawing, switchToAnswer, switchToPuzzle
ua-dev-front/crossword-master pull request #64
Opened 2022-09-15 07:05 UTC by Fybex

#56

2022-09-15 08:56 UTC, danmysak approved these changes

2022-09-16 13:05 UTC, danmysak requested changes

2022-09-16 13:05 UTC, danmysak commented on frontend/src/store/index.ts
>      },
Додай експорти.

2022-09-16 18:05 UTC, danmysak approved these changes

2022-09-18 14:31 UTC, TeksPeks approved these changes

2022-09-18 14:40 UTC, merged