Редюсер для switchToEnteringQuestions
ua-dev-front/crossword-master pull request #65
Opened 2022-09-16 11:30 UTC by Fybex

Fixes #57

2022-09-16 14:53 UTC, danmysak requested changes

2022-09-16 14:53 UTC, danmysak commented on frontend/src/store/index.ts
> +      };
1) Винеси, мабуть, код, який обчислює `acrossQuestions` та `downQuestions`, в окрему функцію.
2) Із номерами трохи не те: в одній комірці може бути лише одне число, тому нумерація у горизонталей і вертикалей має бути спільна.
3) Чи не вийде уніфікувати код для горизонталей та вертикалей? Див. також https://github.com/ua-dev-front/crossword-master/pull/67/files.

2022-09-16 14:53 UTC, danmysak commented on frontend/src/store/index.ts
> +          const { row, column } = startPosition;
Чому не деструктуризуєш без проміжної змінної `startPosition`?

2022-09-16 14:53 UTC, danmysak commented on frontend/src/store/index.ts
> +          if (cell?.number) {
Не розумію цю умову.

2022-09-16 14:53 UTC, danmysak commented on frontend/src/store/index.ts
> +      );
Експортуй.

2022-09-18 13:22 UTC, Fybex commented on frontend/src/store/index.ts
> +          if (cell?.number) {
Додав `!`

2022-09-18 13:23 UTC, Fybex commented on frontend/src/store/index.ts
> +      };
1. Виніс,
2. Виправив
3. 🤷‍♂️

2022-09-18 13:24 UTC, Fybex commented
Для тестування використовував такий Grid
```
[
    [
      { letter: null, number: null },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    [
      { letter: null, number: null },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    [
      { letter: null, number: null },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    [
      { letter: null, number: null },
      { letter: null, number: null },
      { letter: null, number: null },
      { letter: null, number: null },
      { letter: null, number: null },
      null,
      null,
      null,
      null,
      null
    ],
    [
      null,
      null,
      null,
      { letter: null, number: null },
      null,
      null,
      null,
      null,
      null,
      null
    ],
    [
      null,
      null,
      null,
      { letter: null, number: null },
      null,
      null,
      null,
      null,
      null,
      null
    ],
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ]
  ]
```

2022-09-18 16:55 UTC, danmysak requested changes

2022-09-18 16:55 UTC, danmysak commented on frontend/src/store/index.ts
> +const getQuestionsFromGrid = (grid: State['grid']) => {
1) Чому не `function`?
2) Не знав, що так можна. А може, можна і `State.grid`?

2022-09-18 16:55 UTC, danmysak commented on frontend/src/store/index.ts
> +    for (let column = 0; column < COLUMNS; column++) {
Є сенс брати з самої змінної `grid`.

2022-09-18 16:55 UTC, danmysak commented on frontend/src/store/index.ts
> +          });
Це теж неправильно! Питання з одним і тим самим номером може бути як по горизонталі, так і по вертикалі.

2022-09-20 16:21 UTC, Fybex commented on frontend/src/store/index.ts
> +const getQuestionsFromGrid = (grid: State['grid']) => {
> 1. Чому не `function`?
> 2. Не знав, що так можна. А може, можна і `State.grid`?

1. Виправив
2. Ні

2022-09-20 16:46 UTC, danmysak requested changes

2022-09-20 16:46 UTC, danmysak commented on frontend/src/store/index.ts
>              id: currentId++,
Тестував? Теж неправильно...

2022-09-20 16:46 UTC, danmysak commented on frontend/src/store/index.ts
>    };
Можна все ж таки зменшити дублювання. Якщо потрібно, обговоримо на занятті.

2022-09-22 16:55 UTC, danmysak approved these changes

2022-09-25 14:31 UTC, TeksPeks approved these changes

2022-09-25 14:40 UTC, merged