Update question reducer
ua-dev-front/crossword-master pull request #67
Opened 2022-09-16 13:00 UTC by TeksPeks

Fixes #58

2022-09-16 13:06 UTC, danmysak requested changes

2022-09-16 13:06 UTC, danmysak commented on frontend/src/store/index.ts
> +      if (state.questions) {
Чому `if`? `assert` або знак оклику.

2022-09-16 13:06 UTC, danmysak commented on frontend/src/store/index.ts
> +        state.questions[action.payload.direction][action.payload.id].question =
Це неправильно... `id` — не індекс.

2022-09-16 13:11 UTC, TeksPeks commented on frontend/src/store/index.ts
> +      if (state.questions) {
у нас стоїть правило `Forbidden non-null assertion.eslint`, може відключити його?

2022-09-16 13:18 UTC, danmysak commented on frontend/src/store/index.ts
> +      if (state.questions) {
Спробуй з асертом: `if (...) throw new AssertionError(...)`.

2022-09-16 14:24 UTC, danmysak requested changes

2022-09-16 14:24 UTC, danmysak commented on frontend/src/store/index.ts
> +import { AssertionError } from 'assert';
Це найбільш «системний» імпорт, тому його логічно поставити на перше місце.

2022-09-16 14:24 UTC, danmysak commented on frontend/src/store/index.ts
> +        throw new AssertionError({ message: 'state.questions is null' });
Тут і взагалі повідомлення про помилку має бути human-readable, а не зав’язане на код (у разі потреби програміст і так перейде в цей рядок і побачить, що сталося в термінах коду).

2022-09-16 14:24 UTC, danmysak commented on frontend/src/store/index.ts
> +      );
Ти тестував цей код?..

2022-09-16 17:00 UTC, TeksPeks commented on frontend/src/store/index.ts
> +      );
не тестував, але я його скопіював з коду оновленя питань в `App`

2022-09-16 17:11 UTC, danmysak requested changes

2022-09-16 17:11 UTC, danmysak commented on frontend/src/store/index.ts
> +      }
Домовилися обійтися знаком оклику після реалізації #69.

2022-09-18 14:32 UTC, TeksPeks commented on frontend/src/store/index.ts
> +      );
пофіксив

2022-09-18 14:45 UTC, Fybex requested changes

2022-09-18 14:45 UTC, Fybex commented on frontend/src/store/index.ts
> +      const { direction, id, question } = action.payload;
Чому не зразу дестриктуризовано в параметрах?

2022-09-18 17:00 UTC, danmysak approved these changes

2022-09-18 17:04 UTC, Fybex approved these changes

2022-09-20 14:34 UTC, merged