generate questions reducer
ua-dev-front/crossword-master pull request #72
Opened 2022-09-18 16:28 UTC by TeksPeks

Fixes #59 
Поки що зробив редюсер тільки для `generateQuestions`, і є дві проблеми:
1. На апі не врахований CORS, через що не виходить робити виклики з фетч, додав пулл реквест для цього.
2. `AbortController` не можна зберігати в редаксовому стейті, бо він `non-serializable`, редакс видає таку помилку:
```
A non-serializable value was detected in the state, in the path: `general.fetchAbortController`. Value: AbortController {signal: AbortSignal} 
Take a look at the reducer(s) handling this action type: generateQuestions/pending.
(See https://redux.js.org/faq/organizing-state#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state)
```

2022-09-18 17:13 UTC, danmysak requested changes

2022-09-18 17:13 UTC, danmysak commented on frontend/src/appConstants.ts
>  export const COLUMNS = 10;
Порожній рядок.

2022-09-18 17:13 UTC, danmysak commented on frontend/src/store/index.ts
> +          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
Прибрати.

2022-09-20 16:37 UTC, TeksPeks commented
Поки що тільки доробив `generateQuestions`.
в `tsconfig` поміняв `CompilerOptions.target`: `es5` -> `es6`, бо зі значенням `es5` не можна ітерувати по рядках.

2022-09-20 17:28 UTC, danmysak requested changes

2022-09-20 17:28 UTC, danmysak commented on frontend/tsconfig.json
> +    "target": "ES6",
Домовилися натомість скористатися `split`ом.

2022-09-20 17:28 UTC, danmysak commented on frontend/src/store/index.ts
> +  start_position: CellPosition;
Виправити ім’я змінної.

2022-09-20 17:28 UTC, danmysak commented on frontend/src/store/index.ts
> +      table: grid.map((row) => row.map((cell) => +!!cell)),
`cell ? 1 : 0`

2022-09-20 17:28 UTC, danmysak commented on frontend/src/store/index.ts
> +  return result;
Можна без проміжної змінної.

2022-09-20 17:28 UTC, danmysak commented on frontend/src/store/index.ts
> +      console.log(action);
Якщо нема вбудованого механізму, то `console.error(читабельний текст помилки)`.

2022-09-20 17:28 UTC, danmysak commented on frontend/src/store/index.ts
> +            id: Math.floor(Math.random() * 100), // Shouldn't the id be generated on backend?
id має бути конкретний (обговорили на занятті).

2022-09-20 17:28 UTC, danmysak commented on frontend/src/store/index.ts
> +        questions.map((question) => {
`forEach`

2022-09-20 17:28 UTC, danmysak commented on frontend/src/store/index.ts
> +          [...question.answer].map((character, index) => {
`.split()`, `forEach`, `character` → `letter`

2022-09-20 17:28 UTC, danmysak commented on frontend/src/store/index.ts
> +              number: index === 0 ? Math.floor(Math.random() * 100) : null, // again, should the id be generated on backend?
Див. вище.

2022-09-22 16:05 UTC, TeksPeks commented on frontend/src/store/index.ts
> +  },
для тестування

2022-09-22 16:06 UTC, TeksPeks commented on frontend/src/store/index.ts
> +  start_position: CellPosition;
#77

2022-09-22 16:13 UTC, TeksPeks commented on frontend/src/store/index.ts
> +      console.log(action);
здається нема

2022-09-22 17:26 UTC, danmysak requested changes

2022-09-22 17:26 UTC, danmysak commented on frontend/src/store/index.ts
> +  ],
Тестові дані — лише в App.tsx (і то ненадовго).

2022-09-22 17:26 UTC, danmysak commented on frontend/src/store/index.ts
> +      state.fetchAbortController = fetchAbortController;
Зайва проміжна змінна.

2022-09-22 17:26 UTC, danmysak commented on frontend/src/store/index.ts
> +      state.fetchAbortController = null;
Пробуємо повторити запит через кілька секунд.

2022-09-26 14:20 UTC, TeksPeks commented
зробив редюсер `solveQuestions`, але поки що не тестував, тому що ендпоїнт `solve` повертає неправильні дані.
має повертати
```
{
  "answers": {
    "across": [
      {
        "id": 2,
        "answer": "cross"
      }
    ],
    "down": [
      {
        "id": 1,
        "answer": "disc"
      },
      {
        "id": 3,
        "answer": "son"
      }
    ]
  }
}
```
а повертає
```
  "answers": {
    "across": ["cross"],
    "down": ["disc", "son"]
  }
}
```

2022-10-02 16:52 UTC, TeksPeks commented on frontend/src/store/index.ts
> +  start_position: CellPosition;
виправив

2022-10-02 16:52 UTC, TeksPeks commented on frontend/src/store/index.ts
> +            id: Math.floor(Math.random() * 100), // Shouldn't the id be generated on backend?
виправив

2022-10-02 17:31 UTC, danmysak requested changes

2022-10-02 17:31 UTC, danmysak commented on frontend/src/store/helpers.ts
> +function getQuestionsFromGrid(grid: State['grid']) {
Потрібен тип результату.

2022-10-02 17:31 UTC, danmysak commented on frontend/src/store/index.ts
> +}[];
Типом має бути не масив, а сам базовий об’єкт.

2022-10-02 17:31 UTC, danmysak commented on frontend/src/store/helpers.ts
> +function getQuestionId(
Прибрати функцію.

2022-10-02 17:31 UTC, danmysak commented on frontend/src/store/index.ts
> +}[];
Те саме.

2022-10-02 17:31 UTC, danmysak commented on frontend/src/store/index.ts
> +      table: grid.map((row) => row.map((cell) => (cell ? 1 : 0))),
Див. вище.

2022-10-02 17:31 UTC, danmysak commented on frontend/src/store/index.ts
> +      table: grid.map((row) => row.map((cell) => (cell ? 1 : 0))),
Винести функцію. Можна об’єднати з `getBooleanGrid`.

2022-10-02 17:31 UTC, danmysak commented on frontend/src/store/index.ts
> +            id: getQuestionId(direction as Direction, question, state.grid),
Змінити алгоритм (обговорили на занятті).

2022-10-02 17:31 UTC, danmysak commented on frontend/src/store/index.ts
> +                  ? getQuestionId(direction as Direction, question, state.grid)
Оновити алгоритм.

2022-10-02 17:31 UTC, danmysak commented on frontend/src/store/index.ts
> +      console.error(`Solving questions failed: ${error.stack}`);
Повторювати запит.

2022-10-02 17:31 UTC, danmysak commented on frontend/src/store/index.ts
> +      console.error(`Generating questions failed: ${error.stack}`);
Повторювати запит.

2022-10-02 17:31 UTC, danmysak commented on frontend/src/store/index.ts
> +            ].find((question) => question.id === answer.id)!;
Реалізувати ефективніше — з індексуванням.

2022-10-04 15:43 UTC, danmysak requested changes

2022-10-04 15:43 UTC, danmysak commented on frontend/src/store/index.ts
> +                  ? state.questions![direction as Direction][index].id
Гм... А це точно правильно?

2022-10-04 15:52 UTC, TeksPeks commented on frontend/src/store/index.ts
> +      console.error(`Solving questions failed: ${error.stack}`);
Щоб повторити запит мені треба задіспатчити `solveQuestions` так `store.dispatch(solveQuestions())`, але `store` оголошений нижче.
Єдиний спосіб який я придумав, це діспатчити в функції під оголошенням `store`у, а тут її викликати, але це виглядає дивно

2022-10-04 15:54 UTC, TeksPeks commented on frontend/src/store/index.ts
> +            ].find((question) => question.id === answer.id)!;
Не розумію що таке індексування і як його використовувати

2022-10-06 16:11 UTC, TeksPeks commented on frontend/src/store/index.ts
> +            ].find((question) => question.id === answer.id)!;
зробив

2022-10-06 16:13 UTC, TeksPeks commented on frontend/src/store/index.ts
> +      console.error(`Solving questions failed: ${error.stack}`);
Повторюю прямо в колбеці `createAsyncThunk` з `try catch`

2022-10-06 17:35 UTC, danmysak requested changes

2022-10-06 17:35 UTC, danmysak commented on frontend/src/store/index.ts
> +        return rejectWithValue(error.message);
Здається, цей сценарій не мав би передбачати помилки.

2022-10-06 17:35 UTC, danmysak commented on frontend/src/store/index.ts
> +      return rejectWithValue(error.stack);
`null`

2022-10-06 17:35 UTC, danmysak commented on frontend/src/store/index.ts
> +        return rejectWithValue(error.message);
`null`

2022-10-06 17:35 UTC, danmysak commented on frontend/src/store/index.ts
> +      return rejectWithValue(error.stack);
`null`

2022-10-06 17:35 UTC, danmysak commented on frontend/src/store/index.ts
> +  }
Чи не можна уникнути дублювань логіки?

2022-10-06 17:35 UTC, danmysak commented on frontend/src/store/index.ts
> +    }
`assert`

2022-10-06 17:35 UTC, danmysak commented on frontend/src/store/index.ts
> +    if (error instanceof DOMException) {
`&&`

2022-10-06 17:35 UTC, danmysak commented on frontend/src/store/index.ts
> +      setTimeout(() => dispatch(generateQuestions()), 3000);
Робимо повторний запит одразу, щоб уникнути потенційних багів.

2022-10-09 09:16 UTC, TeksPeks commented on frontend/src/store/index.ts
> +  }
Виніс блок `try catch` у функцію

2022-10-09 09:18 UTC, TeksPeks commented on frontend/src/store/index.ts
> +    }
в тайпскрипті, як я розумію `assert` роблять як раз так, зі `throw new Errror()`, може тільки у функцію можна винести.
https://stackoverflow.com/a/71625025/19630681

2022-10-09 09:19 UTC, TeksPeks commented on frontend/src/store/index.ts
> +    if (error instanceof DOMException) {
поміняв логіку, тепер цієї умови нема

2022-10-09 14:48 UTC, danmysak commented on frontend/src/store/helpers.ts
>  };
1) Зведи ці дві функції в одну, зробивши колбек (який повертає `question.id` в першому випадку і `getStartPositionString(question.startPosition)` у другому) параметром функції. Відповідно, `getStartPositionString` поверни у старий файл і передай сюди як колбек.

2) Задай тип результату функції. Імовірно, тобі знадобляться дженерики.

3) Не зловживай `forEach`. Тут підійшов би звичайний (і більш стандартний) цикл.

2022-10-09 14:48 UTC, danmysak commented on frontend/src/store/index.ts
> +      retryCallback();
1) Тут скоріше має бути дещо інакше: якщо `!(error instanceof Error && error.name === 'AbortError')`. А то код може викинути і щось інше, крім `Error` (саме з цієї причини TS не вважає, що `error` має тип `Error`).

2) Немає сенсу інтерполювати `error` — виведи в консоль саму змінну (її можна буде поклацати тощо).

3) Тестував, що все працює як задумано?

2022-10-09 14:48 UTC, danmysak commented on frontend/src/store/index.ts
> +  body: string,
Є сенс прийняти об’єкт і вже тут серіалізувати.

2022-10-09 14:48 UTC, danmysak commented on frontend/src/store/index.ts
> +): Promise<T | undefined> => {
`undefined` — системна деталь JS. Там, де можна, ми оперуємо «відсутнім значенням» явно. Використай `null` / `return null`.

2022-10-09 14:48 UTC, danmysak commented on frontend/src/store/index.ts
> +  }
Усе одно відчувається суттєве дублювання. Далі звести вже ніяк не можна?

2022-10-09 14:48 UTC, danmysak commented on frontend/src/store/index.ts
> +        return rejectWithValue(error.message);
По-моєму, досі передбачає.

2022-10-09 14:50 UTC, danmysak requested changes
Знов GitHub глючить. Додавав коментарі у рев’ю, а додалися кожен сам по собі.

2022-10-09 15:41 UTC, TeksPeks commented on frontend/src/store/index.ts
> +        return rejectWithValue(error.message);
Треба повертати `rejectWithValue(null)`, бо в іншому випадку запуститься `generateQuestions/fullfilled` з `payload`ом `undefined`

2022-10-09 15:52 UTC, danmysak commented on frontend/src/store/index.ts
> +        return rejectWithValue(error.message);
То так і мало би бути. Чи чим це погано?

2022-10-11 07:49 UTC, TeksPeks commented on frontend/src/store/index.ts
> +        return rejectWithValue(error.message);
В `generateQuestions/fullfilled` виконується код, який повинен виконуватися тільки якщо питання правильно згенерувались, типу створення питань у стейті, чи перемикання моду на `Puzzle`. Можна перевіряти чи `payload` (те що повертається з коллбеку) не `undefined` і в цьому випадку нічого не робити, але тоді нема сенсу викликати цей action взагалі.

2022-10-11 12:11 UTC, danmysak commented on frontend/src/store/index.ts
> +        return rejectWithValue(error.message);
Гаразд, хай тоді дійсно так лишається.

2022-10-11 12:22 UTC, danmysak commented on frontend/src/store/helpers.ts
> +  const indexedQuestions: IndexedQuestions<T> = {} as IndexedQuestions<T>;
Фрагмент `: IndexedQuestions<T>` зайвий.

2022-10-11 12:22 UTC, danmysak commented on frontend/src/store/index.ts
> +  body: unknown,
Мало би бути `any`, а не `unknown`. Але тут можна звузити: `object`.

2022-10-11 12:22 UTC, danmysak commented on frontend/src/store/index.ts
> +      retryCallback();
1 — у коді не так, як я пропонував (і не впевнений, що правильно).
2 — готово.
3 — поки що не отримав відповіді.

2022-10-11 12:24 UTC, danmysak requested changes
-

2022-10-12 14:25 UTC, TeksPeks commented on frontend/src/store/index.ts
> +      retryCallback();
1. виправив
3. тестував, працює, можна перевірити заповнивши одну клітинку і натиснувши кнопку 'Generate questions' (треба буде виправити, якщо заповнювати клітинки по діагоналі також буде помилка)

2022-10-12 14:32 UTC, TeksPeks commented on frontend/src/store/index.ts
> +  }
Звів ще трішки, поки що нема ідей як ще можна звести

2022-10-12 15:11 UTC, danmysak commented on frontend/src/views/DrawingOrErasingView/index.tsx
> +            onClick={() => dispatch(generateQuestions())}
Так само треба замінити для кнопки нижче.

2022-10-12 15:11 UTC, danmysak commented on frontend/src/store/index.ts
> +  }
Гаразд, в принципі вже може бути.

2022-10-12 15:11 UTC, danmysak requested changes
Останній коментар...

2022-10-12 15:56 UTC, danmysak approved these changes

2022-10-12 17:09 UTC, Fybex requested changes

2022-10-12 17:09 UTC, Fybex commented on frontend/src/views/DrawingOrErasingView/index.tsx
> +  const dispatch = useAppDispatch();
Пустий рядок

2022-10-14 08:40 UTC, Fybex approved these changes

2022-10-14 13:27 UTC, merged