Adapt api response
ua-dev-front/crossword-master pull request #79
Opened 2022-09-25 18:39 UTC by TeksPeks

Fixes #75 
Створив окремий тип для відповіді з сервера.

2022-09-26 17:06 UTC, danmysak requested changes

2022-09-26 17:06 UTC, danmysak commented on backend/app.py
> +class GenerateResponseWords(TypedDict):
Позбутися цього типу (використати відразу `GenerateResponse`).

2022-09-26 17:06 UTC, danmysak commented on backend/app.py
> +    for direction, words in asdict(answer).items():
Звести перебір двох напрямів до одного вигляду.

2022-09-28 13:16 UTC, TeksPeks commented on backend/app.py
> +class GenerateResponseWords(TypedDict):
В `TypedDict` не можна типувати вкладені `dict`и, тому залишив так

2022-09-28 15:06 UTC, danmysak requested changes

2022-09-28 15:06 UTC, danmysak commented on backend/app.py
> +from dataclasses import asdict
Порожній рядок.

2022-09-28 15:06 UTC, danmysak commented on backend/app.py
> +    words: GenerateResponseWords | None
`| None` має піти у сигнатуру функції.

2022-09-28 17:31 UTC, danmysak requested changes

2022-09-28 17:31 UTC, danmysak commented on backend/app.py
>  from typing import TypedDict
`typing` — вище.

2022-09-29 15:58 UTC, danmysak requested changes

2022-09-29 15:58 UTC, danmysak commented on backend/app.py
> +        for word in words] for direction, words in asdict(answer).items()}}
1) Виправ форматування (розташування на окремих рядках лівих і правих дужок має бути симетричним).
2) Внеси випадок `{'words': None}` під тернарний оператор.

2022-09-29 23:56 UTC, danmysak requested changes

2022-09-29 23:56 UTC, danmysak commented on backend/app.py
> +            'startPosition': word['start_position']
Кома…

2022-09-30 12:56 UTC, danmysak approved these changes

2022-09-30 12:57 UTC, merged