Fill, erase view
ua-dev-front/crossword-master pull request #80
Opened 2022-09-26 12:28 UTC by Fybex

Fixes #74

2022-09-26 17:36 UTC, danmysak requested changes

2022-09-26 17:36 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +import useAppDispatch from 'hooks/useAppDispatch';
Алфавітний порядок.

2022-09-26 17:36 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +import { Mode } from 'store';
`store` — вище.

2022-09-26 17:36 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +  const CurrentView = viewByMode[mode];
`currentView`.

2022-09-26 17:36 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +import ErasingView from 'views/ErasingView';
Домовилися об’єднати в один view.

2022-09-26 17:36 UTC, danmysak commented on frontend/src/components/Tabs/index.tsx
> +  secondTab: {
`secondaryTab`

2022-09-26 17:36 UTC, danmysak commented on frontend/src/components/Tabs/index.tsx
> +        <div />
Коментар.

2022-09-26 17:36 UTC, danmysak commented on frontend/src/components/Tabs/styles.scss
> +    gap: 0px 0px;
`gap: 0`.

2022-09-26 17:36 UTC, danmysak commented on frontend/src/styles/index.scss
> +  .center {
Домовилися зробити локальним.

2022-09-26 17:36 UTC, danmysak commented on frontend/src/utils/getBooleanGrid.ts
> +export default function getBooleanGrid(grid: State['grid']) {
Після інших змін відпаде необхідність.

2022-09-26 17:36 UTC, danmysak commented on frontend/src/views/DrawingView.tsx
> +  dispatch: AppDispatch;
Краще з колбеками.

2022-09-26 17:36 UTC, danmysak commented on frontend/src/views/ErasingView.tsx
> +  dispatch: AppDispatch;
Краще колбеки.

2022-09-28 11:46 UTC, Fybex commented on frontend/src/views/DrawingView.tsx
> +  dispatch: AppDispatch;
не вийшло

2022-09-28 15:00 UTC, danmysak requested changes

2022-09-28 15:00 UTC, danmysak commented on frontend/src/components/App/index.tsx
> +    }, {} as Record<Mode, JSX.Element>),
Спрости, скориставшись функцією, що створює `<DrawingOrErasingView ...`.

2022-09-28 15:00 UTC, danmysak commented on frontend/src/views/drawingOrErasingView/index.tsx
> +import React from 'react';
Чому назва папки, що містить цей файл, із маленької літери?

2022-09-28 15:00 UTC, danmysak commented on frontend/src/views/drawingOrErasingView/index.tsx
> +  switchToErasing,
Мабуть, за абеткою?..

2022-09-28 15:00 UTC, danmysak commented on frontend/src/views/drawingOrErasingView/index.tsx
> +    gridToTransform.map((row) => row.map((cell) => !!cell));
Використай `useMemo`.

2022-09-28 15:00 UTC, danmysak commented on frontend/src/views/drawingOrErasingView/index.tsx
> +      {grid.every((row) => row.every((cell) => !cell)) ? (
`useMemo`.

2022-09-28 15:00 UTC, danmysak commented on frontend/src/components/Tabs/index.tsx
>      <div className='tabs'>
До речі, написи не мають стрибати при перемиканні: фактична ширина напису має дорівнювати більшій із двох.

2022-09-28 16:58 UTC, Fybex commented on frontend/src/views/drawingOrErasingView/index.tsx
> +  switchToErasing,
Я розмістив в порядку, аналогічному до того, який в `state/index.ts`

2022-09-30 19:59 UTC, Fybex commented on frontend/src/components/Tabs/index.tsx
>      <div className='tabs'>
Також, напевно код з 54 по 75 можна дещо зменшити 🤔

2022-10-01 05:08 UTC, danmysak requested changes
Див. слек.

2022-10-02 07:37 UTC, danmysak requested changes

2022-10-02 07:37 UTC, danmysak commented on frontend/src/components/Tab/index.tsx
> +        <span className={classnames('tab__label', 'tab__hidden-label')}>
`tab__label-hidden`

2022-10-02 07:37 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
> +    grid-area: tab;
А де цей `tab` оголошено?

2022-10-02 07:37 UTC, danmysak commented on frontend/src/components/Tab/index.tsx
> +  alternativeLabel,
Додай коментар, який пояснює призначення поля.

2022-10-02 07:37 UTC, danmysak commented on frontend/src/components/Tabs/index.tsx
> +          alternativeLabel={tab?.alternativeLabel}
А тут точно потрібен знак питання?

2022-10-02 07:37 UTC, danmysak commented on frontend/src/views/DrawingOrErasingView/index.tsx
> +}
Енам тут не до речі. Можна оформити як об’єкт: `const TAB_LABELS = { ...`.

2022-10-02 07:37 UTC, danmysak commented on frontend/src/views/DrawingOrErasingView/index.tsx
> +                  alternativeLabel: TabLabels.Erasing,
Тут і нижче `label` та `alternativeLabel` краще поставити поряд, щоб було краще видно, «що відбувається» (те, що в описі пропсів вони не поспіль — нічого страшного).

2022-10-02 07:37 UTC, danmysak commented on frontend/src/views/DrawingOrErasingView/index.tsx
> +                  alternativeLabel: TabLabels.Erase,
Чи не можна все ж таки уникнути дублювання: замість чотирьох об’єктів описати два або й узагалі один?

2022-10-02 07:37 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
Зараз є певні проблеми з анімацією (можна поставити тривалість 2 секунди, щоб краще було видно): у вибраного таба анімації немає взагалі, а у перемикача вона починається не з того місця. В ідеалі і там, і там має працювати повноцінна анімація переходу.

2022-10-02 16:43 UTC, Fybex commented on frontend/src/views/DrawingOrErasingView/index.tsx
> +}
Прибрав `Enum`

2022-10-02 16:48 UTC, Fybex commented on frontend/src/components/Tab/styles.scss
> +    grid-area: tab;
Додав `grid-template-areas: 'tab';` до батьківського елементу

2022-10-02 16:51 UTC, Fybex commented on frontend/src/views/DrawingOrErasingView/index.tsx
> +                  alternativeLabel: TabLabels.Erase,
Постарався мінімізувати код 🤷‍♂️

2022-10-02 16:55 UTC, danmysak requested changes

2022-10-02 16:55 UTC, danmysak commented on frontend/src/components/Tab/styles.scss
> +  &__label-hidden {
Занеси у блок вище.

2022-10-02 16:55 UTC, danmysak commented on frontend/src/views/DrawingOrErasingView/index.tsx
> +              false
Бракує коми.

2022-10-02 16:55 UTC, danmysak commented on frontend/src/views/DrawingOrErasingView/index.tsx
> +  const getTabByModeAndIsSelected = useCallback(
Чи справді потрібен `useCallback`?

2022-10-02 16:55 UTC, danmysak commented on frontend/src/views/DrawingOrErasingView/index.tsx
> +      };
Ці дві функції мали б жити у спеціалізованому файлі. Але, як на мене, це оверкіл — достатньо простенького словничка.

2022-10-02 16:55 UTC, danmysak commented on frontend/src/views/DrawingOrErasingView/index.tsx
> +          };
Я б залишив один об’єкт, у полях якого застосував тернарний оператор.

2022-10-02 17:00 UTC, Fybex commented on frontend/src/views/DrawingOrErasingView/index.tsx
> +          };
Але тоді тут в кожному полі буде тернарний оператор

2022-10-02 17:01 UTC, Fybex commented on frontend/src/views/DrawingOrErasingView/index.tsx
> +              false
чому тут повинна бути кома

2022-10-02 18:10 UTC, danmysak commented on frontend/src/views/DrawingOrErasingView/index.tsx
> +              false
Причина писати кому така сама, що й для масивів та об’єктів: при додаванні ще одного аргумента до функції цей рядок не доведеться міняти — а це врятована історія для git blame. Тому якщо в тому випадку домовилися, то і тут варто.

2022-10-02 18:10 UTC, danmysak commented on frontend/src/views/DrawingOrErasingView/index.tsx
> +          };
Насправді лише в перших двох. Загальна кількість коду вийде, здається, суттєво меншою.

2022-10-02 18:24 UTC, Fybex commented on frontend/src/views/DrawingOrErasingView/index.tsx
> +          };
Так іконки ж теж відрізняються

2022-10-02 18:39 UTC, danmysak commented on frontend/src/views/DrawingOrErasingView/index.tsx
> +          };
Так. Але в цьому випадку оператор буде не тернарний.

2022-10-04 15:24 UTC, Fybex commented on frontend/src/views/DrawingOrErasingView/index.tsx
> +  const getTabByModeAndIsSelected = useCallback(
Можливо я не до кінця тоді розумію `useCallback`, але я його тут використовую щоб при зміні Props функція не змінювалася, щоб вона змінювалася тільки при першому рендері

2022-10-04 15:32 UTC, danmysak commented on frontend/src/views/DrawingOrErasingView/index.tsx
> +  const getTabByModeAndIsSelected = useCallback(
А навіщо потрібно, щоб вона не змінювалася після першого рендеру?

2022-10-04 16:12 UTC, Fybex commented on frontend/src/views/DrawingOrErasingView/index.tsx
> +  const getTabByModeAndIsSelected = useCallback(
Прибрав

2022-10-04 16:13 UTC, Fybex commented on frontend/src/views/DrawingOrErasingView/index.tsx
> +      };
Зробив словничок `labelByModeAndIsSelected` який знаходиться в новій функції `getLabel`

2022-10-04 16:14 UTC, Fybex commented on frontend/src/components/Tab/styles.scss
Додав `animation`, мені здається це не можна нормально реалізувати з `transition`

2022-10-06 15:18 UTC, Fybex commented on frontend/src/components/Tab/styles.scss
Прибрав `animation`, виправив проблему з анімацією видаленням компонентів-обгорток `DrawingView`, `ErasingView`

2022-10-06 15:31 UTC, danmysak commented on frontend/src/views/DrawingOrErasingView/index.tsx
> +          normal: 'Draw',
Краще `regular`.

2022-10-06 17:00 UTC, danmysak approved these changes

2022-10-08 17:26 UTC, TeksPeks approved these changes

2022-10-08 20:04 UTC, merged