Fix solve endpoint response
ua-dev-front/crossword-master pull request #83
Opened 2022-09-28 12:59 UTC by TeksPeks

Fixes #81

2022-09-28 15:08 UTC, danmysak requested changes
Врахуй зауваження до #79.
Матиме сенс рев’ювити після того, як той PR буде залито.

2022-09-30 18:55 UTC, danmysak requested changes

2022-09-30 18:55 UTC, danmysak commented on backend/app.py
> +        } for index, word in enumerate(value)] for direction, value in words.items()}}
Приведи до того ж вигляду, що `generate`: лапки, перенесення рядків, кожен `for` із нового рядка. Також `value` варто перейменувати на щось інформативніше. Наприклад, `word_list`.

2022-10-01 12:22 UTC, danmysak requested changes

2022-10-01 12:22 UTC, danmysak commented on backend/app.py
> +    ] for direction, words_list in words.items()}}
Відповідно до правил англійської, word list — не words list.
Також знову пропущено кому.

2022-10-02 11:25 UTC, danmysak approved these changes

2022-10-02 16:02 UTC, Fybex approved these changes

2022-10-02 16:05 UTC, merged