Disable editable state of non-clickable(editable) cell
ua-dev-front/crossword-master pull request #88
Opened 2022-10-06 17:14 UTC by Fybex

Fixes #87

2022-10-06 18:22 UTC, danmysak requested changes

2022-10-08 20:07 UTC, Fybex commented on frontend/src/components/Cell/index.tsx
> +
Переробив на перший варіант, який обговорювали на занятті. Мені здається він оптимальний

2022-10-08 20:09 UTC, Fybex commented on frontend/src/components/Grid/index.tsx
> +            : mode === Mode.Draw,
Як? 🤔

2022-10-08 20:09 UTC, Fybex commented on frontend/src/components/Grid/index.tsx
>    );
Замерджив `main`, в якому вже є #80

2022-10-09 05:21 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +            : mode === Mode.Draw,
`editable: mode === (matrix[row][column] ? Mode.Erase : Mode.Draw)`

2022-10-09 08:47 UTC, Fybex commented on frontend/src/components/Grid/index.tsx
> +            : mode === Mode.Draw,
> `editable: mode === (matrix[row][column] ? Mode.Erase : Mode.Draw)`

Точно, не знаю чому не здогадався 👍

2022-10-09 08:48 UTC, danmysak approved these changes

2022-10-09 09:36 UTC, TeksPeks approved these changes

2022-10-09 09:40 UTC, merged