Grid: edit event on drag
ua-dev-front/crossword-master pull request #90
Opened 2022-10-11 10:48 UTC by Fybex

Fixes #78 

Тепер при утримуванні мишки або пальця на сенсорі спрацює `onChange` у `Grid`

2022-10-12 09:13 UTC, danmysak requested changes

2022-10-12 09:13 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +  };
Здається, [цей підхід](https://stackoverflow.com/a/70737325/430083) значно чистіший. Сніпет під дописом начебто дійсно працює.

2022-10-12 09:13 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +      );
Краще просто використати `.closest()`: https://developer.mozilla.org/en-US/docs/Web/API/Element/closest.

Також тепер розумію, навіщо тобі знадобилося чіпляти дані до комірки. Якщо не вийде переробити зовсім, як намічено в іншому коментарі, то мені використання даних здається все ж значно меншим злом.

2022-10-12 09:13 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +      if (row !== -1 && column !== -1) {
Думаю, цю перевірку правильніше робити «upstream» — порівнювати з `-1` сам індекс.

2022-10-14 12:02 UTC, Fybex commented on frontend/src/components/Grid/index.tsx
> +      );
Цей код було прибрано 👍

2022-10-14 12:02 UTC, Fybex commented on frontend/src/components/Grid/index.tsx
> +      if (row !== -1 && column !== -1) {
Цей код було прибрано 👍

2022-10-14 12:25 UTC, danmysak requested changes

2022-10-14 12:25 UTC, danmysak commented on frontend/src/components/Cell/index.tsx
> +      onPointerDown={(event) => handleReleaseCapture(event)}
Назви хендлерів неоднорідні. Краще `handlePointerMove` та `handlePointerDown` (а також, можливо, є сенс поміняти їх місцями, щоб вийшло в хронологічному порядку).

2022-10-14 12:25 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +  useGlobalMouseClickToggle(() => setIsMouseDown(!isMouseDown));
У такому випадку мало б сенс зарефакторити цей хук у `isPointerDown`. Але загалом це, можливо, не зовсім те, що нам потрібно: зараз комірки зафарбуються, навіть якщо початкове натискання було поза грідом.

2022-10-14 12:26 UTC, Fybex commented on frontend/src/components/Grid/index.tsx
> +  useGlobalMouseClickToggle(() => setIsMouseDown(!isMouseDown));
Я ще не запросив re request...ще працюю на над цим

2022-10-14 12:38 UTC, Fybex commented on frontend/src/components/Grid/index.tsx
> +  useGlobalMouseClickToggle(() => setIsMouseDown(!isMouseDown));
> У такому випадку мало б сенс зарефакторити цей хук у `isPointerDown`. Але загалом це, можливо, не зовсім те, що нам потрібно: зараз комірки зафарбуються, навіть якщо початкове натискання було поза грідом.

Перейменував всі `mouse` змінні на `pointer`. Тепер перевіряю чи було початкове натискання в `Grid`

2022-10-14 12:42 UTC, danmysak commented on frontend/src/components/Cell/index.tsx
> +      onPointerDown={(event) => handleReleaseCapture(event)}
Маю на увазі: спочатку `down`, потім `move.

2022-10-14 12:44 UTC, Fybex commented on frontend/src/components/Cell/index.tsx
> +      onPointerDown={(event) => handleReleaseCapture(event)}
> Маю на увазі: спочатку `down`, потім `move`.

...я це розумію... добре, змінив

2022-10-14 12:47 UTC, danmysak requested changes

2022-10-14 12:47 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +  const ref = useRef<HTMLDivElement>(null);
Нема сенсу бути специфічним: можна просто `HTMLElement`.

2022-10-14 12:47 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +    ),
1) Навіщо `!!`? Здається, і так тип булевський...
2) На мій погляд, чистіше буде з `useGlobalMouseClickToggle` передавати параметр, який визначає, чи це down, чи up, безпосередньо.

2022-10-14 12:52 UTC, Fybex commented on frontend/src/components/Grid/index.tsx
> +    ),
1. Без дужок: 
```
Argument of type 'boolean | undefined' is not assignable to parameter of type 'SetStateAction<boolean>'.
  Type 'undefined' is not assignable to type 'SetStateAction<boolean>'.ts(2345)
```

2022-10-14 12:53 UTC, Fybex commented on frontend/src/components/Grid/index.tsx
> +    ),
> Member

Можу написати так  
```
event.type === 'pointerdown' &&
        !!ref.current?.contains(event.target as HTMLElement),
```

2022-10-14 12:54 UTC, Fybex commented on frontend/src/components/Grid/index.tsx
> +  const ref = useRef<HTMLDivElement>(null);
Тоді в рядку 95 ts свариться

2022-10-14 12:54 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +    ),
Ага, точно. Так буде трохи краще.

2022-10-14 13:00 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +  const ref = useRef<HTMLDivElement>(null);
Неінтуїтивно. Що ж, у такому разі варіант https://stackoverflow.com/a/63130433/430083 мені здається трохи кращим, але можна залишити як є.

2022-10-14 17:09 UTC, danmysak requested changes

2022-10-14 17:09 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +import useGlobalPointerClickToggle from 'hooks/useGlobalPointerClickToggle';
`Click` → `State`

2022-10-14 17:09 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +  useGlobalPointerClickToggle((event, isDownEvent) => {
Зайві фігурні дужки.

2022-10-14 17:09 UTC, danmysak commented on frontend/src/hooks/useGlobalPointerClickToggle.ts
> +};
Розділити події на дві категорії.

2022-10-14 17:20 UTC, Fybex commented on frontend/src/hooks/useGlobalPointerClickToggle.ts
> +};
Упростив

2022-10-14 17:23 UTC, danmysak requested changes

2022-10-14 17:23 UTC, danmysak commented on frontend/src/hooks/useGlobalPointerStateToggle.ts
> +      );
Виправити ідентичність функцій.

2022-10-15 18:13 UTC, danmysak requested changes

2022-10-15 18:13 UTC, danmysak commented on frontend/src/hooks/useGlobalPointerStateToggle.ts
> +      document.removeEventListener('pointerup', handlePointerUp);
При оновленні значень `handlePointerDown`/`handlePointerUp` спроба відписки відбудеться за новими значеннями, а отже, старі залишаться підписаними.

2022-10-16 16:27 UTC, danmysak requested changes

2022-10-16 16:27 UTC, danmysak commented on frontend/src/hooks/useGlobalPointerStateToggle.ts
> +      document.removeEventListener('pointerup', pointerUpListener);
А чи є тоді сенс у цих проміжних функціях `handlePointerDown` / `handlePointerUp` та `callbackRef`’і? Може, просто відразу зробити те саме з `callback`’ом?

2022-10-16 17:06 UTC, danmysak approved these changes

2022-10-17 19:57 UTC, TeksPeks requested changes

2022-10-17 19:57 UTC, TeksPeks commented on frontend/src/components/Grid/index.tsx
>    const { mode, matrix } = props;
мені здається, що деструктуризація пропсів має бути зверху, можливо краще навіть в сигнатуру функції її перенести.

2022-10-17 20:38 UTC, Fybex commented on frontend/src/components/Grid/index.tsx
>    const { mode, matrix } = props;
Це цікаве зауваження.
1. Винести в сигнатуру неможливо `props.onChange`
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/46112160/196277939-84794403-4d02-4a69-b398-8839bf01fe08.png">
Звісно можна у всі варіанти типів пододавати `onChange: undefined`, але це дивно
2. Чи повинна бути деструктуризація зверху? 🤔 Вище ми не використовуємо ці змінні, можна було б аргументувати перенесення на верх тим, щоб було краще розуміти що передається в компонент, але це TS, тут і так це зрозуміло.
Що скажете @danmysak, @TeksPeks?

2022-10-18 05:40 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
>    const { mode, matrix } = props;
За такого сценарію, як у нас, погоджуюся з Андрієм.

2022-10-18 06:24 UTC, TeksPeks approved these changes

2022-10-18 06:26 UTC, merged