Failed solving crossword
ua-dev-front/crossword-master pull request #94
Opened 2022-10-14 15:35 UTC by TeksPeks

Fixes #93

2022-10-14 17:21 UTC, danmysak requested changes

2022-10-14 17:21 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +      return 'Solving...';
Має залежати від поточного режиму.

2022-10-14 17:21 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +    </>
Виносимо лоадер у GridWrapper.

2022-10-14 17:21 UTC, danmysak commented on frontend/src/components/Grid/index.tsx
> +          <Loader label={getLoaderLabel()} isLoading={showOverlay} />
`label` має залишатися з останнього «непорожнього значення».

2022-10-16 09:13 UTC, danmysak requested changes

2022-10-16 09:13 UTC, danmysak commented on frontend/src/components/GridWrapper/index.tsx
> +            showOverlay && 'grid-wrapper__overlay_visible',
Краще навпаки: винести у клас стан `_hidden` (бо «типове» значення для компонента — бути видимим).

2022-10-16 09:13 UTC, danmysak commented on frontend/src/components/GridWrapper/index.tsx
> +          <Loader label={loaderLabel} isLoading={showOverlay} />
Краще тоді перейменувати `isLoading` у `display` (бо значення `true` цього пропса не завжди означає, що дійсно відбувається завантаження).

2022-10-16 09:13 UTC, danmysak commented on frontend/src/components/GridWrapper/styles.scss
> +            pointer-events: revert;
Думаю, після зміни клас на `_hidden` буде інакше, але в будь-якому разі цікаво: що робить `revert`? Не знайшов документації.

2022-10-16 15:26 UTC, TeksPeks commented on frontend/src/components/GridWrapper/styles.scss
> +            pointer-events: revert;
Це загальне значення для всіх стилів, яке робить так, якби стиль не був заданий.
https://developer.mozilla.org/en-US/docs/Web/CSS/revert

2022-10-16 15:30 UTC, TeksPeks commented on frontend/src/components/GridWrapper/index.tsx
> +          <Loader label={loaderLabel} isLoading={showOverlay} />
Можливо тоді й `Loader` треба перейменувати. Наприклад в `MessageBox` або якось інше

2022-10-16 15:46 UTC, danmysak commented on frontend/src/components/GridWrapper/index.tsx
> +          <Loader label={loaderLabel} isLoading={showOverlay} />
Чому?

2022-10-16 15:50 UTC, danmysak approved these changes

2022-10-16 16:16 UTC, TeksPeks commented on frontend/src/components/GridWrapper/index.tsx
> +          <Loader label={loaderLabel} isLoading={showOverlay} />
Бо він відображається не тільки під час запитів, а і для помилок

2022-10-16 16:20 UTC, danmysak commented on frontend/src/components/GridWrapper/index.tsx
> +          <Loader label={loaderLabel} isLoading={showOverlay} />
Ага, зрозуміло. Як на мене, нормально і так — усе ж таки він відображає помилку, пов’язану з завантаженням даних.

2022-10-16 16:21 UTC, TeksPeks commented on frontend/src/components/GridWrapper/index.tsx
> +          <Loader label={loaderLabel} isLoading={showOverlay} />
Добре

2022-10-17 21:11 UTC, Fybex requested changes

2022-10-18 05:42 UTC, danmysak commented on frontend/src/components/GridWrapper/index.tsx
> +import React, { ReactNode, useEffect, useState } from 'react';
Безумовно. І висоту рядка заодно збільшити.

2022-10-18 06:02 UTC, TeksPeks commented on frontend/src/components/GridWrapper/index.tsx
> +    setLoaderLabel(getLoaderLabel() ?? loaderLabel);
https://github.com/ua-dev-front/crossword-master/pull/94#discussion_r995975473
коли `getLoaderLabel()` повертає `null` залишається минулий `label`

2022-10-18 06:15 UTC, Fybex commented on frontend/src/components/GridWrapper/index.tsx
> +    setLoaderLabel(getLoaderLabel() ?? loaderLabel);
> [#94 (comment)](https://github.com/ua-dev-front/crossword-master/pull/94#discussion_r995975473) коли `getLoaderLabel()` повертає `null` залишається минулий `label`

А чому тоді так, а не в рядку 34 замість `null` `loaderLabel`?

2022-10-18 06:16 UTC, TeksPeks commented on frontend/src/components/GridWrapper/styles.scss
> +        position: relative; // For the overlay
не знав про це

2022-10-18 06:17 UTC, TeksPeks commented on frontend/src/components/GridWrapper/index.tsx
> +import React, { ReactNode, useEffect, useState } from 'react';
змінив

2022-10-18 06:25 UTC, Fybex requested changes

2022-10-18 06:25 UTC, Fybex commented on frontend/src/components/GridWrapper/index.tsx
> +  const { fetchAbortController, apiFailed, mode } = useAppSelector(
1. Ми наче старалися дотримуватися виклику глобального стану, де можливо з компоненту `App`, щоб зробити малі компоненти більш адаптивними. 
2. Теж саме, до речі, стосується, на мою думку, й `useAppDispatch` в `DrawingOrErasingView`. `onModeChange`, `onCellChange` - колбеки з `dispatch`, так повинні бути реалізовані й інші `actions`. 
P.S. Не впевнений, що 2 стосується цього PR

2022-10-18 06:28 UTC, TeksPeks commented on frontend/src/components/GridWrapper/index.tsx
> +    setLoaderLabel(getLoaderLabel() ?? loaderLabel);
щоб функцію не пов'язувати з додатковою задачею компонента

2022-10-18 06:30 UTC, TeksPeks commented on frontend/src/components/GridWrapper/index.tsx
> +  const { fetchAbortController, apiFailed, mode } = useAppSelector(
1. Ми ж це робили, щоб пропси не змінювати, а всіх цих змінних нема в пропсах цього компоненту

2022-10-18 06:35 UTC, danmysak commented on frontend/src/components/GridWrapper/index.tsx
> +  const { fetchAbortController, apiFailed, mode } = useAppSelector(
Андрій, здається, має цілковиту рацію (коментар Мирослава не дуже зрозумів — чому не можна додати пропсів?).
@Fybex Візьмеш на себе 2?

2022-10-18 07:05 UTC, TeksPeks commented on frontend/src/components/GridWrapper/index.tsx
> +  const { fetchAbortController, apiFailed, mode } = useAppSelector(
1. перемістив в пропси

2022-10-18 08:13 UTC, danmysak commented on frontend/src/components/GridWrapper/index.tsx
> +  const { fetchAbortController, apiFailed, mode } = useAppSelector(
Ідеться не про формальне прокидання параметрів, а про абстрагування компонентів: компоненти мають приймати на вхід не частину стану, а якісь параметри, які мають сенс з _їхнього_ погляду. Перетворенням одного на інше і займається `App`.

2022-10-18 13:57 UTC, Fybex requested changes

2022-10-18 13:57 UTC, Fybex commented on frontend/src/components/App/index.tsx
> +  const { grid, fetchAbortController, apiFailed, mode } = useAppSelector(
`mode` -  найважливіша з цих всіх змінних, вона повинна бути першою

2022-10-18 14:10 UTC, danmysak requested changes

2022-10-18 14:10 UTC, danmysak commented on frontend/src/components/GridWrapper/index.tsx
> +  }, [loaderLabel]);
У такому випадку, мабуть, варто використати `useLayoutEffect`.

2022-10-18 14:10 UTC, Fybex requested changes

2022-10-18 14:10 UTC, Fybex commented on frontend/src/components/App/index.tsx
> +            loaderLabel={getLoaderLabel()}
Чому тут `loaderLabel` одразу після `mode`, `grid`, а в компоненті останнім? Це не критично, але...

2022-10-18 15:18 UTC, danmysak approved these changes

2022-10-18 16:40 UTC, Fybex approved these changes

2022-10-18 16:41 UTC, merged